// Code generated by nhatp.com/go/mock-gen/cmd/go-mock-gen - v1.0.0. DO NOT EDIT.

package rest

import (
	"fmt"
	todocli "github.com/trungnc90/learn-golang/assignments/01_todo_cli"
	"path/filepath"
	"reflect"
	"runtime"
	"strconv"
	"strings"
	"testing"
)

func mockgenCallerLocation(skip int) string {
	_, file, line, _ := runtime.Caller(skip)
	return fmt.Sprintf("%s:%d", filepath.Base(file), line)
}

type mockgenMockMethod interface {
	methodName() string
	interfaceName() string
	buildCallHistory(sb *strings.Builder, header string)
	fatal(index int, msg string)
	panic(msg string)
}

func mockgenMessageWriteArguments(sb *strings.Builder, template string, args []any) {
	maxLen := 0
	for i := 0; i < len(args); i += 2 {
		str, ok := args[i].(string)
		if !ok {
			str = fmt.Sprintf("%v", args[i])
		}
		maxLen = max(maxLen, len(str))
	}

	format := strings.ReplaceAll(template, "[MAX-KEY-LEN]", strconv.Itoa(maxLen))
	for i := 0; i < len(args); i += 2 {
		key, ok := args[i].(string)
		if !ok {
			key = fmt.Sprintf("%v", args[i])
		}

		var val any
		if i+1 < len(args) {
			val = args[i+1]
		}
		sb.WriteString(fmt.Sprintf(format, key, val))
	}
}

func mockgenMessageMatchFail(m mockgenMockMethod, matchedAt string, index int, args []any) string {
	sb := &strings.Builder{}
	sb.WriteString(fmt.Sprintf("%s.%s call #%d did not match\n", m.interfaceName(), m.methodName(), index+1))
	sb.WriteString(fmt.Sprintf("arguments:\n"))
	mockgenMessageWriteArguments(sb, "\t%[MAX-KEY-LEN]s = %#v\n", args)
	sb.WriteString("\n")
	m.buildCallHistory(sb, "call history")
	sb.WriteString(fmt.Sprintf("hint: check the callback passed to Match at %s", matchedAt))
	return sb.String()
}

func mockgenMessageNotImplemented(interfaceName string, methodName string, signature string, createdLocation string, args []any) string {
	sb := &strings.Builder{}
	sb.WriteString(fmt.Sprintf("unexpected call to %s.%s\n", interfaceName, methodName))
	sb.WriteString(fmt.Sprintf("signature: %s.%s%s\n", interfaceName, methodName, signature))
	sb.WriteString(fmt.Sprintf("called at: %s\n", mockgenCallerLocation(3)))
	sb.WriteString("arguments:\n")
	mockgenMessageWriteArguments(sb, "\t%[MAX-KEY-LEN]s = %#v\n", args)

	location := ""
	if createdLocation != "" {
		location = " after " + createdLocation
	}
	sb.WriteString(fmt.Sprintf("\nhint:%s use one of:\n\t[var].EXPECT().%s(t)\n\t[var].STUB().%s(func(...) ...)\n\n", location, methodName, methodName))
	return sb.String()
}

func mockgenMessageCallHistory(sb *strings.Builder, index int, expectedAt string, calledAt string, args []any) string {
	sb.WriteString(fmt.Sprintf("\t#%d expect at: %s\n", index+1, expectedAt))
	sb.WriteString(fmt.Sprintf("\t   called at: %s\n", calledAt))
	sb.WriteString(fmt.Sprintf("\t   arguments:\n"))
	mockgenMessageWriteArguments(sb, "\t\t%[MAX-KEY-LEN]s = %#v\n", args)
	sb.WriteString("\n")
	return sb.String()
}

func mockgenMessageTooManyCalls(m mockgenMockMethod, want int, got int, args []any) string {
	sb := &strings.Builder{}
	sb.WriteString(fmt.Sprintf("too many calls to %s.%s\n", m.interfaceName(), m.methodName()))
	sb.WriteString(fmt.Sprintf("\twant: %d, got: %d\n\n", want, got))
	m.buildCallHistory(sb, "")
	sb.WriteString(fmt.Sprintf("\t#%d expect at: %s\n", got, "missing"))
	sb.WriteString(fmt.Sprintf("\t   called at: %s\n", mockgenCallerLocation(4)))
	sb.WriteString(fmt.Sprintf("\t   arguments:\n"))
	mockgenMessageWriteArguments(sb, "\t\t%[MAX-KEY-LEN]s = %#v\n", args)
	sb.WriteString("\n")
	sb.WriteString(fmt.Sprintf("\thint: remove unexpected call or add 1 more EXPECT:\n\t\t[var].EXPECT().%s(t)\n", m.methodName()))
	return sb.String()
}

func mockgenMessageMatchByNil(m mockgenMockMethod) string {
	sb := &strings.Builder{}
	sb.WriteString(fmt.Sprintf("%s.%s Match received a nil function\n", m.interfaceName(), m.methodName()))
	sb.WriteString("\thint: provide a valid function")
	return sb.String()
}

func mockgenMessageExpectByNil(m mockgenMockMethod) string {
	sb := &strings.Builder{}
	sb.WriteString(fmt.Sprintf("unexpected nil testing.TB in %s.%s\n", m.interfaceName(), m.methodName()))
	sb.WriteString(fmt.Sprintf("\tcalled at: %s\n\n", mockgenCallerLocation(3)))
	sb.WriteString("\thint: EXPECT requires a valid testing.TB, use STUB instead:\n")
	sb.WriteString(fmt.Sprintf("\t\tspy := [var].STUB().%s(func(...) ...)\n", m.methodName()))
	return sb.String()
}

func mockgenMessageExpectAfterStub(m mockgenMockMethod, stubAt string) string {
	sb := &strings.Builder{}
	sb.WriteString(fmt.Sprintf("conflicting usage for %s.%s\n", m.interfaceName(), m.methodName()))
	sb.WriteString(fmt.Sprintf("\t%14s: %s\n", "STUB used at", stubAt))
	sb.WriteString(fmt.Sprintf("\t%14s: %s\n\n", "EXPECT used at", mockgenCallerLocation(3)))
	sb.WriteString("\thint: use either EXPECT or STUB for the same method, not both\n\n")
	return sb.String()
}

func mockgenMessageStubByNil(m mockgenMockMethod, calledAt string) string {
	sb := &strings.Builder{}
	sb.WriteString(fmt.Sprintf("%s.%s STUB received a nil function\n", m.interfaceName(), m.methodName()))
	sb.WriteString(fmt.Sprintf("called at: %s\n\n", calledAt))
	sb.WriteString("hint: provide a valid function\n")
	return sb.String()
}

func mockgenMessageStubAfterExpect(m mockgenMockMethod, expectAt string) string {
	sb := &strings.Builder{}
	sb.WriteString(fmt.Sprintf("conflicting usage for %s.%s\n", m.interfaceName(), m.methodName()))
	sb.WriteString(fmt.Sprintf("\t%14s: %s\n", "EXPECT used at", expectAt))
	sb.WriteString(fmt.Sprintf("\t%14s: %s\n\n", "STUB used at", mockgenCallerLocation(3)))
	sb.WriteString("\thint: use either EXPECT or STUB for the same method, not both\n\n")
	return sb.String()
}

func mockgenMessageDuplicateStub(m mockgenMockMethod, firstUsedAt string) string {
	sb := &strings.Builder{}
	sb.WriteString(fmt.Sprintf("duplicate STUB for %s.%s\n", m.interfaceName(), m.methodName()))
	sb.WriteString(fmt.Sprintf("\t%14s: %s\n", "first used at", firstUsedAt))
	sb.WriteString(fmt.Sprintf("\t%14s: %s\n\n", "second used at", mockgenCallerLocation(3)))
	sb.WriteString(fmt.Sprintf("\thint: %s.%s is already stubbed, remove one of the above\n\n", m.interfaceName(), m.methodName()))
	return sb.String()
}

func mockgenMessageExpectButNotCalled(m mockgenMockMethod, want int, got int, index int) string {
	sb := &strings.Builder{}
	sb.WriteString(fmt.Sprintf("%s.%s was not called as expected\n", m.interfaceName(), m.methodName()))
	sb.WriteString(fmt.Sprintf("\twant: %d, got: %d\n\n", want, got))
	m.buildCallHistory(sb, "")
	sb.WriteString(fmt.Sprintf("\t#%d never called\n\n", index+1))
	sb.WriteString("\thint: add the missing call or remove the EXPECT above")
	return sb.String()
}

func mockgenMessageMatchArgByNil(m mockgenMockMethod, method string) string {
	sb := &strings.Builder{}
	sb.WriteString(fmt.Sprintf("%s.%s %s received a nil function\n", m.interfaceName(), m.methodName(), method))
	sb.WriteString("\thint: provide a valid function")
	return sb.String()
}

func mockgenMessageDuplicateMatchArg(m mockgenMockMethod, method string, firstUsedAt string) string {
	sb := &strings.Builder{}
	sb.WriteString(fmt.Sprintf("duplicate %s for %s.%s\n", method, m.interfaceName(), m.methodName()))
	sb.WriteString(fmt.Sprintf("\t%14s: %s\n\n", "first used at", firstUsedAt))
	sb.WriteString("\thint: each argument can only be matched once, remove one of the above")
	return sb.String()
}

func mockgenMessageMatchArgHint() string {
	return fmt.Sprintf("\thint: check argument matching at %s\n\t\tor use STUB for fine-grained control", mockgenCallerLocation(3))
}

func mockgenMatchArgument[T any](m mockgenMockMethod, index int, name string, got T, match func(T) bool, wants map[string]any, methods map[string]string, hints map[string]string, tb testing.TB, expectAt string) {
	if match == nil || match(got) {
		return
	}
	tb.Helper()

	method := "func(got) bool"
	if v, ok := methods[name]; ok {
		method = v
	}

	hint := fmt.Sprintf("hint: for custom matching use .Match[arg](func(...) bool) at %s\n\tor use STUB for fine-grained control", expectAt)
	if v, ok := hints[name]; ok {
		hint = v
	}

	sb := &strings.Builder{}
	sb.WriteString(fmt.Sprintf("%s.%s call #%d argument \"%s\" did not match\n", m.interfaceName(), m.methodName(), index+1, name))
	if want, ok := wants[name]; ok {
		sb.WriteString(fmt.Sprintf("  want: %#v\n", want))
	}
	sb.WriteString(fmt.Sprintf("   got: %#v\n", got))
	sb.WriteString(fmt.Sprintf("method: %s\n", method))
	sb.WriteString("\n")
	m.buildCallHistory(sb, "call history")
	sb.WriteString(hint)

	tb.Helper()
	m.fatal(index, sb.String())
}

func mockgenReflectEqualMatcher[T any](want T) func(T) bool {
	return func(got T) bool {
		return reflect.DeepEqual(want, got)
	}
}

func mockgenBasicComparisonMatcher[T comparable](want T) func(T) bool {
	return func(got T) bool {
		return want == got
	}
}

func testManager() *manager {
	return &manager{td: &managerTestDouble{location: mockgenCallerLocation(2)}}
}

type managerTestDouble struct {
	location    string
	AddTask     *managerAddTask
	DeleteTask  *managerDeleteTask
	ListTasks   *managerListTasks
	ToggleDone  *managerToggleDone
	UpdateTasks *managerUpdateTasks
}

type manager struct {
	td *managerTestDouble
}

func (m *manager) STUB() *managerStubber {
	return &managerStubber{target: m}
}

func (m *manager) EXPECT() *managerExpecter {
	return &managerExpecter{target: m}
}

func (m *manager) AddTask(cmd *todocli.AddCmd) (*todocli.Task, error) {
	v0, v1, v2 := "Manager", "AddTask", "(cmd AddCmd) (Task, error)"
	v3 := []any{"cmd", cmd}

	if m.td == nil {
		panic(mockgenMessageNotImplemented(v0, v1, v2, "", v3))
	}

	if v4 := m.td.AddTask; v4 != nil {
		switch {
		case v4.stub != nil:
			return v4.invokeStub(cmd)
		case len(v4.expects) > 0:
			v5 := len(v4.Calls)
			if v5 < len(v4.expects) {
				v4.expects[v5].tb.Helper()
			}
			return v4.invokeExpect(cmd)
		}
	}
	panic(mockgenMessageNotImplemented(v0, v1, v2, m.td.location, v3))
}

func (m *manager) DeleteTask(cmd *todocli.DeleteCmd) error {
	v0, v1, v2 := "Manager", "DeleteTask", "(cmd DeleteCmd) error"
	v3 := []any{"cmd", cmd}

	if m.td == nil {
		panic(mockgenMessageNotImplemented(v0, v1, v2, "", v3))
	}

	if v4 := m.td.DeleteTask; v4 != nil {
		switch {
		case v4.stub != nil:
			return v4.invokeStub(cmd)
		case len(v4.expects) > 0:
			v5 := len(v4.Calls)
			if v5 < len(v4.expects) {
				v4.expects[v5].tb.Helper()
			}
			return v4.invokeExpect(cmd)
		}
	}
	panic(mockgenMessageNotImplemented(v0, v1, v2, m.td.location, v3))
}

func (m *manager) ListTasks(cmd *todocli.ListCmd) ([]todocli.Task, error) {
	v0, v1, v2 := "Manager", "ListTasks", "(cmd ListCmd) ([]Task, error)"
	v3 := []any{"cmd", cmd}

	if m.td == nil {
		panic(mockgenMessageNotImplemented(v0, v1, v2, "", v3))
	}

	if v4 := m.td.ListTasks; v4 != nil {
		switch {
		case v4.stub != nil:
			return v4.invokeStub(cmd)
		case len(v4.expects) > 0:
			v5 := len(v4.Calls)
			if v5 < len(v4.expects) {
				v4.expects[v5].tb.Helper()
			}
			return v4.invokeExpect(cmd)
		}
	}
	panic(mockgenMessageNotImplemented(v0, v1, v2, m.td.location, v3))
}

func (m *manager) ToggleDone(cmd *todocli.DoneCmd) (*todocli.Task, error) {
	v0, v1, v2 := "Manager", "ToggleDone", "(cmd DoneCmd) (Task, error)"
	v3 := []any{"cmd", cmd}

	if m.td == nil {
		panic(mockgenMessageNotImplemented(v0, v1, v2, "", v3))
	}

	if v4 := m.td.ToggleDone; v4 != nil {
		switch {
		case v4.stub != nil:
			return v4.invokeStub(cmd)
		case len(v4.expects) > 0:
			v5 := len(v4.Calls)
			if v5 < len(v4.expects) {
				v4.expects[v5].tb.Helper()
			}
			return v4.invokeExpect(cmd)
		}
	}
	panic(mockgenMessageNotImplemented(v0, v1, v2, m.td.location, v3))
}

func (m *manager) UpdateTasks(cmd *todocli.UpdateCmd) (*todocli.Task, error) {
	v0, v1, v2 := "Manager", "UpdateTasks", "(cmd UpdateCmd) (Task, error)"
	v3 := []any{"cmd", cmd}

	if m.td == nil {
		panic(mockgenMessageNotImplemented(v0, v1, v2, "", v3))
	}

	if v4 := m.td.UpdateTasks; v4 != nil {
		switch {
		case v4.stub != nil:
			return v4.invokeStub(cmd)
		case len(v4.expects) > 0:
			v5 := len(v4.Calls)
			if v5 < len(v4.expects) {
				v4.expects[v5].tb.Helper()
			}
			return v4.invokeExpect(cmd)
		}
	}
	panic(mockgenMessageNotImplemented(v0, v1, v2, m.td.location, v3))
}

type managerStubber struct {
	target *manager
}

func (s *managerStubber) AddTask(stub func(cmd *todocli.AddCmd) (*todocli.Task, error)) *managerAddTask {
	if s.target.td == nil {
		s.target.td = &managerTestDouble{}
	}

	m := s.target.td.AddTask
	if m == nil {
		m = &managerAddTask{stubLocation: mockgenCallerLocation(2)}
		s.target.td.AddTask = m
	}

	if stub == nil {
		m.panic(mockgenMessageStubByNil(m, mockgenCallerLocation(2)))
	}

	if m.stub != nil {
		m.panic(mockgenMessageDuplicateStub(m, m.stubLocation))
	}

	if len(m.expects) > 0 {
		m.panic(mockgenMessageStubAfterExpect(m, m.expects[0].location))
	}

	m.stub = stub
	return m
}

func (s *managerStubber) DeleteTask(stub func(cmd *todocli.DeleteCmd) error) *managerDeleteTask {
	if s.target.td == nil {
		s.target.td = &managerTestDouble{}
	}

	m := s.target.td.DeleteTask
	if m == nil {
		m = &managerDeleteTask{stubLocation: mockgenCallerLocation(2)}
		s.target.td.DeleteTask = m
	}

	if stub == nil {
		m.panic(mockgenMessageStubByNil(m, mockgenCallerLocation(2)))
	}

	if m.stub != nil {
		m.panic(mockgenMessageDuplicateStub(m, m.stubLocation))
	}

	if len(m.expects) > 0 {
		m.panic(mockgenMessageStubAfterExpect(m, m.expects[0].location))
	}

	m.stub = stub
	return m
}

func (s *managerStubber) ListTasks(stub func(cmd *todocli.ListCmd) ([]todocli.Task, error)) *managerListTasks {
	if s.target.td == nil {
		s.target.td = &managerTestDouble{}
	}

	m := s.target.td.ListTasks
	if m == nil {
		m = &managerListTasks{stubLocation: mockgenCallerLocation(2)}
		s.target.td.ListTasks = m
	}

	if stub == nil {
		m.panic(mockgenMessageStubByNil(m, mockgenCallerLocation(2)))
	}

	if m.stub != nil {
		m.panic(mockgenMessageDuplicateStub(m, m.stubLocation))
	}

	if len(m.expects) > 0 {
		m.panic(mockgenMessageStubAfterExpect(m, m.expects[0].location))
	}

	m.stub = stub
	return m
}

func (s *managerStubber) ToggleDone(stub func(cmd *todocli.DoneCmd) (*todocli.Task, error)) *managerToggleDone {
	if s.target.td == nil {
		s.target.td = &managerTestDouble{}
	}

	m := s.target.td.ToggleDone
	if m == nil {
		m = &managerToggleDone{stubLocation: mockgenCallerLocation(2)}
		s.target.td.ToggleDone = m
	}

	if stub == nil {
		m.panic(mockgenMessageStubByNil(m, mockgenCallerLocation(2)))
	}

	if m.stub != nil {
		m.panic(mockgenMessageDuplicateStub(m, m.stubLocation))
	}

	if len(m.expects) > 0 {
		m.panic(mockgenMessageStubAfterExpect(m, m.expects[0].location))
	}

	m.stub = stub
	return m
}

func (s *managerStubber) UpdateTasks(stub func(cmd *todocli.UpdateCmd) (*todocli.Task, error)) *managerUpdateTasks {
	if s.target.td == nil {
		s.target.td = &managerTestDouble{}
	}

	m := s.target.td.UpdateTasks
	if m == nil {
		m = &managerUpdateTasks{stubLocation: mockgenCallerLocation(2)}
		s.target.td.UpdateTasks = m
	}

	if stub == nil {
		m.panic(mockgenMessageStubByNil(m, mockgenCallerLocation(2)))
	}

	if m.stub != nil {
		m.panic(mockgenMessageDuplicateStub(m, m.stubLocation))
	}

	if len(m.expects) > 0 {
		m.panic(mockgenMessageStubAfterExpect(m, m.expects[0].location))
	}

	m.stub = stub
	return m
}

type managerExpecter struct {
	target *manager
}

func (e *managerExpecter) AddTask(tb testing.TB) *managerAddTaskExpecter {
	if e.target.td == nil {
		e.target.td = &managerTestDouble{}
	}

	var m = e.target.td.AddTask
	if m == nil {
		m = &managerAddTask{}
		e.target.td.AddTask = m
	}

	if m.stub != nil {
		m.panic(mockgenMessageExpectAfterStub(m, m.stubLocation))
	}

	if tb == nil {
		m.panic(mockgenMessageExpectByNil(m))
	}

	idx := len(m.expects)
	m.expects = append(m.expects, &managerAddTaskExpect{
		location:         mockgenCallerLocation(2),
		matcher:          &managerAddTaskArgumentMatcher{},
		matcherWants:     make(map[string]any),
		matcherMethods:   make(map[string]string),
		matcherHints:     make(map[string]string),
		matcherLocations: make(map[string]string),
		index:            idx,
		tb:               tb,
	})

	tb.Helper()
	tb.Cleanup(func() {
		tb.Helper()
		m.verify(idx)
	})

	return &managerAddTaskExpecter{target: m, expect: m.expects[idx]}
}

func (e *managerExpecter) DeleteTask(tb testing.TB) *managerDeleteTaskExpecter {
	if e.target.td == nil {
		e.target.td = &managerTestDouble{}
	}

	var m = e.target.td.DeleteTask
	if m == nil {
		m = &managerDeleteTask{}
		e.target.td.DeleteTask = m
	}

	if m.stub != nil {
		m.panic(mockgenMessageExpectAfterStub(m, m.stubLocation))
	}

	if tb == nil {
		m.panic(mockgenMessageExpectByNil(m))
	}

	idx := len(m.expects)
	m.expects = append(m.expects, &managerDeleteTaskExpect{
		location:         mockgenCallerLocation(2),
		matcher:          &managerDeleteTaskArgumentMatcher{},
		matcherWants:     make(map[string]any),
		matcherMethods:   make(map[string]string),
		matcherHints:     make(map[string]string),
		matcherLocations: make(map[string]string),
		index:            idx,
		tb:               tb,
	})

	tb.Helper()
	tb.Cleanup(func() {
		tb.Helper()
		m.verify(idx)
	})

	return &managerDeleteTaskExpecter{target: m, expect: m.expects[idx]}
}

func (e *managerExpecter) ListTasks(tb testing.TB) *managerListTasksExpecter {
	if e.target.td == nil {
		e.target.td = &managerTestDouble{}
	}

	var m = e.target.td.ListTasks
	if m == nil {
		m = &managerListTasks{}
		e.target.td.ListTasks = m
	}

	if m.stub != nil {
		m.panic(mockgenMessageExpectAfterStub(m, m.stubLocation))
	}

	if tb == nil {
		m.panic(mockgenMessageExpectByNil(m))
	}

	idx := len(m.expects)
	m.expects = append(m.expects, &managerListTasksExpect{
		location:         mockgenCallerLocation(2),
		matcher:          &managerListTasksArgumentMatcher{},
		matcherWants:     make(map[string]any),
		matcherMethods:   make(map[string]string),
		matcherHints:     make(map[string]string),
		matcherLocations: make(map[string]string),
		index:            idx,
		tb:               tb,
	})

	tb.Helper()
	tb.Cleanup(func() {
		tb.Helper()
		m.verify(idx)
	})

	return &managerListTasksExpecter{target: m, expect: m.expects[idx]}
}

func (e *managerExpecter) ToggleDone(tb testing.TB) *managerToggleDoneExpecter {
	if e.target.td == nil {
		e.target.td = &managerTestDouble{}
	}

	var m = e.target.td.ToggleDone
	if m == nil {
		m = &managerToggleDone{}
		e.target.td.ToggleDone = m
	}

	if m.stub != nil {
		m.panic(mockgenMessageExpectAfterStub(m, m.stubLocation))
	}

	if tb == nil {
		m.panic(mockgenMessageExpectByNil(m))
	}

	idx := len(m.expects)
	m.expects = append(m.expects, &managerToggleDoneExpect{
		location:         mockgenCallerLocation(2),
		matcher:          &managerToggleDoneArgumentMatcher{},
		matcherWants:     make(map[string]any),
		matcherMethods:   make(map[string]string),
		matcherHints:     make(map[string]string),
		matcherLocations: make(map[string]string),
		index:            idx,
		tb:               tb,
	})

	tb.Helper()
	tb.Cleanup(func() {
		tb.Helper()
		m.verify(idx)
	})

	return &managerToggleDoneExpecter{target: m, expect: m.expects[idx]}
}

func (e *managerExpecter) UpdateTasks(tb testing.TB) *managerUpdateTasksExpecter {
	if e.target.td == nil {
		e.target.td = &managerTestDouble{}
	}

	var m = e.target.td.UpdateTasks
	if m == nil {
		m = &managerUpdateTasks{}
		e.target.td.UpdateTasks = m
	}

	if m.stub != nil {
		m.panic(mockgenMessageExpectAfterStub(m, m.stubLocation))
	}

	if tb == nil {
		m.panic(mockgenMessageExpectByNil(m))
	}

	idx := len(m.expects)
	m.expects = append(m.expects, &managerUpdateTasksExpect{
		location:         mockgenCallerLocation(2),
		matcher:          &managerUpdateTasksArgumentMatcher{},
		matcherWants:     make(map[string]any),
		matcherMethods:   make(map[string]string),
		matcherHints:     make(map[string]string),
		matcherLocations: make(map[string]string),
		index:            idx,
		tb:               tb,
	})

	tb.Helper()
	tb.Cleanup(func() {
		tb.Helper()
		m.verify(idx)
	})

	return &managerUpdateTasksExpecter{target: m, expect: m.expects[idx]}
}

type managerAddTask struct {
	Calls        []managerAddTaskCall
	stub         func(cmd *todocli.AddCmd) (*todocli.Task, error)
	stubLocation string
	expects      []*managerAddTaskExpect
	verified     bool
}

func (m *managerAddTask) methodName() string {
	return "AddTask"
}

func (m *managerAddTask) interfaceName() string {
	return "Manager"
}

func (m *managerAddTask) fatal(index int, msg string) {
	m.verified = true
	m.expects[index].tb.Helper()
	m.expects[index].tb.Fatal(msg)
}

func (m *managerAddTask) panic(msg string) {
	m.verified = true
	panic(msg)
}

func (m *managerAddTask) buildCallHistory(sb *strings.Builder, header string) {
	if header != "" && len(m.Calls) != 0 {
		sb.WriteString(fmt.Sprintf("%s:\n", header))
	}

	for i, v := range m.Calls {
		a := []any{"cmd", v.Argument.cmd}
		mockgenMessageCallHistory(sb, i, m.expects[i].location, v.Location, a)
	}
}

func (m *managerAddTask) invokeStub(cmd *todocli.AddCmd) (*todocli.Task, error) {
	v0, v1 := m.stub(cmd)
	return m.capture(managerAddTaskArgument{cmd: cmd}, managerAddTaskReturn{first: v0, second: v1})
}

func (m *managerAddTask) invokeExpect(cmd *todocli.AddCmd) (*todocli.Task, error) {
	v0 := []any{"cmd", cmd}

	v1 := len(m.Calls)
	if v1 >= len(m.expects) {
		m.panic(mockgenMessageTooManyCalls(m, len(m.expects), v1+1, v0))
	}

	v2 := m.expects[v1]
	if v2.match != nil && !v2.match(cmd) {
		v2.tb.Helper()
		m.fatal(v1, mockgenMessageMatchFail(m, v2.matchLocation, v1, v0))
	}

	v2.tb.Helper()
	mockgenMatchArgument(m, v1, "cmd", cmd, v2.matcher.cmd, v2.matcherWants, v2.matcherMethods, v2.matcherHints, v2.tb, v2.matcherLocations["cmd"])

	return m.capture(managerAddTaskArgument{cmd: cmd}, v2.returns)
}

func (m *managerAddTask) capture(args managerAddTaskArgument, returns managerAddTaskReturn) (*todocli.Task, error) {
	m.Calls = append(m.Calls, managerAddTaskCall{Location: mockgenCallerLocation(4), Argument: args, Return: returns})
	return returns.first, returns.second
}

func (m *managerAddTask) verify(index int) {
	if !m.verified && index >= len(m.Calls) {
		m.expects[index].tb.Helper()
		m.expects[index].tb.Fatal(mockgenMessageExpectButNotCalled(m, len(m.expects), len(m.Calls), index))
	}
}

type managerAddTaskCall struct {
	Location string
	Argument managerAddTaskArgument
	Return   managerAddTaskReturn
}

type managerAddTaskArgument struct {
	cmd *todocli.AddCmd
}

type managerAddTaskArgumentMatcher struct {
	cmd func(cmd *todocli.AddCmd) bool
}

type managerAddTaskReturn struct {
	first  *todocli.Task
	second error
}

type managerAddTaskExpect struct {
	match            func(cmd *todocli.AddCmd) bool
	matchLocation    string
	matcher          *managerAddTaskArgumentMatcher
	matcherWants     map[string]any
	matcherMethods   map[string]string
	matcherHints     map[string]string
	matcherLocations map[string]string
	returns          managerAddTaskReturn
	location         string
	index            int
	tb               testing.TB
}

type managerAddTaskExpecter struct {
	expect *managerAddTaskExpect
	target *managerAddTask
}

func (e *managerAddTaskExpecter) Return(first *todocli.Task, second error) {
	e.expect.returns = managerAddTaskReturn{first: first, second: second}
}

func (e *managerAddTaskExpecter) Match(matcher func(cmd *todocli.AddCmd) bool) *managerAddTaskExpecterWithMatch {
	if matcher == nil {
		e.expect.tb.Helper()
		e.target.fatal(e.expect.index, mockgenMessageMatchByNil(e.target))
	}

	e.expect.match = matcher
	e.expect.matchLocation = mockgenCallerLocation(2)
	return &managerAddTaskExpecterWithMatch{expect: e.expect}
}

func (e *managerAddTaskExpecter) MatchCmd(matcher func(cmd *todocli.AddCmd) bool) *managerAddTaskExpecterWithMatchArg {
	if matcher == nil {
		e.expect.tb.Helper()
		e.target.fatal(e.expect.index, mockgenMessageMatchArgByNil(e.target, "MatchCmd"))
	}

	e.expect.matcher.cmd = matcher
	e.expect.matcherLocations["cmd"] = mockgenCallerLocation(2)
	e.expect.matcherHints["cmd"] = mockgenMessageMatchArgHint()
	return &managerAddTaskExpecterWithMatchArg{expect: e.expect, target: e.target}
}

func (e *managerAddTaskExpecter) With(cmd *todocli.AddCmd) *managerAddTaskExpecterWithValue {
	e.WithCmd(cmd)
	e.expect.matcherLocations["cmd"] = mockgenCallerLocation(2)

	return &managerAddTaskExpecterWithValue{expect: e.expect}
}

func (e *managerAddTaskExpecter) WithCmd(cmd *todocli.AddCmd) *managerAddTaskExpecterWithValueArg {
	e.expect.matcher.cmd = mockgenBasicComparisonMatcher(cmd)
	e.expect.matcherWants["cmd"] = cmd
	e.expect.matcherMethods["cmd"] = "=="
	e.expect.matcherLocations["cmd"] = mockgenCallerLocation(2)

	return &managerAddTaskExpecterWithValueArg{expect: e.expect, target: e.target}
}

type managerAddTaskExpecterWithMatch struct {
	expect *managerAddTaskExpect
}

func (e *managerAddTaskExpecterWithMatch) Return(first *todocli.Task, second error) {
	e.expect.returns = managerAddTaskReturn{first: first, second: second}
}

type managerAddTaskExpecterWithMatchArg struct {
	expect *managerAddTaskExpect
	target *managerAddTask
}

func (e *managerAddTaskExpecterWithMatchArg) Return(first *todocli.Task, second error) {
	e.expect.returns = managerAddTaskReturn{first: first, second: second}
}

func (e *managerAddTaskExpecterWithMatchArg) MatchCmd(matcher func(cmd *todocli.AddCmd) bool) *managerAddTaskExpecterWithMatchArg {
	if matcher == nil {
		e.expect.tb.Helper()
		e.target.fatal(e.expect.index, mockgenMessageMatchArgByNil(e.target, "MatchCmd"))
	}

	if e.expect.matcher.cmd != nil {
		e.expect.tb.Helper()
		e.target.fatal(e.expect.index, mockgenMessageDuplicateMatchArg(e.target, "MatchCmd", e.expect.matcherLocations["cmd"]))
	}

	e.expect.matcher.cmd = matcher
	e.expect.matcherLocations["cmd"] = mockgenCallerLocation(2)
	e.expect.matcherHints["cmd"] = mockgenMessageMatchArgHint()
	return e
}

type managerAddTaskExpecterWithValue struct {
	expect *managerAddTaskExpect
}

func (e *managerAddTaskExpecterWithValue) Return(first *todocli.Task, second error) {
	e.expect.returns = managerAddTaskReturn{first: first, second: second}
}

type managerAddTaskExpecterWithValueArg struct {
	expect *managerAddTaskExpect
	target *managerAddTask
}

func (e *managerAddTaskExpecterWithValueArg) Return(first *todocli.Task, second error) {
	e.expect.returns = managerAddTaskReturn{first: first, second: second}
}

func (e *managerAddTaskExpecterWithValueArg) WithCmd(cmd *todocli.AddCmd) *managerAddTaskExpecterWithValueArg {
	if e.expect.matcher.cmd != nil {
		e.expect.tb.Helper()
		e.target.fatal(e.expect.index, mockgenMessageDuplicateMatchArg(e.target, "WithCmd", e.expect.matcherLocations["cmd"]))
	}

	e.expect.matcher.cmd = mockgenBasicComparisonMatcher(cmd)
	e.expect.matcherWants["cmd"] = cmd
	e.expect.matcherMethods["cmd"] = "=="
	e.expect.matcherLocations["cmd"] = mockgenCallerLocation(2)

	return e
}

type managerDeleteTask struct {
	Calls        []managerDeleteTaskCall
	stub         func(cmd *todocli.DeleteCmd) error
	stubLocation string
	expects      []*managerDeleteTaskExpect
	verified     bool
}

func (m *managerDeleteTask) methodName() string {
	return "DeleteTask"
}

func (m *managerDeleteTask) interfaceName() string {
	return "Manager"
}

func (m *managerDeleteTask) fatal(index int, msg string) {
	m.verified = true
	m.expects[index].tb.Helper()
	m.expects[index].tb.Fatal(msg)
}

func (m *managerDeleteTask) panic(msg string) {
	m.verified = true
	panic(msg)
}

func (m *managerDeleteTask) buildCallHistory(sb *strings.Builder, header string) {
	if header != "" && len(m.Calls) != 0 {
		sb.WriteString(fmt.Sprintf("%s:\n", header))
	}

	for i, v := range m.Calls {
		a := []any{"cmd", v.Argument.cmd}
		mockgenMessageCallHistory(sb, i, m.expects[i].location, v.Location, a)
	}
}

func (m *managerDeleteTask) invokeStub(cmd *todocli.DeleteCmd) error {
	v0 := m.stub(cmd)
	return m.capture(managerDeleteTaskArgument{cmd: cmd}, managerDeleteTaskReturn{first: v0})
}

func (m *managerDeleteTask) invokeExpect(cmd *todocli.DeleteCmd) error {
	v0 := []any{"cmd", cmd}

	v1 := len(m.Calls)
	if v1 >= len(m.expects) {
		m.panic(mockgenMessageTooManyCalls(m, len(m.expects), v1+1, v0))
	}

	v2 := m.expects[v1]
	if v2.match != nil && !v2.match(cmd) {
		v2.tb.Helper()
		m.fatal(v1, mockgenMessageMatchFail(m, v2.matchLocation, v1, v0))
	}

	v2.tb.Helper()
	mockgenMatchArgument(m, v1, "cmd", cmd, v2.matcher.cmd, v2.matcherWants, v2.matcherMethods, v2.matcherHints, v2.tb, v2.matcherLocations["cmd"])

	return m.capture(managerDeleteTaskArgument{cmd: cmd}, v2.returns)
}

func (m *managerDeleteTask) capture(args managerDeleteTaskArgument, returns managerDeleteTaskReturn) error {
	m.Calls = append(m.Calls, managerDeleteTaskCall{Location: mockgenCallerLocation(4), Argument: args, Return: returns})
	return returns.first
}

func (m *managerDeleteTask) verify(index int) {
	if !m.verified && index >= len(m.Calls) {
		m.expects[index].tb.Helper()
		m.expects[index].tb.Fatal(mockgenMessageExpectButNotCalled(m, len(m.expects), len(m.Calls), index))
	}
}

type managerDeleteTaskCall struct {
	Location string
	Argument managerDeleteTaskArgument
	Return   managerDeleteTaskReturn
}

type managerDeleteTaskArgument struct {
	cmd *todocli.DeleteCmd
}

type managerDeleteTaskArgumentMatcher struct {
	cmd func(cmd *todocli.DeleteCmd) bool
}

type managerDeleteTaskReturn struct {
	first error
}

type managerDeleteTaskExpect struct {
	match            func(cmd *todocli.DeleteCmd) bool
	matchLocation    string
	matcher          *managerDeleteTaskArgumentMatcher
	matcherWants     map[string]any
	matcherMethods   map[string]string
	matcherHints     map[string]string
	matcherLocations map[string]string
	returns          managerDeleteTaskReturn
	location         string
	index            int
	tb               testing.TB
}

type managerDeleteTaskExpecter struct {
	expect *managerDeleteTaskExpect
	target *managerDeleteTask
}

func (e *managerDeleteTaskExpecter) Return(first error) {
	e.expect.returns = managerDeleteTaskReturn{first: first}
}

func (e *managerDeleteTaskExpecter) Match(matcher func(cmd *todocli.DeleteCmd) bool) *managerDeleteTaskExpecterWithMatch {
	if matcher == nil {
		e.expect.tb.Helper()
		e.target.fatal(e.expect.index, mockgenMessageMatchByNil(e.target))
	}

	e.expect.match = matcher
	e.expect.matchLocation = mockgenCallerLocation(2)
	return &managerDeleteTaskExpecterWithMatch{expect: e.expect}
}

func (e *managerDeleteTaskExpecter) MatchCmd(matcher func(cmd *todocli.DeleteCmd) bool) *managerDeleteTaskExpecterWithMatchArg {
	if matcher == nil {
		e.expect.tb.Helper()
		e.target.fatal(e.expect.index, mockgenMessageMatchArgByNil(e.target, "MatchCmd"))
	}

	e.expect.matcher.cmd = matcher
	e.expect.matcherLocations["cmd"] = mockgenCallerLocation(2)
	e.expect.matcherHints["cmd"] = mockgenMessageMatchArgHint()
	return &managerDeleteTaskExpecterWithMatchArg{expect: e.expect, target: e.target}
}

func (e *managerDeleteTaskExpecter) With(cmd *todocli.DeleteCmd) *managerDeleteTaskExpecterWithValue {
	e.WithCmd(cmd)
	e.expect.matcherLocations["cmd"] = mockgenCallerLocation(2)

	return &managerDeleteTaskExpecterWithValue{expect: e.expect}
}

func (e *managerDeleteTaskExpecter) WithCmd(cmd *todocli.DeleteCmd) *managerDeleteTaskExpecterWithValueArg {
	e.expect.matcher.cmd = mockgenBasicComparisonMatcher(cmd)
	e.expect.matcherWants["cmd"] = cmd
	e.expect.matcherMethods["cmd"] = "=="
	e.expect.matcherLocations["cmd"] = mockgenCallerLocation(2)

	return &managerDeleteTaskExpecterWithValueArg{expect: e.expect, target: e.target}
}

type managerDeleteTaskExpecterWithMatch struct {
	expect *managerDeleteTaskExpect
}

func (e *managerDeleteTaskExpecterWithMatch) Return(first error) {
	e.expect.returns = managerDeleteTaskReturn{first: first}
}

type managerDeleteTaskExpecterWithMatchArg struct {
	expect *managerDeleteTaskExpect
	target *managerDeleteTask
}

func (e *managerDeleteTaskExpecterWithMatchArg) Return(first error) {
	e.expect.returns = managerDeleteTaskReturn{first: first}
}

func (e *managerDeleteTaskExpecterWithMatchArg) MatchCmd(matcher func(cmd *todocli.DeleteCmd) bool) *managerDeleteTaskExpecterWithMatchArg {
	if matcher == nil {
		e.expect.tb.Helper()
		e.target.fatal(e.expect.index, mockgenMessageMatchArgByNil(e.target, "MatchCmd"))
	}

	if e.expect.matcher.cmd != nil {
		e.expect.tb.Helper()
		e.target.fatal(e.expect.index, mockgenMessageDuplicateMatchArg(e.target, "MatchCmd", e.expect.matcherLocations["cmd"]))
	}

	e.expect.matcher.cmd = matcher
	e.expect.matcherLocations["cmd"] = mockgenCallerLocation(2)
	e.expect.matcherHints["cmd"] = mockgenMessageMatchArgHint()
	return e
}

type managerDeleteTaskExpecterWithValue struct {
	expect *managerDeleteTaskExpect
}

func (e *managerDeleteTaskExpecterWithValue) Return(first error) {
	e.expect.returns = managerDeleteTaskReturn{first: first}
}

type managerDeleteTaskExpecterWithValueArg struct {
	expect *managerDeleteTaskExpect
	target *managerDeleteTask
}

func (e *managerDeleteTaskExpecterWithValueArg) Return(first error) {
	e.expect.returns = managerDeleteTaskReturn{first: first}
}

func (e *managerDeleteTaskExpecterWithValueArg) WithCmd(cmd *todocli.DeleteCmd) *managerDeleteTaskExpecterWithValueArg {
	if e.expect.matcher.cmd != nil {
		e.expect.tb.Helper()
		e.target.fatal(e.expect.index, mockgenMessageDuplicateMatchArg(e.target, "WithCmd", e.expect.matcherLocations["cmd"]))
	}

	e.expect.matcher.cmd = mockgenBasicComparisonMatcher(cmd)
	e.expect.matcherWants["cmd"] = cmd
	e.expect.matcherMethods["cmd"] = "=="
	e.expect.matcherLocations["cmd"] = mockgenCallerLocation(2)

	return e
}

type managerListTasks struct {
	Calls        []managerListTasksCall
	stub         func(cmd *todocli.ListCmd) ([]todocli.Task, error)
	stubLocation string
	expects      []*managerListTasksExpect
	verified     bool
}

func (m *managerListTasks) methodName() string {
	return "ListTasks"
}

func (m *managerListTasks) interfaceName() string {
	return "Manager"
}

func (m *managerListTasks) fatal(index int, msg string) {
	m.verified = true
	m.expects[index].tb.Helper()
	m.expects[index].tb.Fatal(msg)
}

func (m *managerListTasks) panic(msg string) {
	m.verified = true
	panic(msg)
}

func (m *managerListTasks) buildCallHistory(sb *strings.Builder, header string) {
	if header != "" && len(m.Calls) != 0 {
		sb.WriteString(fmt.Sprintf("%s:\n", header))
	}

	for i, v := range m.Calls {
		a := []any{"cmd", v.Argument.cmd}
		mockgenMessageCallHistory(sb, i, m.expects[i].location, v.Location, a)
	}
}

func (m *managerListTasks) invokeStub(cmd *todocli.ListCmd) ([]todocli.Task, error) {
	v0, v1 := m.stub(cmd)
	return m.capture(managerListTasksArgument{cmd: cmd}, managerListTasksReturn{first: v0, second: v1})
}

func (m *managerListTasks) invokeExpect(cmd *todocli.ListCmd) ([]todocli.Task, error) {
	v0 := []any{"cmd", cmd}

	v1 := len(m.Calls)
	if v1 >= len(m.expects) {
		m.panic(mockgenMessageTooManyCalls(m, len(m.expects), v1+1, v0))
	}

	v2 := m.expects[v1]
	if v2.match != nil && !v2.match(cmd) {
		v2.tb.Helper()
		m.fatal(v1, mockgenMessageMatchFail(m, v2.matchLocation, v1, v0))
	}

	v2.tb.Helper()
	mockgenMatchArgument(m, v1, "cmd", cmd, v2.matcher.cmd, v2.matcherWants, v2.matcherMethods, v2.matcherHints, v2.tb, v2.matcherLocations["cmd"])

	return m.capture(managerListTasksArgument{cmd: cmd}, v2.returns)
}

func (m *managerListTasks) capture(args managerListTasksArgument, returns managerListTasksReturn) ([]todocli.Task, error) {
	m.Calls = append(m.Calls, managerListTasksCall{Location: mockgenCallerLocation(4), Argument: args, Return: returns})
	return returns.first, returns.second
}

func (m *managerListTasks) verify(index int) {
	if !m.verified && index >= len(m.Calls) {
		m.expects[index].tb.Helper()
		m.expects[index].tb.Fatal(mockgenMessageExpectButNotCalled(m, len(m.expects), len(m.Calls), index))
	}
}

type managerListTasksCall struct {
	Location string
	Argument managerListTasksArgument
	Return   managerListTasksReturn
}

type managerListTasksArgument struct {
	cmd *todocli.ListCmd
}

type managerListTasksArgumentMatcher struct {
	cmd func(cmd *todocli.ListCmd) bool
}

type managerListTasksReturn struct {
	first  []todocli.Task
	second error
}

type managerListTasksExpect struct {
	match            func(cmd *todocli.ListCmd) bool
	matchLocation    string
	matcher          *managerListTasksArgumentMatcher
	matcherWants     map[string]any
	matcherMethods   map[string]string
	matcherHints     map[string]string
	matcherLocations map[string]string
	returns          managerListTasksReturn
	location         string
	index            int
	tb               testing.TB
}

type managerListTasksExpecter struct {
	expect *managerListTasksExpect
	target *managerListTasks
}

func (e *managerListTasksExpecter) Return(first []todocli.Task, second error) {
	e.expect.returns = managerListTasksReturn{first: first, second: second}
}

func (e *managerListTasksExpecter) Match(matcher func(cmd *todocli.ListCmd) bool) *managerListTasksExpecterWithMatch {
	if matcher == nil {
		e.expect.tb.Helper()
		e.target.fatal(e.expect.index, mockgenMessageMatchByNil(e.target))
	}

	e.expect.match = matcher
	e.expect.matchLocation = mockgenCallerLocation(2)
	return &managerListTasksExpecterWithMatch{expect: e.expect}
}

func (e *managerListTasksExpecter) MatchCmd(matcher func(cmd *todocli.ListCmd) bool) *managerListTasksExpecterWithMatchArg {
	if matcher == nil {
		e.expect.tb.Helper()
		e.target.fatal(e.expect.index, mockgenMessageMatchArgByNil(e.target, "MatchCmd"))
	}

	e.expect.matcher.cmd = matcher
	e.expect.matcherLocations["cmd"] = mockgenCallerLocation(2)
	e.expect.matcherHints["cmd"] = mockgenMessageMatchArgHint()
	return &managerListTasksExpecterWithMatchArg{expect: e.expect, target: e.target}
}

func (e *managerListTasksExpecter) With(cmd *todocli.ListCmd) *managerListTasksExpecterWithValue {
	e.WithCmd(cmd)
	e.expect.matcherLocations["cmd"] = mockgenCallerLocation(2)

	return &managerListTasksExpecterWithValue{expect: e.expect}
}

func (e *managerListTasksExpecter) WithCmd(cmd *todocli.ListCmd) *managerListTasksExpecterWithValueArg {
	e.expect.matcher.cmd = mockgenBasicComparisonMatcher(cmd)
	e.expect.matcherWants["cmd"] = cmd
	e.expect.matcherMethods["cmd"] = "=="
	e.expect.matcherLocations["cmd"] = mockgenCallerLocation(2)

	return &managerListTasksExpecterWithValueArg{expect: e.expect, target: e.target}
}

type managerListTasksExpecterWithMatch struct {
	expect *managerListTasksExpect
}

func (e *managerListTasksExpecterWithMatch) Return(first []todocli.Task, second error) {
	e.expect.returns = managerListTasksReturn{first: first, second: second}
}

type managerListTasksExpecterWithMatchArg struct {
	expect *managerListTasksExpect
	target *managerListTasks
}

func (e *managerListTasksExpecterWithMatchArg) Return(first []todocli.Task, second error) {
	e.expect.returns = managerListTasksReturn{first: first, second: second}
}

func (e *managerListTasksExpecterWithMatchArg) MatchCmd(matcher func(cmd *todocli.ListCmd) bool) *managerListTasksExpecterWithMatchArg {
	if matcher == nil {
		e.expect.tb.Helper()
		e.target.fatal(e.expect.index, mockgenMessageMatchArgByNil(e.target, "MatchCmd"))
	}

	if e.expect.matcher.cmd != nil {
		e.expect.tb.Helper()
		e.target.fatal(e.expect.index, mockgenMessageDuplicateMatchArg(e.target, "MatchCmd", e.expect.matcherLocations["cmd"]))
	}

	e.expect.matcher.cmd = matcher
	e.expect.matcherLocations["cmd"] = mockgenCallerLocation(2)
	e.expect.matcherHints["cmd"] = mockgenMessageMatchArgHint()
	return e
}

type managerListTasksExpecterWithValue struct {
	expect *managerListTasksExpect
}

func (e *managerListTasksExpecterWithValue) Return(first []todocli.Task, second error) {
	e.expect.returns = managerListTasksReturn{first: first, second: second}
}

type managerListTasksExpecterWithValueArg struct {
	expect *managerListTasksExpect
	target *managerListTasks
}

func (e *managerListTasksExpecterWithValueArg) Return(first []todocli.Task, second error) {
	e.expect.returns = managerListTasksReturn{first: first, second: second}
}

func (e *managerListTasksExpecterWithValueArg) WithCmd(cmd *todocli.ListCmd) *managerListTasksExpecterWithValueArg {
	if e.expect.matcher.cmd != nil {
		e.expect.tb.Helper()
		e.target.fatal(e.expect.index, mockgenMessageDuplicateMatchArg(e.target, "WithCmd", e.expect.matcherLocations["cmd"]))
	}

	e.expect.matcher.cmd = mockgenBasicComparisonMatcher(cmd)
	e.expect.matcherWants["cmd"] = cmd
	e.expect.matcherMethods["cmd"] = "=="
	e.expect.matcherLocations["cmd"] = mockgenCallerLocation(2)

	return e
}

type managerToggleDone struct {
	Calls        []managerToggleDoneCall
	stub         func(cmd *todocli.DoneCmd) (*todocli.Task, error)
	stubLocation string
	expects      []*managerToggleDoneExpect
	verified     bool
}

func (m *managerToggleDone) methodName() string {
	return "ToggleDone"
}

func (m *managerToggleDone) interfaceName() string {
	return "Manager"
}

func (m *managerToggleDone) fatal(index int, msg string) {
	m.verified = true
	m.expects[index].tb.Helper()
	m.expects[index].tb.Fatal(msg)
}

func (m *managerToggleDone) panic(msg string) {
	m.verified = true
	panic(msg)
}

func (m *managerToggleDone) buildCallHistory(sb *strings.Builder, header string) {
	if header != "" && len(m.Calls) != 0 {
		sb.WriteString(fmt.Sprintf("%s:\n", header))
	}

	for i, v := range m.Calls {
		a := []any{"cmd", v.Argument.cmd}
		mockgenMessageCallHistory(sb, i, m.expects[i].location, v.Location, a)
	}
}

func (m *managerToggleDone) invokeStub(cmd *todocli.DoneCmd) (*todocli.Task, error) {
	v0, v1 := m.stub(cmd)
	return m.capture(managerToggleDoneArgument{cmd: cmd}, managerToggleDoneReturn{first: v0, second: v1})
}

func (m *managerToggleDone) invokeExpect(cmd *todocli.DoneCmd) (*todocli.Task, error) {
	v0 := []any{"cmd", cmd}

	v1 := len(m.Calls)
	if v1 >= len(m.expects) {
		m.panic(mockgenMessageTooManyCalls(m, len(m.expects), v1+1, v0))
	}

	v2 := m.expects[v1]
	if v2.match != nil && !v2.match(cmd) {
		v2.tb.Helper()
		m.fatal(v1, mockgenMessageMatchFail(m, v2.matchLocation, v1, v0))
	}

	v2.tb.Helper()
	mockgenMatchArgument(m, v1, "cmd", cmd, v2.matcher.cmd, v2.matcherWants, v2.matcherMethods, v2.matcherHints, v2.tb, v2.matcherLocations["cmd"])

	return m.capture(managerToggleDoneArgument{cmd: cmd}, v2.returns)
}

func (m *managerToggleDone) capture(args managerToggleDoneArgument, returns managerToggleDoneReturn) (*todocli.Task, error) {
	m.Calls = append(m.Calls, managerToggleDoneCall{Location: mockgenCallerLocation(4), Argument: args, Return: returns})
	return returns.first, returns.second
}

func (m *managerToggleDone) verify(index int) {
	if !m.verified && index >= len(m.Calls) {
		m.expects[index].tb.Helper()
		m.expects[index].tb.Fatal(mockgenMessageExpectButNotCalled(m, len(m.expects), len(m.Calls), index))
	}
}

type managerToggleDoneCall struct {
	Location string
	Argument managerToggleDoneArgument
	Return   managerToggleDoneReturn
}

type managerToggleDoneArgument struct {
	cmd *todocli.DoneCmd
}

type managerToggleDoneArgumentMatcher struct {
	cmd func(cmd *todocli.DoneCmd) bool
}

type managerToggleDoneReturn struct {
	first  *todocli.Task
	second error
}

type managerToggleDoneExpect struct {
	match            func(cmd *todocli.DoneCmd) bool
	matchLocation    string
	matcher          *managerToggleDoneArgumentMatcher
	matcherWants     map[string]any
	matcherMethods   map[string]string
	matcherHints     map[string]string
	matcherLocations map[string]string
	returns          managerToggleDoneReturn
	location         string
	index            int
	tb               testing.TB
}

type managerToggleDoneExpecter struct {
	expect *managerToggleDoneExpect
	target *managerToggleDone
}

func (e *managerToggleDoneExpecter) Return(first *todocli.Task, second error) {
	e.expect.returns = managerToggleDoneReturn{first: first, second: second}
}

func (e *managerToggleDoneExpecter) Match(matcher func(cmd *todocli.DoneCmd) bool) *managerToggleDoneExpecterWithMatch {
	if matcher == nil {
		e.expect.tb.Helper()
		e.target.fatal(e.expect.index, mockgenMessageMatchByNil(e.target))
	}

	e.expect.match = matcher
	e.expect.matchLocation = mockgenCallerLocation(2)
	return &managerToggleDoneExpecterWithMatch{expect: e.expect}
}

func (e *managerToggleDoneExpecter) MatchCmd(matcher func(cmd *todocli.DoneCmd) bool) *managerToggleDoneExpecterWithMatchArg {
	if matcher == nil {
		e.expect.tb.Helper()
		e.target.fatal(e.expect.index, mockgenMessageMatchArgByNil(e.target, "MatchCmd"))
	}

	e.expect.matcher.cmd = matcher
	e.expect.matcherLocations["cmd"] = mockgenCallerLocation(2)
	e.expect.matcherHints["cmd"] = mockgenMessageMatchArgHint()
	return &managerToggleDoneExpecterWithMatchArg{expect: e.expect, target: e.target}
}

func (e *managerToggleDoneExpecter) With(cmd *todocli.DoneCmd) *managerToggleDoneExpecterWithValue {
	e.WithCmd(cmd)
	e.expect.matcherLocations["cmd"] = mockgenCallerLocation(2)

	return &managerToggleDoneExpecterWithValue{expect: e.expect}
}

func (e *managerToggleDoneExpecter) WithCmd(cmd *todocli.DoneCmd) *managerToggleDoneExpecterWithValueArg {
	e.expect.matcher.cmd = mockgenBasicComparisonMatcher(cmd)
	e.expect.matcherWants["cmd"] = cmd
	e.expect.matcherMethods["cmd"] = "=="
	e.expect.matcherLocations["cmd"] = mockgenCallerLocation(2)

	return &managerToggleDoneExpecterWithValueArg{expect: e.expect, target: e.target}
}

type managerToggleDoneExpecterWithMatch struct {
	expect *managerToggleDoneExpect
}

func (e *managerToggleDoneExpecterWithMatch) Return(first *todocli.Task, second error) {
	e.expect.returns = managerToggleDoneReturn{first: first, second: second}
}

type managerToggleDoneExpecterWithMatchArg struct {
	expect *managerToggleDoneExpect
	target *managerToggleDone
}

func (e *managerToggleDoneExpecterWithMatchArg) Return(first *todocli.Task, second error) {
	e.expect.returns = managerToggleDoneReturn{first: first, second: second}
}

func (e *managerToggleDoneExpecterWithMatchArg) MatchCmd(matcher func(cmd *todocli.DoneCmd) bool) *managerToggleDoneExpecterWithMatchArg {
	if matcher == nil {
		e.expect.tb.Helper()
		e.target.fatal(e.expect.index, mockgenMessageMatchArgByNil(e.target, "MatchCmd"))
	}

	if e.expect.matcher.cmd != nil {
		e.expect.tb.Helper()
		e.target.fatal(e.expect.index, mockgenMessageDuplicateMatchArg(e.target, "MatchCmd", e.expect.matcherLocations["cmd"]))
	}

	e.expect.matcher.cmd = matcher
	e.expect.matcherLocations["cmd"] = mockgenCallerLocation(2)
	e.expect.matcherHints["cmd"] = mockgenMessageMatchArgHint()
	return e
}

type managerToggleDoneExpecterWithValue struct {
	expect *managerToggleDoneExpect
}

func (e *managerToggleDoneExpecterWithValue) Return(first *todocli.Task, second error) {
	e.expect.returns = managerToggleDoneReturn{first: first, second: second}
}

type managerToggleDoneExpecterWithValueArg struct {
	expect *managerToggleDoneExpect
	target *managerToggleDone
}

func (e *managerToggleDoneExpecterWithValueArg) Return(first *todocli.Task, second error) {
	e.expect.returns = managerToggleDoneReturn{first: first, second: second}
}

func (e *managerToggleDoneExpecterWithValueArg) WithCmd(cmd *todocli.DoneCmd) *managerToggleDoneExpecterWithValueArg {
	if e.expect.matcher.cmd != nil {
		e.expect.tb.Helper()
		e.target.fatal(e.expect.index, mockgenMessageDuplicateMatchArg(e.target, "WithCmd", e.expect.matcherLocations["cmd"]))
	}

	e.expect.matcher.cmd = mockgenBasicComparisonMatcher(cmd)
	e.expect.matcherWants["cmd"] = cmd
	e.expect.matcherMethods["cmd"] = "=="
	e.expect.matcherLocations["cmd"] = mockgenCallerLocation(2)

	return e
}

type managerUpdateTasks struct {
	Calls        []managerUpdateTasksCall
	stub         func(cmd *todocli.UpdateCmd) (*todocli.Task, error)
	stubLocation string
	expects      []*managerUpdateTasksExpect
	verified     bool
}

func (m *managerUpdateTasks) methodName() string {
	return "UpdateTasks"
}

func (m *managerUpdateTasks) interfaceName() string {
	return "Manager"
}

func (m *managerUpdateTasks) fatal(index int, msg string) {
	m.verified = true
	m.expects[index].tb.Helper()
	m.expects[index].tb.Fatal(msg)
}

func (m *managerUpdateTasks) panic(msg string) {
	m.verified = true
	panic(msg)
}

func (m *managerUpdateTasks) buildCallHistory(sb *strings.Builder, header string) {
	if header != "" && len(m.Calls) != 0 {
		sb.WriteString(fmt.Sprintf("%s:\n", header))
	}

	for i, v := range m.Calls {
		a := []any{"cmd", v.Argument.cmd}
		mockgenMessageCallHistory(sb, i, m.expects[i].location, v.Location, a)
	}
}

func (m *managerUpdateTasks) invokeStub(cmd *todocli.UpdateCmd) (*todocli.Task, error) {
	v0, v1 := m.stub(cmd)
	return m.capture(managerUpdateTasksArgument{cmd: cmd}, managerUpdateTasksReturn{first: v0, second: v1})
}

func (m *managerUpdateTasks) invokeExpect(cmd *todocli.UpdateCmd) (*todocli.Task, error) {
	v0 := []any{"cmd", cmd}

	v1 := len(m.Calls)
	if v1 >= len(m.expects) {
		m.panic(mockgenMessageTooManyCalls(m, len(m.expects), v1+1, v0))
	}

	v2 := m.expects[v1]
	if v2.match != nil && !v2.match(cmd) {
		v2.tb.Helper()
		m.fatal(v1, mockgenMessageMatchFail(m, v2.matchLocation, v1, v0))
	}

	v2.tb.Helper()
	mockgenMatchArgument(m, v1, "cmd", cmd, v2.matcher.cmd, v2.matcherWants, v2.matcherMethods, v2.matcherHints, v2.tb, v2.matcherLocations["cmd"])

	return m.capture(managerUpdateTasksArgument{cmd: cmd}, v2.returns)
}

func (m *managerUpdateTasks) capture(args managerUpdateTasksArgument, returns managerUpdateTasksReturn) (*todocli.Task, error) {
	m.Calls = append(m.Calls, managerUpdateTasksCall{Location: mockgenCallerLocation(4), Argument: args, Return: returns})
	return returns.first, returns.second
}

func (m *managerUpdateTasks) verify(index int) {
	if !m.verified && index >= len(m.Calls) {
		m.expects[index].tb.Helper()
		m.expects[index].tb.Fatal(mockgenMessageExpectButNotCalled(m, len(m.expects), len(m.Calls), index))
	}
}

type managerUpdateTasksCall struct {
	Location string
	Argument managerUpdateTasksArgument
	Return   managerUpdateTasksReturn
}

type managerUpdateTasksArgument struct {
	cmd *todocli.UpdateCmd
}

type managerUpdateTasksArgumentMatcher struct {
	cmd func(cmd *todocli.UpdateCmd) bool
}

type managerUpdateTasksReturn struct {
	first  *todocli.Task
	second error
}

type managerUpdateTasksExpect struct {
	match            func(cmd *todocli.UpdateCmd) bool
	matchLocation    string
	matcher          *managerUpdateTasksArgumentMatcher
	matcherWants     map[string]any
	matcherMethods   map[string]string
	matcherHints     map[string]string
	matcherLocations map[string]string
	returns          managerUpdateTasksReturn
	location         string
	index            int
	tb               testing.TB
}

type managerUpdateTasksExpecter struct {
	expect *managerUpdateTasksExpect
	target *managerUpdateTasks
}

func (e *managerUpdateTasksExpecter) Return(first *todocli.Task, second error) {
	e.expect.returns = managerUpdateTasksReturn{first: first, second: second}
}

func (e *managerUpdateTasksExpecter) Match(matcher func(cmd *todocli.UpdateCmd) bool) *managerUpdateTasksExpecterWithMatch {
	if matcher == nil {
		e.expect.tb.Helper()
		e.target.fatal(e.expect.index, mockgenMessageMatchByNil(e.target))
	}

	e.expect.match = matcher
	e.expect.matchLocation = mockgenCallerLocation(2)
	return &managerUpdateTasksExpecterWithMatch{expect: e.expect}
}

func (e *managerUpdateTasksExpecter) MatchCmd(matcher func(cmd *todocli.UpdateCmd) bool) *managerUpdateTasksExpecterWithMatchArg {
	if matcher == nil {
		e.expect.tb.Helper()
		e.target.fatal(e.expect.index, mockgenMessageMatchArgByNil(e.target, "MatchCmd"))
	}

	e.expect.matcher.cmd = matcher
	e.expect.matcherLocations["cmd"] = mockgenCallerLocation(2)
	e.expect.matcherHints["cmd"] = mockgenMessageMatchArgHint()
	return &managerUpdateTasksExpecterWithMatchArg{expect: e.expect, target: e.target}
}

func (e *managerUpdateTasksExpecter) With(cmd *todocli.UpdateCmd) *managerUpdateTasksExpecterWithValue {
	e.WithCmd(cmd)
	e.expect.matcherLocations["cmd"] = mockgenCallerLocation(2)

	return &managerUpdateTasksExpecterWithValue{expect: e.expect}
}

func (e *managerUpdateTasksExpecter) WithCmd(cmd *todocli.UpdateCmd) *managerUpdateTasksExpecterWithValueArg {
	e.expect.matcher.cmd = mockgenBasicComparisonMatcher(cmd)
	e.expect.matcherWants["cmd"] = cmd
	e.expect.matcherMethods["cmd"] = "=="
	e.expect.matcherLocations["cmd"] = mockgenCallerLocation(2)

	return &managerUpdateTasksExpecterWithValueArg{expect: e.expect, target: e.target}
}

type managerUpdateTasksExpecterWithMatch struct {
	expect *managerUpdateTasksExpect
}

func (e *managerUpdateTasksExpecterWithMatch) Return(first *todocli.Task, second error) {
	e.expect.returns = managerUpdateTasksReturn{first: first, second: second}
}

type managerUpdateTasksExpecterWithMatchArg struct {
	expect *managerUpdateTasksExpect
	target *managerUpdateTasks
}

func (e *managerUpdateTasksExpecterWithMatchArg) Return(first *todocli.Task, second error) {
	e.expect.returns = managerUpdateTasksReturn{first: first, second: second}
}

func (e *managerUpdateTasksExpecterWithMatchArg) MatchCmd(matcher func(cmd *todocli.UpdateCmd) bool) *managerUpdateTasksExpecterWithMatchArg {
	if matcher == nil {
		e.expect.tb.Helper()
		e.target.fatal(e.expect.index, mockgenMessageMatchArgByNil(e.target, "MatchCmd"))
	}

	if e.expect.matcher.cmd != nil {
		e.expect.tb.Helper()
		e.target.fatal(e.expect.index, mockgenMessageDuplicateMatchArg(e.target, "MatchCmd", e.expect.matcherLocations["cmd"]))
	}

	e.expect.matcher.cmd = matcher
	e.expect.matcherLocations["cmd"] = mockgenCallerLocation(2)
	e.expect.matcherHints["cmd"] = mockgenMessageMatchArgHint()
	return e
}

type managerUpdateTasksExpecterWithValue struct {
	expect *managerUpdateTasksExpect
}

func (e *managerUpdateTasksExpecterWithValue) Return(first *todocli.Task, second error) {
	e.expect.returns = managerUpdateTasksReturn{first: first, second: second}
}

type managerUpdateTasksExpecterWithValueArg struct {
	expect *managerUpdateTasksExpect
	target *managerUpdateTasks
}

func (e *managerUpdateTasksExpecterWithValueArg) Return(first *todocli.Task, second error) {
	e.expect.returns = managerUpdateTasksReturn{first: first, second: second}
}

func (e *managerUpdateTasksExpecterWithValueArg) WithCmd(cmd *todocli.UpdateCmd) *managerUpdateTasksExpecterWithValueArg {
	if e.expect.matcher.cmd != nil {
		e.expect.tb.Helper()
		e.target.fatal(e.expect.index, mockgenMessageDuplicateMatchArg(e.target, "WithCmd", e.expect.matcherLocations["cmd"]))
	}

	e.expect.matcher.cmd = mockgenBasicComparisonMatcher(cmd)
	e.expect.matcherWants["cmd"] = cmd
	e.expect.matcherMethods["cmd"] = "=="
	e.expect.matcherLocations["cmd"] = mockgenCallerLocation(2)

	return e
}
