// Code generated by nhatp.com/go/mock-gen/cmd/go-mock-gen - v1.0.0. DO NOT EDIT.

package handler

import (
	"fmt"
	todocli "github.com/trungnc90/learn-golang/assignments/01_todo_cli"
	"path/filepath"
	"reflect"
	"runtime"
	"strconv"
	"strings"
	"testing"
)

func mockgenCallerLocation(skip int) string {
	_, file, line, _ := runtime.Caller(skip)
	return fmt.Sprintf("%s:%d", filepath.Base(file), line)
}

type mockgenMockMethod interface {
	methodName() string
	interfaceName() string
	buildCallHistory(sb *strings.Builder, header string)
	fatal(index int, msg string)
	panic(msg string)
}

func mockgenMessageWriteArguments(sb *strings.Builder, template string, args []any) {
	maxLen := 0
	for i := 0; i < len(args); i += 2 {
		str, ok := args[i].(string)
		if !ok {
			str = fmt.Sprintf("%v", args[i])
		}
		maxLen = max(maxLen, len(str))
	}

	format := strings.ReplaceAll(template, "[MAX-KEY-LEN]", strconv.Itoa(maxLen))
	for i := 0; i < len(args); i += 2 {
		key, ok := args[i].(string)
		if !ok {
			key = fmt.Sprintf("%v", args[i])
		}

		var val any
		if i+1 < len(args) {
			val = args[i+1]
		}
		sb.WriteString(fmt.Sprintf(format, key, val))
	}
}

func mockgenMessageMatchFail(m mockgenMockMethod, matchedAt string, index int, args []any) string {
	sb := &strings.Builder{}
	sb.WriteString(fmt.Sprintf("%s.%s call #%d did not match\n", m.interfaceName(), m.methodName(), index+1))
	sb.WriteString(fmt.Sprintf("arguments:\n"))
	mockgenMessageWriteArguments(sb, "\t%[MAX-KEY-LEN]s = %#v\n", args)
	sb.WriteString("\n")
	m.buildCallHistory(sb, "call history")
	sb.WriteString(fmt.Sprintf("hint: check the callback passed to Match at %s", matchedAt))
	return sb.String()
}

func mockgenMessageNotImplemented(interfaceName string, methodName string, signature string, createdLocation string, args []any) string {
	sb := &strings.Builder{}
	sb.WriteString(fmt.Sprintf("unexpected call to %s.%s\n", interfaceName, methodName))
	sb.WriteString(fmt.Sprintf("signature: %s.%s%s\n", interfaceName, methodName, signature))
	sb.WriteString(fmt.Sprintf("called at: %s\n", mockgenCallerLocation(3)))
	sb.WriteString("arguments:\n")
	mockgenMessageWriteArguments(sb, "\t%[MAX-KEY-LEN]s = %#v\n", args)

	location := ""
	if createdLocation != "" {
		location = " after " + createdLocation
	}
	sb.WriteString(fmt.Sprintf("\nhint:%s use one of:\n\t[var].EXPECT().%s(t)\n\t[var].STUB().%s(func(...) ...)\n\n", location, methodName, methodName))
	return sb.String()
}

func mockgenMessageCallHistory(sb *strings.Builder, index int, expectedAt string, calledAt string, args []any) string {
	sb.WriteString(fmt.Sprintf("\t#%d expect at: %s\n", index+1, expectedAt))
	sb.WriteString(fmt.Sprintf("\t   called at: %s\n", calledAt))
	sb.WriteString(fmt.Sprintf("\t   arguments:\n"))
	mockgenMessageWriteArguments(sb, "\t\t%[MAX-KEY-LEN]s = %#v\n", args)
	sb.WriteString("\n")
	return sb.String()
}

func mockgenMessageTooManyCalls(m mockgenMockMethod, want int, got int, args []any) string {
	sb := &strings.Builder{}
	sb.WriteString(fmt.Sprintf("too many calls to %s.%s\n", m.interfaceName(), m.methodName()))
	sb.WriteString(fmt.Sprintf("\twant: %d, got: %d\n\n", want, got))
	m.buildCallHistory(sb, "")
	sb.WriteString(fmt.Sprintf("\t#%d expect at: %s\n", got, "missing"))
	sb.WriteString(fmt.Sprintf("\t   called at: %s\n", mockgenCallerLocation(4)))
	sb.WriteString(fmt.Sprintf("\t   arguments:\n"))
	mockgenMessageWriteArguments(sb, "\t\t%[MAX-KEY-LEN]s = %#v\n", args)
	sb.WriteString("\n")
	sb.WriteString(fmt.Sprintf("\thint: remove unexpected call or add 1 more EXPECT:\n\t\t[var].EXPECT().%s(t)\n", m.methodName()))
	return sb.String()
}

func mockgenMessageMatchByNil(m mockgenMockMethod) string {
	sb := &strings.Builder{}
	sb.WriteString(fmt.Sprintf("%s.%s Match received a nil function\n", m.interfaceName(), m.methodName()))
	sb.WriteString("\thint: provide a valid function")
	return sb.String()
}

func mockgenMessageExpectByNil(m mockgenMockMethod) string {
	sb := &strings.Builder{}
	sb.WriteString(fmt.Sprintf("unexpected nil testing.TB in %s.%s\n", m.interfaceName(), m.methodName()))
	sb.WriteString(fmt.Sprintf("\tcalled at: %s\n\n", mockgenCallerLocation(3)))
	sb.WriteString("\thint: EXPECT requires a valid testing.TB, use STUB instead:\n")
	sb.WriteString(fmt.Sprintf("\t\tspy := [var].STUB().%s(func(...) ...)\n", m.methodName()))
	return sb.String()
}

func mockgenMessageExpectAfterStub(m mockgenMockMethod, stubAt string) string {
	sb := &strings.Builder{}
	sb.WriteString(fmt.Sprintf("conflicting usage for %s.%s\n", m.interfaceName(), m.methodName()))
	sb.WriteString(fmt.Sprintf("\t%14s: %s\n", "STUB used at", stubAt))
	sb.WriteString(fmt.Sprintf("\t%14s: %s\n\n", "EXPECT used at", mockgenCallerLocation(3)))
	sb.WriteString("\thint: use either EXPECT or STUB for the same method, not both\n\n")
	return sb.String()
}

func mockgenMessageStubByNil(m mockgenMockMethod, calledAt string) string {
	sb := &strings.Builder{}
	sb.WriteString(fmt.Sprintf("%s.%s STUB received a nil function\n", m.interfaceName(), m.methodName()))
	sb.WriteString(fmt.Sprintf("called at: %s\n\n", calledAt))
	sb.WriteString("hint: provide a valid function\n")
	return sb.String()
}

func mockgenMessageStubAfterExpect(m mockgenMockMethod, expectAt string) string {
	sb := &strings.Builder{}
	sb.WriteString(fmt.Sprintf("conflicting usage for %s.%s\n", m.interfaceName(), m.methodName()))
	sb.WriteString(fmt.Sprintf("\t%14s: %s\n", "EXPECT used at", expectAt))
	sb.WriteString(fmt.Sprintf("\t%14s: %s\n\n", "STUB used at", mockgenCallerLocation(3)))
	sb.WriteString("\thint: use either EXPECT or STUB for the same method, not both\n\n")
	return sb.String()
}

func mockgenMessageDuplicateStub(m mockgenMockMethod, firstUsedAt string) string {
	sb := &strings.Builder{}
	sb.WriteString(fmt.Sprintf("duplicate STUB for %s.%s\n", m.interfaceName(), m.methodName()))
	sb.WriteString(fmt.Sprintf("\t%14s: %s\n", "first used at", firstUsedAt))
	sb.WriteString(fmt.Sprintf("\t%14s: %s\n\n", "second used at", mockgenCallerLocation(3)))
	sb.WriteString(fmt.Sprintf("\thint: %s.%s is already stubbed, remove one of the above\n\n", m.interfaceName(), m.methodName()))
	return sb.String()
}

func mockgenMessageExpectButNotCalled(m mockgenMockMethod, want int, got int, index int) string {
	sb := &strings.Builder{}
	sb.WriteString(fmt.Sprintf("%s.%s was not called as expected\n", m.interfaceName(), m.methodName()))
	sb.WriteString(fmt.Sprintf("\twant: %d, got: %d\n\n", want, got))
	m.buildCallHistory(sb, "")
	sb.WriteString(fmt.Sprintf("\t#%d never called\n\n", index+1))
	sb.WriteString("\thint: add the missing call or remove the EXPECT above")
	return sb.String()
}

func mockgenMessageMatchArgByNil(m mockgenMockMethod, method string) string {
	sb := &strings.Builder{}
	sb.WriteString(fmt.Sprintf("%s.%s %s received a nil function\n", m.interfaceName(), m.methodName(), method))
	sb.WriteString("\thint: provide a valid function")
	return sb.String()
}

func mockgenMessageDuplicateMatchArg(m mockgenMockMethod, method string, firstUsedAt string) string {
	sb := &strings.Builder{}
	sb.WriteString(fmt.Sprintf("duplicate %s for %s.%s\n", method, m.interfaceName(), m.methodName()))
	sb.WriteString(fmt.Sprintf("\t%14s: %s\n\n", "first used at", firstUsedAt))
	sb.WriteString("\thint: each argument can only be matched once, remove one of the above")
	return sb.String()
}

func mockgenMessageMatchArgHint() string {
	return fmt.Sprintf("\thint: check argument matching at %s\n\t\tor use STUB for fine-grained control", mockgenCallerLocation(3))
}

func mockgenMatchArgument[T any](m mockgenMockMethod, index int, name string, got T, match func(T) bool, wants map[string]any, methods map[string]string, hints map[string]string, tb testing.TB, expectAt string) {
	if match == nil || match(got) {
		return
	}
	tb.Helper()

	method := "func(got) bool"
	if v, ok := methods[name]; ok {
		method = v
	}

	hint := fmt.Sprintf("hint: for custom matching use .Match[arg](func(...) bool) at %s\n\tor use STUB for fine-grained control", expectAt)
	if v, ok := hints[name]; ok {
		hint = v
	}

	sb := &strings.Builder{}
	sb.WriteString(fmt.Sprintf("%s.%s call #%d argument \"%s\" did not match\n", m.interfaceName(), m.methodName(), index+1, name))
	if want, ok := wants[name]; ok {
		sb.WriteString(fmt.Sprintf("  want: %#v\n", want))
	}
	sb.WriteString(fmt.Sprintf("   got: %#v\n", got))
	sb.WriteString(fmt.Sprintf("method: %s\n", method))
	sb.WriteString("\n")
	m.buildCallHistory(sb, "call history")
	sb.WriteString(hint)

	tb.Helper()
	m.fatal(index, sb.String())
}

func mockgenReflectEqualMatcher[T any](want T) func(T) bool {
	return func(got T) bool {
		return reflect.DeepEqual(want, got)
	}
}

func mockgenBasicComparisonMatcher[T comparable](want T) func(T) bool {
	return func(got T) bool {
		return want == got
	}
}

func testTaskManager() *taskManager {
	return &taskManager{td: &taskManagerTestDouble{location: mockgenCallerLocation(2)}}
}

type taskManagerTestDouble struct {
	location    string
	AddTask     *taskManagerAddTask
	DeleteTask  *taskManagerDeleteTask
	ListTasks   *taskManagerListTasks
	ToggleDone  *taskManagerToggleDone
	UpdateTasks *taskManagerUpdateTasks
}

type taskManager struct {
	td *taskManagerTestDouble
}

func (m *taskManager) STUB() *taskManagerStubber {
	return &taskManagerStubber{target: m}
}

func (m *taskManager) EXPECT() *taskManagerExpecter {
	return &taskManagerExpecter{target: m}
}

func (m *taskManager) AddTask(cmd *todocli.AddCmd) (*todocli.Task, error) {
	v0, v1, v2 := "TaskManager", "AddTask", "(cmd AddCmd) (Task, error)"
	v3 := []any{"cmd", cmd}

	if m.td == nil {
		panic(mockgenMessageNotImplemented(v0, v1, v2, "", v3))
	}

	if v4 := m.td.AddTask; v4 != nil {
		switch {
		case v4.stub != nil:
			return v4.invokeStub(cmd)
		case len(v4.expects) > 0:
			v5 := len(v4.Calls)
			if v5 < len(v4.expects) {
				v4.expects[v5].tb.Helper()
			}
			return v4.invokeExpect(cmd)
		}
	}
	panic(mockgenMessageNotImplemented(v0, v1, v2, m.td.location, v3))
}

func (m *taskManager) DeleteTask(cmd *todocli.DeleteCmd) error {
	v0, v1, v2 := "TaskManager", "DeleteTask", "(cmd DeleteCmd) error"
	v3 := []any{"cmd", cmd}

	if m.td == nil {
		panic(mockgenMessageNotImplemented(v0, v1, v2, "", v3))
	}

	if v4 := m.td.DeleteTask; v4 != nil {
		switch {
		case v4.stub != nil:
			return v4.invokeStub(cmd)
		case len(v4.expects) > 0:
			v5 := len(v4.Calls)
			if v5 < len(v4.expects) {
				v4.expects[v5].tb.Helper()
			}
			return v4.invokeExpect(cmd)
		}
	}
	panic(mockgenMessageNotImplemented(v0, v1, v2, m.td.location, v3))
}

func (m *taskManager) ListTasks(cmd *todocli.ListCmd) ([]todocli.Task, error) {
	v0, v1, v2 := "TaskManager", "ListTasks", "(cmd ListCmd) ([]Task, error)"
	v3 := []any{"cmd", cmd}

	if m.td == nil {
		panic(mockgenMessageNotImplemented(v0, v1, v2, "", v3))
	}

	if v4 := m.td.ListTasks; v4 != nil {
		switch {
		case v4.stub != nil:
			return v4.invokeStub(cmd)
		case len(v4.expects) > 0:
			v5 := len(v4.Calls)
			if v5 < len(v4.expects) {
				v4.expects[v5].tb.Helper()
			}
			return v4.invokeExpect(cmd)
		}
	}
	panic(mockgenMessageNotImplemented(v0, v1, v2, m.td.location, v3))
}

func (m *taskManager) ToggleDone(cmd *todocli.DoneCmd) (*todocli.Task, error) {
	v0, v1, v2 := "TaskManager", "ToggleDone", "(cmd DoneCmd) (Task, error)"
	v3 := []any{"cmd", cmd}

	if m.td == nil {
		panic(mockgenMessageNotImplemented(v0, v1, v2, "", v3))
	}

	if v4 := m.td.ToggleDone; v4 != nil {
		switch {
		case v4.stub != nil:
			return v4.invokeStub(cmd)
		case len(v4.expects) > 0:
			v5 := len(v4.Calls)
			if v5 < len(v4.expects) {
				v4.expects[v5].tb.Helper()
			}
			return v4.invokeExpect(cmd)
		}
	}
	panic(mockgenMessageNotImplemented(v0, v1, v2, m.td.location, v3))
}

func (m *taskManager) UpdateTasks(cmd *todocli.UpdateCmd) (*todocli.Task, error) {
	v0, v1, v2 := "TaskManager", "UpdateTasks", "(cmd UpdateCmd) (Task, error)"
	v3 := []any{"cmd", cmd}

	if m.td == nil {
		panic(mockgenMessageNotImplemented(v0, v1, v2, "", v3))
	}

	if v4 := m.td.UpdateTasks; v4 != nil {
		switch {
		case v4.stub != nil:
			return v4.invokeStub(cmd)
		case len(v4.expects) > 0:
			v5 := len(v4.Calls)
			if v5 < len(v4.expects) {
				v4.expects[v5].tb.Helper()
			}
			return v4.invokeExpect(cmd)
		}
	}
	panic(mockgenMessageNotImplemented(v0, v1, v2, m.td.location, v3))
}

type taskManagerStubber struct {
	target *taskManager
}

func (s *taskManagerStubber) AddTask(stub func(cmd *todocli.AddCmd) (*todocli.Task, error)) *taskManagerAddTask {
	if s.target.td == nil {
		s.target.td = &taskManagerTestDouble{}
	}

	m := s.target.td.AddTask
	if m == nil {
		m = &taskManagerAddTask{stubLocation: mockgenCallerLocation(2)}
		s.target.td.AddTask = m
	}

	if stub == nil {
		m.panic(mockgenMessageStubByNil(m, mockgenCallerLocation(2)))
	}

	if m.stub != nil {
		m.panic(mockgenMessageDuplicateStub(m, m.stubLocation))
	}

	if len(m.expects) > 0 {
		m.panic(mockgenMessageStubAfterExpect(m, m.expects[0].location))
	}

	m.stub = stub
	return m
}

func (s *taskManagerStubber) DeleteTask(stub func(cmd *todocli.DeleteCmd) error) *taskManagerDeleteTask {
	if s.target.td == nil {
		s.target.td = &taskManagerTestDouble{}
	}

	m := s.target.td.DeleteTask
	if m == nil {
		m = &taskManagerDeleteTask{stubLocation: mockgenCallerLocation(2)}
		s.target.td.DeleteTask = m
	}

	if stub == nil {
		m.panic(mockgenMessageStubByNil(m, mockgenCallerLocation(2)))
	}

	if m.stub != nil {
		m.panic(mockgenMessageDuplicateStub(m, m.stubLocation))
	}

	if len(m.expects) > 0 {
		m.panic(mockgenMessageStubAfterExpect(m, m.expects[0].location))
	}

	m.stub = stub
	return m
}

func (s *taskManagerStubber) ListTasks(stub func(cmd *todocli.ListCmd) ([]todocli.Task, error)) *taskManagerListTasks {
	if s.target.td == nil {
		s.target.td = &taskManagerTestDouble{}
	}

	m := s.target.td.ListTasks
	if m == nil {
		m = &taskManagerListTasks{stubLocation: mockgenCallerLocation(2)}
		s.target.td.ListTasks = m
	}

	if stub == nil {
		m.panic(mockgenMessageStubByNil(m, mockgenCallerLocation(2)))
	}

	if m.stub != nil {
		m.panic(mockgenMessageDuplicateStub(m, m.stubLocation))
	}

	if len(m.expects) > 0 {
		m.panic(mockgenMessageStubAfterExpect(m, m.expects[0].location))
	}

	m.stub = stub
	return m
}

func (s *taskManagerStubber) ToggleDone(stub func(cmd *todocli.DoneCmd) (*todocli.Task, error)) *taskManagerToggleDone {
	if s.target.td == nil {
		s.target.td = &taskManagerTestDouble{}
	}

	m := s.target.td.ToggleDone
	if m == nil {
		m = &taskManagerToggleDone{stubLocation: mockgenCallerLocation(2)}
		s.target.td.ToggleDone = m
	}

	if stub == nil {
		m.panic(mockgenMessageStubByNil(m, mockgenCallerLocation(2)))
	}

	if m.stub != nil {
		m.panic(mockgenMessageDuplicateStub(m, m.stubLocation))
	}

	if len(m.expects) > 0 {
		m.panic(mockgenMessageStubAfterExpect(m, m.expects[0].location))
	}

	m.stub = stub
	return m
}

func (s *taskManagerStubber) UpdateTasks(stub func(cmd *todocli.UpdateCmd) (*todocli.Task, error)) *taskManagerUpdateTasks {
	if s.target.td == nil {
		s.target.td = &taskManagerTestDouble{}
	}

	m := s.target.td.UpdateTasks
	if m == nil {
		m = &taskManagerUpdateTasks{stubLocation: mockgenCallerLocation(2)}
		s.target.td.UpdateTasks = m
	}

	if stub == nil {
		m.panic(mockgenMessageStubByNil(m, mockgenCallerLocation(2)))
	}

	if m.stub != nil {
		m.panic(mockgenMessageDuplicateStub(m, m.stubLocation))
	}

	if len(m.expects) > 0 {
		m.panic(mockgenMessageStubAfterExpect(m, m.expects[0].location))
	}

	m.stub = stub
	return m
}

type taskManagerExpecter struct {
	target *taskManager
}

func (e *taskManagerExpecter) AddTask(tb testing.TB) *taskManagerAddTaskExpecter {
	if e.target.td == nil {
		e.target.td = &taskManagerTestDouble{}
	}

	var m = e.target.td.AddTask
	if m == nil {
		m = &taskManagerAddTask{}
		e.target.td.AddTask = m
	}

	if m.stub != nil {
		m.panic(mockgenMessageExpectAfterStub(m, m.stubLocation))
	}

	if tb == nil {
		m.panic(mockgenMessageExpectByNil(m))
	}

	idx := len(m.expects)
	m.expects = append(m.expects, &taskManagerAddTaskExpect{
		location:         mockgenCallerLocation(2),
		matcher:          &taskManagerAddTaskArgumentMatcher{},
		matcherWants:     make(map[string]any),
		matcherMethods:   make(map[string]string),
		matcherHints:     make(map[string]string),
		matcherLocations: make(map[string]string),
		index:            idx,
		tb:               tb,
	})

	tb.Helper()
	tb.Cleanup(func() {
		tb.Helper()
		m.verify(idx)
	})

	return &taskManagerAddTaskExpecter{target: m, expect: m.expects[idx]}
}

func (e *taskManagerExpecter) DeleteTask(tb testing.TB) *taskManagerDeleteTaskExpecter {
	if e.target.td == nil {
		e.target.td = &taskManagerTestDouble{}
	}

	var m = e.target.td.DeleteTask
	if m == nil {
		m = &taskManagerDeleteTask{}
		e.target.td.DeleteTask = m
	}

	if m.stub != nil {
		m.panic(mockgenMessageExpectAfterStub(m, m.stubLocation))
	}

	if tb == nil {
		m.panic(mockgenMessageExpectByNil(m))
	}

	idx := len(m.expects)
	m.expects = append(m.expects, &taskManagerDeleteTaskExpect{
		location:         mockgenCallerLocation(2),
		matcher:          &taskManagerDeleteTaskArgumentMatcher{},
		matcherWants:     make(map[string]any),
		matcherMethods:   make(map[string]string),
		matcherHints:     make(map[string]string),
		matcherLocations: make(map[string]string),
		index:            idx,
		tb:               tb,
	})

	tb.Helper()
	tb.Cleanup(func() {
		tb.Helper()
		m.verify(idx)
	})

	return &taskManagerDeleteTaskExpecter{target: m, expect: m.expects[idx]}
}

func (e *taskManagerExpecter) ListTasks(tb testing.TB) *taskManagerListTasksExpecter {
	if e.target.td == nil {
		e.target.td = &taskManagerTestDouble{}
	}

	var m = e.target.td.ListTasks
	if m == nil {
		m = &taskManagerListTasks{}
		e.target.td.ListTasks = m
	}

	if m.stub != nil {
		m.panic(mockgenMessageExpectAfterStub(m, m.stubLocation))
	}

	if tb == nil {
		m.panic(mockgenMessageExpectByNil(m))
	}

	idx := len(m.expects)
	m.expects = append(m.expects, &taskManagerListTasksExpect{
		location:         mockgenCallerLocation(2),
		matcher:          &taskManagerListTasksArgumentMatcher{},
		matcherWants:     make(map[string]any),
		matcherMethods:   make(map[string]string),
		matcherHints:     make(map[string]string),
		matcherLocations: make(map[string]string),
		index:            idx,
		tb:               tb,
	})

	tb.Helper()
	tb.Cleanup(func() {
		tb.Helper()
		m.verify(idx)
	})

	return &taskManagerListTasksExpecter{target: m, expect: m.expects[idx]}
}

func (e *taskManagerExpecter) ToggleDone(tb testing.TB) *taskManagerToggleDoneExpecter {
	if e.target.td == nil {
		e.target.td = &taskManagerTestDouble{}
	}

	var m = e.target.td.ToggleDone
	if m == nil {
		m = &taskManagerToggleDone{}
		e.target.td.ToggleDone = m
	}

	if m.stub != nil {
		m.panic(mockgenMessageExpectAfterStub(m, m.stubLocation))
	}

	if tb == nil {
		m.panic(mockgenMessageExpectByNil(m))
	}

	idx := len(m.expects)
	m.expects = append(m.expects, &taskManagerToggleDoneExpect{
		location:         mockgenCallerLocation(2),
		matcher:          &taskManagerToggleDoneArgumentMatcher{},
		matcherWants:     make(map[string]any),
		matcherMethods:   make(map[string]string),
		matcherHints:     make(map[string]string),
		matcherLocations: make(map[string]string),
		index:            idx,
		tb:               tb,
	})

	tb.Helper()
	tb.Cleanup(func() {
		tb.Helper()
		m.verify(idx)
	})

	return &taskManagerToggleDoneExpecter{target: m, expect: m.expects[idx]}
}

func (e *taskManagerExpecter) UpdateTasks(tb testing.TB) *taskManagerUpdateTasksExpecter {
	if e.target.td == nil {
		e.target.td = &taskManagerTestDouble{}
	}

	var m = e.target.td.UpdateTasks
	if m == nil {
		m = &taskManagerUpdateTasks{}
		e.target.td.UpdateTasks = m
	}

	if m.stub != nil {
		m.panic(mockgenMessageExpectAfterStub(m, m.stubLocation))
	}

	if tb == nil {
		m.panic(mockgenMessageExpectByNil(m))
	}

	idx := len(m.expects)
	m.expects = append(m.expects, &taskManagerUpdateTasksExpect{
		location:         mockgenCallerLocation(2),
		matcher:          &taskManagerUpdateTasksArgumentMatcher{},
		matcherWants:     make(map[string]any),
		matcherMethods:   make(map[string]string),
		matcherHints:     make(map[string]string),
		matcherLocations: make(map[string]string),
		index:            idx,
		tb:               tb,
	})

	tb.Helper()
	tb.Cleanup(func() {
		tb.Helper()
		m.verify(idx)
	})

	return &taskManagerUpdateTasksExpecter{target: m, expect: m.expects[idx]}
}

type taskManagerAddTask struct {
	Calls        []taskManagerAddTaskCall
	stub         func(cmd *todocli.AddCmd) (*todocli.Task, error)
	stubLocation string
	expects      []*taskManagerAddTaskExpect
	verified     bool
}

func (m *taskManagerAddTask) methodName() string {
	return "AddTask"
}

func (m *taskManagerAddTask) interfaceName() string {
	return "TaskManager"
}

func (m *taskManagerAddTask) fatal(index int, msg string) {
	m.verified = true
	m.expects[index].tb.Helper()
	m.expects[index].tb.Fatal(msg)
}

func (m *taskManagerAddTask) panic(msg string) {
	m.verified = true
	panic(msg)
}

func (m *taskManagerAddTask) buildCallHistory(sb *strings.Builder, header string) {
	if header != "" && len(m.Calls) != 0 {
		sb.WriteString(fmt.Sprintf("%s:\n", header))
	}

	for i, v := range m.Calls {
		a := []any{"cmd", v.Argument.cmd}
		mockgenMessageCallHistory(sb, i, m.expects[i].location, v.Location, a)
	}
}

func (m *taskManagerAddTask) invokeStub(cmd *todocli.AddCmd) (*todocli.Task, error) {
	v0, v1 := m.stub(cmd)
	return m.capture(taskManagerAddTaskArgument{cmd: cmd}, taskManagerAddTaskReturn{first: v0, second: v1})
}

func (m *taskManagerAddTask) invokeExpect(cmd *todocli.AddCmd) (*todocli.Task, error) {
	v0 := []any{"cmd", cmd}

	v1 := len(m.Calls)
	if v1 >= len(m.expects) {
		m.panic(mockgenMessageTooManyCalls(m, len(m.expects), v1+1, v0))
	}

	v2 := m.expects[v1]
	if v2.match != nil && !v2.match(cmd) {
		v2.tb.Helper()
		m.fatal(v1, mockgenMessageMatchFail(m, v2.matchLocation, v1, v0))
	}

	v2.tb.Helper()
	mockgenMatchArgument(m, v1, "cmd", cmd, v2.matcher.cmd, v2.matcherWants, v2.matcherMethods, v2.matcherHints, v2.tb, v2.matcherLocations["cmd"])

	return m.capture(taskManagerAddTaskArgument{cmd: cmd}, v2.returns)
}

func (m *taskManagerAddTask) capture(args taskManagerAddTaskArgument, returns taskManagerAddTaskReturn) (*todocli.Task, error) {
	m.Calls = append(m.Calls, taskManagerAddTaskCall{Location: mockgenCallerLocation(4), Argument: args, Return: returns})
	return returns.first, returns.second
}

func (m *taskManagerAddTask) verify(index int) {
	if !m.verified && index >= len(m.Calls) {
		m.expects[index].tb.Helper()
		m.expects[index].tb.Fatal(mockgenMessageExpectButNotCalled(m, len(m.expects), len(m.Calls), index))
	}
}

type taskManagerAddTaskCall struct {
	Location string
	Argument taskManagerAddTaskArgument
	Return   taskManagerAddTaskReturn
}

type taskManagerAddTaskArgument struct {
	cmd *todocli.AddCmd
}

type taskManagerAddTaskArgumentMatcher struct {
	cmd func(cmd *todocli.AddCmd) bool
}

type taskManagerAddTaskReturn struct {
	first  *todocli.Task
	second error
}

type taskManagerAddTaskExpect struct {
	match            func(cmd *todocli.AddCmd) bool
	matchLocation    string
	matcher          *taskManagerAddTaskArgumentMatcher
	matcherWants     map[string]any
	matcherMethods   map[string]string
	matcherHints     map[string]string
	matcherLocations map[string]string
	returns          taskManagerAddTaskReturn
	location         string
	index            int
	tb               testing.TB
}

type taskManagerAddTaskExpecter struct {
	expect *taskManagerAddTaskExpect
	target *taskManagerAddTask
}

func (e *taskManagerAddTaskExpecter) Return(first *todocli.Task, second error) {
	e.expect.returns = taskManagerAddTaskReturn{first: first, second: second}
}

func (e *taskManagerAddTaskExpecter) Match(matcher func(cmd *todocli.AddCmd) bool) *taskManagerAddTaskExpecterWithMatch {
	if matcher == nil {
		e.expect.tb.Helper()
		e.target.fatal(e.expect.index, mockgenMessageMatchByNil(e.target))
	}

	e.expect.match = matcher
	e.expect.matchLocation = mockgenCallerLocation(2)
	return &taskManagerAddTaskExpecterWithMatch{expect: e.expect}
}

func (e *taskManagerAddTaskExpecter) MatchCmd(matcher func(cmd *todocli.AddCmd) bool) *taskManagerAddTaskExpecterWithMatchArg {
	if matcher == nil {
		e.expect.tb.Helper()
		e.target.fatal(e.expect.index, mockgenMessageMatchArgByNil(e.target, "MatchCmd"))
	}

	e.expect.matcher.cmd = matcher
	e.expect.matcherLocations["cmd"] = mockgenCallerLocation(2)
	e.expect.matcherHints["cmd"] = mockgenMessageMatchArgHint()
	return &taskManagerAddTaskExpecterWithMatchArg{expect: e.expect, target: e.target}
}

func (e *taskManagerAddTaskExpecter) With(cmd *todocli.AddCmd) *taskManagerAddTaskExpecterWithValue {
	e.WithCmd(cmd)
	e.expect.matcherLocations["cmd"] = mockgenCallerLocation(2)

	return &taskManagerAddTaskExpecterWithValue{expect: e.expect}
}

func (e *taskManagerAddTaskExpecter) WithCmd(cmd *todocli.AddCmd) *taskManagerAddTaskExpecterWithValueArg {
	e.expect.matcher.cmd = mockgenBasicComparisonMatcher(cmd)
	e.expect.matcherWants["cmd"] = cmd
	e.expect.matcherMethods["cmd"] = "=="
	e.expect.matcherLocations["cmd"] = mockgenCallerLocation(2)

	return &taskManagerAddTaskExpecterWithValueArg{expect: e.expect, target: e.target}
}

type taskManagerAddTaskExpecterWithMatch struct {
	expect *taskManagerAddTaskExpect
}

func (e *taskManagerAddTaskExpecterWithMatch) Return(first *todocli.Task, second error) {
	e.expect.returns = taskManagerAddTaskReturn{first: first, second: second}
}

type taskManagerAddTaskExpecterWithMatchArg struct {
	expect *taskManagerAddTaskExpect
	target *taskManagerAddTask
}

func (e *taskManagerAddTaskExpecterWithMatchArg) Return(first *todocli.Task, second error) {
	e.expect.returns = taskManagerAddTaskReturn{first: first, second: second}
}

func (e *taskManagerAddTaskExpecterWithMatchArg) MatchCmd(matcher func(cmd *todocli.AddCmd) bool) *taskManagerAddTaskExpecterWithMatchArg {
	if matcher == nil {
		e.expect.tb.Helper()
		e.target.fatal(e.expect.index, mockgenMessageMatchArgByNil(e.target, "MatchCmd"))
	}

	if e.expect.matcher.cmd != nil {
		e.expect.tb.Helper()
		e.target.fatal(e.expect.index, mockgenMessageDuplicateMatchArg(e.target, "MatchCmd", e.expect.matcherLocations["cmd"]))
	}

	e.expect.matcher.cmd = matcher
	e.expect.matcherLocations["cmd"] = mockgenCallerLocation(2)
	e.expect.matcherHints["cmd"] = mockgenMessageMatchArgHint()
	return e
}

type taskManagerAddTaskExpecterWithValue struct {
	expect *taskManagerAddTaskExpect
}

func (e *taskManagerAddTaskExpecterWithValue) Return(first *todocli.Task, second error) {
	e.expect.returns = taskManagerAddTaskReturn{first: first, second: second}
}

type taskManagerAddTaskExpecterWithValueArg struct {
	expect *taskManagerAddTaskExpect
	target *taskManagerAddTask
}

func (e *taskManagerAddTaskExpecterWithValueArg) Return(first *todocli.Task, second error) {
	e.expect.returns = taskManagerAddTaskReturn{first: first, second: second}
}

func (e *taskManagerAddTaskExpecterWithValueArg) WithCmd(cmd *todocli.AddCmd) *taskManagerAddTaskExpecterWithValueArg {
	if e.expect.matcher.cmd != nil {
		e.expect.tb.Helper()
		e.target.fatal(e.expect.index, mockgenMessageDuplicateMatchArg(e.target, "WithCmd", e.expect.matcherLocations["cmd"]))
	}

	e.expect.matcher.cmd = mockgenBasicComparisonMatcher(cmd)
	e.expect.matcherWants["cmd"] = cmd
	e.expect.matcherMethods["cmd"] = "=="
	e.expect.matcherLocations["cmd"] = mockgenCallerLocation(2)

	return e
}

type taskManagerDeleteTask struct {
	Calls        []taskManagerDeleteTaskCall
	stub         func(cmd *todocli.DeleteCmd) error
	stubLocation string
	expects      []*taskManagerDeleteTaskExpect
	verified     bool
}

func (m *taskManagerDeleteTask) methodName() string {
	return "DeleteTask"
}

func (m *taskManagerDeleteTask) interfaceName() string {
	return "TaskManager"
}

func (m *taskManagerDeleteTask) fatal(index int, msg string) {
	m.verified = true
	m.expects[index].tb.Helper()
	m.expects[index].tb.Fatal(msg)
}

func (m *taskManagerDeleteTask) panic(msg string) {
	m.verified = true
	panic(msg)
}

func (m *taskManagerDeleteTask) buildCallHistory(sb *strings.Builder, header string) {
	if header != "" && len(m.Calls) != 0 {
		sb.WriteString(fmt.Sprintf("%s:\n", header))
	}

	for i, v := range m.Calls {
		a := []any{"cmd", v.Argument.cmd}
		mockgenMessageCallHistory(sb, i, m.expects[i].location, v.Location, a)
	}
}

func (m *taskManagerDeleteTask) invokeStub(cmd *todocli.DeleteCmd) error {
	v0 := m.stub(cmd)
	return m.capture(taskManagerDeleteTaskArgument{cmd: cmd}, taskManagerDeleteTaskReturn{first: v0})
}

func (m *taskManagerDeleteTask) invokeExpect(cmd *todocli.DeleteCmd) error {
	v0 := []any{"cmd", cmd}

	v1 := len(m.Calls)
	if v1 >= len(m.expects) {
		m.panic(mockgenMessageTooManyCalls(m, len(m.expects), v1+1, v0))
	}

	v2 := m.expects[v1]
	if v2.match != nil && !v2.match(cmd) {
		v2.tb.Helper()
		m.fatal(v1, mockgenMessageMatchFail(m, v2.matchLocation, v1, v0))
	}

	v2.tb.Helper()
	mockgenMatchArgument(m, v1, "cmd", cmd, v2.matcher.cmd, v2.matcherWants, v2.matcherMethods, v2.matcherHints, v2.tb, v2.matcherLocations["cmd"])

	return m.capture(taskManagerDeleteTaskArgument{cmd: cmd}, v2.returns)
}

func (m *taskManagerDeleteTask) capture(args taskManagerDeleteTaskArgument, returns taskManagerDeleteTaskReturn) error {
	m.Calls = append(m.Calls, taskManagerDeleteTaskCall{Location: mockgenCallerLocation(4), Argument: args, Return: returns})
	return returns.first
}

func (m *taskManagerDeleteTask) verify(index int) {
	if !m.verified && index >= len(m.Calls) {
		m.expects[index].tb.Helper()
		m.expects[index].tb.Fatal(mockgenMessageExpectButNotCalled(m, len(m.expects), len(m.Calls), index))
	}
}

type taskManagerDeleteTaskCall struct {
	Location string
	Argument taskManagerDeleteTaskArgument
	Return   taskManagerDeleteTaskReturn
}

type taskManagerDeleteTaskArgument struct {
	cmd *todocli.DeleteCmd
}

type taskManagerDeleteTaskArgumentMatcher struct {
	cmd func(cmd *todocli.DeleteCmd) bool
}

type taskManagerDeleteTaskReturn struct {
	first error
}

type taskManagerDeleteTaskExpect struct {
	match            func(cmd *todocli.DeleteCmd) bool
	matchLocation    string
	matcher          *taskManagerDeleteTaskArgumentMatcher
	matcherWants     map[string]any
	matcherMethods   map[string]string
	matcherHints     map[string]string
	matcherLocations map[string]string
	returns          taskManagerDeleteTaskReturn
	location         string
	index            int
	tb               testing.TB
}

type taskManagerDeleteTaskExpecter struct {
	expect *taskManagerDeleteTaskExpect
	target *taskManagerDeleteTask
}

func (e *taskManagerDeleteTaskExpecter) Return(first error) {
	e.expect.returns = taskManagerDeleteTaskReturn{first: first}
}

func (e *taskManagerDeleteTaskExpecter) Match(matcher func(cmd *todocli.DeleteCmd) bool) *taskManagerDeleteTaskExpecterWithMatch {
	if matcher == nil {
		e.expect.tb.Helper()
		e.target.fatal(e.expect.index, mockgenMessageMatchByNil(e.target))
	}

	e.expect.match = matcher
	e.expect.matchLocation = mockgenCallerLocation(2)
	return &taskManagerDeleteTaskExpecterWithMatch{expect: e.expect}
}

func (e *taskManagerDeleteTaskExpecter) MatchCmd(matcher func(cmd *todocli.DeleteCmd) bool) *taskManagerDeleteTaskExpecterWithMatchArg {
	if matcher == nil {
		e.expect.tb.Helper()
		e.target.fatal(e.expect.index, mockgenMessageMatchArgByNil(e.target, "MatchCmd"))
	}

	e.expect.matcher.cmd = matcher
	e.expect.matcherLocations["cmd"] = mockgenCallerLocation(2)
	e.expect.matcherHints["cmd"] = mockgenMessageMatchArgHint()
	return &taskManagerDeleteTaskExpecterWithMatchArg{expect: e.expect, target: e.target}
}

func (e *taskManagerDeleteTaskExpecter) With(cmd *todocli.DeleteCmd) *taskManagerDeleteTaskExpecterWithValue {
	e.WithCmd(cmd)
	e.expect.matcherLocations["cmd"] = mockgenCallerLocation(2)

	return &taskManagerDeleteTaskExpecterWithValue{expect: e.expect}
}

func (e *taskManagerDeleteTaskExpecter) WithCmd(cmd *todocli.DeleteCmd) *taskManagerDeleteTaskExpecterWithValueArg {
	e.expect.matcher.cmd = mockgenBasicComparisonMatcher(cmd)
	e.expect.matcherWants["cmd"] = cmd
	e.expect.matcherMethods["cmd"] = "=="
	e.expect.matcherLocations["cmd"] = mockgenCallerLocation(2)

	return &taskManagerDeleteTaskExpecterWithValueArg{expect: e.expect, target: e.target}
}

type taskManagerDeleteTaskExpecterWithMatch struct {
	expect *taskManagerDeleteTaskExpect
}

func (e *taskManagerDeleteTaskExpecterWithMatch) Return(first error) {
	e.expect.returns = taskManagerDeleteTaskReturn{first: first}
}

type taskManagerDeleteTaskExpecterWithMatchArg struct {
	expect *taskManagerDeleteTaskExpect
	target *taskManagerDeleteTask
}

func (e *taskManagerDeleteTaskExpecterWithMatchArg) Return(first error) {
	e.expect.returns = taskManagerDeleteTaskReturn{first: first}
}

func (e *taskManagerDeleteTaskExpecterWithMatchArg) MatchCmd(matcher func(cmd *todocli.DeleteCmd) bool) *taskManagerDeleteTaskExpecterWithMatchArg {
	if matcher == nil {
		e.expect.tb.Helper()
		e.target.fatal(e.expect.index, mockgenMessageMatchArgByNil(e.target, "MatchCmd"))
	}

	if e.expect.matcher.cmd != nil {
		e.expect.tb.Helper()
		e.target.fatal(e.expect.index, mockgenMessageDuplicateMatchArg(e.target, "MatchCmd", e.expect.matcherLocations["cmd"]))
	}

	e.expect.matcher.cmd = matcher
	e.expect.matcherLocations["cmd"] = mockgenCallerLocation(2)
	e.expect.matcherHints["cmd"] = mockgenMessageMatchArgHint()
	return e
}

type taskManagerDeleteTaskExpecterWithValue struct {
	expect *taskManagerDeleteTaskExpect
}

func (e *taskManagerDeleteTaskExpecterWithValue) Return(first error) {
	e.expect.returns = taskManagerDeleteTaskReturn{first: first}
}

type taskManagerDeleteTaskExpecterWithValueArg struct {
	expect *taskManagerDeleteTaskExpect
	target *taskManagerDeleteTask
}

func (e *taskManagerDeleteTaskExpecterWithValueArg) Return(first error) {
	e.expect.returns = taskManagerDeleteTaskReturn{first: first}
}

func (e *taskManagerDeleteTaskExpecterWithValueArg) WithCmd(cmd *todocli.DeleteCmd) *taskManagerDeleteTaskExpecterWithValueArg {
	if e.expect.matcher.cmd != nil {
		e.expect.tb.Helper()
		e.target.fatal(e.expect.index, mockgenMessageDuplicateMatchArg(e.target, "WithCmd", e.expect.matcherLocations["cmd"]))
	}

	e.expect.matcher.cmd = mockgenBasicComparisonMatcher(cmd)
	e.expect.matcherWants["cmd"] = cmd
	e.expect.matcherMethods["cmd"] = "=="
	e.expect.matcherLocations["cmd"] = mockgenCallerLocation(2)

	return e
}

type taskManagerListTasks struct {
	Calls        []taskManagerListTasksCall
	stub         func(cmd *todocli.ListCmd) ([]todocli.Task, error)
	stubLocation string
	expects      []*taskManagerListTasksExpect
	verified     bool
}

func (m *taskManagerListTasks) methodName() string {
	return "ListTasks"
}

func (m *taskManagerListTasks) interfaceName() string {
	return "TaskManager"
}

func (m *taskManagerListTasks) fatal(index int, msg string) {
	m.verified = true
	m.expects[index].tb.Helper()
	m.expects[index].tb.Fatal(msg)
}

func (m *taskManagerListTasks) panic(msg string) {
	m.verified = true
	panic(msg)
}

func (m *taskManagerListTasks) buildCallHistory(sb *strings.Builder, header string) {
	if header != "" && len(m.Calls) != 0 {
		sb.WriteString(fmt.Sprintf("%s:\n", header))
	}

	for i, v := range m.Calls {
		a := []any{"cmd", v.Argument.cmd}
		mockgenMessageCallHistory(sb, i, m.expects[i].location, v.Location, a)
	}
}

func (m *taskManagerListTasks) invokeStub(cmd *todocli.ListCmd) ([]todocli.Task, error) {
	v0, v1 := m.stub(cmd)
	return m.capture(taskManagerListTasksArgument{cmd: cmd}, taskManagerListTasksReturn{first: v0, second: v1})
}

func (m *taskManagerListTasks) invokeExpect(cmd *todocli.ListCmd) ([]todocli.Task, error) {
	v0 := []any{"cmd", cmd}

	v1 := len(m.Calls)
	if v1 >= len(m.expects) {
		m.panic(mockgenMessageTooManyCalls(m, len(m.expects), v1+1, v0))
	}

	v2 := m.expects[v1]
	if v2.match != nil && !v2.match(cmd) {
		v2.tb.Helper()
		m.fatal(v1, mockgenMessageMatchFail(m, v2.matchLocation, v1, v0))
	}

	v2.tb.Helper()
	mockgenMatchArgument(m, v1, "cmd", cmd, v2.matcher.cmd, v2.matcherWants, v2.matcherMethods, v2.matcherHints, v2.tb, v2.matcherLocations["cmd"])

	return m.capture(taskManagerListTasksArgument{cmd: cmd}, v2.returns)
}

func (m *taskManagerListTasks) capture(args taskManagerListTasksArgument, returns taskManagerListTasksReturn) ([]todocli.Task, error) {
	m.Calls = append(m.Calls, taskManagerListTasksCall{Location: mockgenCallerLocation(4), Argument: args, Return: returns})
	return returns.first, returns.second
}

func (m *taskManagerListTasks) verify(index int) {
	if !m.verified && index >= len(m.Calls) {
		m.expects[index].tb.Helper()
		m.expects[index].tb.Fatal(mockgenMessageExpectButNotCalled(m, len(m.expects), len(m.Calls), index))
	}
}

type taskManagerListTasksCall struct {
	Location string
	Argument taskManagerListTasksArgument
	Return   taskManagerListTasksReturn
}

type taskManagerListTasksArgument struct {
	cmd *todocli.ListCmd
}

type taskManagerListTasksArgumentMatcher struct {
	cmd func(cmd *todocli.ListCmd) bool
}

type taskManagerListTasksReturn struct {
	first  []todocli.Task
	second error
}

type taskManagerListTasksExpect struct {
	match            func(cmd *todocli.ListCmd) bool
	matchLocation    string
	matcher          *taskManagerListTasksArgumentMatcher
	matcherWants     map[string]any
	matcherMethods   map[string]string
	matcherHints     map[string]string
	matcherLocations map[string]string
	returns          taskManagerListTasksReturn
	location         string
	index            int
	tb               testing.TB
}

type taskManagerListTasksExpecter struct {
	expect *taskManagerListTasksExpect
	target *taskManagerListTasks
}

func (e *taskManagerListTasksExpecter) Return(first []todocli.Task, second error) {
	e.expect.returns = taskManagerListTasksReturn{first: first, second: second}
}

func (e *taskManagerListTasksExpecter) Match(matcher func(cmd *todocli.ListCmd) bool) *taskManagerListTasksExpecterWithMatch {
	if matcher == nil {
		e.expect.tb.Helper()
		e.target.fatal(e.expect.index, mockgenMessageMatchByNil(e.target))
	}

	e.expect.match = matcher
	e.expect.matchLocation = mockgenCallerLocation(2)
	return &taskManagerListTasksExpecterWithMatch{expect: e.expect}
}

func (e *taskManagerListTasksExpecter) MatchCmd(matcher func(cmd *todocli.ListCmd) bool) *taskManagerListTasksExpecterWithMatchArg {
	if matcher == nil {
		e.expect.tb.Helper()
		e.target.fatal(e.expect.index, mockgenMessageMatchArgByNil(e.target, "MatchCmd"))
	}

	e.expect.matcher.cmd = matcher
	e.expect.matcherLocations["cmd"] = mockgenCallerLocation(2)
	e.expect.matcherHints["cmd"] = mockgenMessageMatchArgHint()
	return &taskManagerListTasksExpecterWithMatchArg{expect: e.expect, target: e.target}
}

func (e *taskManagerListTasksExpecter) With(cmd *todocli.ListCmd) *taskManagerListTasksExpecterWithValue {
	e.WithCmd(cmd)
	e.expect.matcherLocations["cmd"] = mockgenCallerLocation(2)

	return &taskManagerListTasksExpecterWithValue{expect: e.expect}
}

func (e *taskManagerListTasksExpecter) WithCmd(cmd *todocli.ListCmd) *taskManagerListTasksExpecterWithValueArg {
	e.expect.matcher.cmd = mockgenBasicComparisonMatcher(cmd)
	e.expect.matcherWants["cmd"] = cmd
	e.expect.matcherMethods["cmd"] = "=="
	e.expect.matcherLocations["cmd"] = mockgenCallerLocation(2)

	return &taskManagerListTasksExpecterWithValueArg{expect: e.expect, target: e.target}
}

type taskManagerListTasksExpecterWithMatch struct {
	expect *taskManagerListTasksExpect
}

func (e *taskManagerListTasksExpecterWithMatch) Return(first []todocli.Task, second error) {
	e.expect.returns = taskManagerListTasksReturn{first: first, second: second}
}

type taskManagerListTasksExpecterWithMatchArg struct {
	expect *taskManagerListTasksExpect
	target *taskManagerListTasks
}

func (e *taskManagerListTasksExpecterWithMatchArg) Return(first []todocli.Task, second error) {
	e.expect.returns = taskManagerListTasksReturn{first: first, second: second}
}

func (e *taskManagerListTasksExpecterWithMatchArg) MatchCmd(matcher func(cmd *todocli.ListCmd) bool) *taskManagerListTasksExpecterWithMatchArg {
	if matcher == nil {
		e.expect.tb.Helper()
		e.target.fatal(e.expect.index, mockgenMessageMatchArgByNil(e.target, "MatchCmd"))
	}

	if e.expect.matcher.cmd != nil {
		e.expect.tb.Helper()
		e.target.fatal(e.expect.index, mockgenMessageDuplicateMatchArg(e.target, "MatchCmd", e.expect.matcherLocations["cmd"]))
	}

	e.expect.matcher.cmd = matcher
	e.expect.matcherLocations["cmd"] = mockgenCallerLocation(2)
	e.expect.matcherHints["cmd"] = mockgenMessageMatchArgHint()
	return e
}

type taskManagerListTasksExpecterWithValue struct {
	expect *taskManagerListTasksExpect
}

func (e *taskManagerListTasksExpecterWithValue) Return(first []todocli.Task, second error) {
	e.expect.returns = taskManagerListTasksReturn{first: first, second: second}
}

type taskManagerListTasksExpecterWithValueArg struct {
	expect *taskManagerListTasksExpect
	target *taskManagerListTasks
}

func (e *taskManagerListTasksExpecterWithValueArg) Return(first []todocli.Task, second error) {
	e.expect.returns = taskManagerListTasksReturn{first: first, second: second}
}

func (e *taskManagerListTasksExpecterWithValueArg) WithCmd(cmd *todocli.ListCmd) *taskManagerListTasksExpecterWithValueArg {
	if e.expect.matcher.cmd != nil {
		e.expect.tb.Helper()
		e.target.fatal(e.expect.index, mockgenMessageDuplicateMatchArg(e.target, "WithCmd", e.expect.matcherLocations["cmd"]))
	}

	e.expect.matcher.cmd = mockgenBasicComparisonMatcher(cmd)
	e.expect.matcherWants["cmd"] = cmd
	e.expect.matcherMethods["cmd"] = "=="
	e.expect.matcherLocations["cmd"] = mockgenCallerLocation(2)

	return e
}

type taskManagerToggleDone struct {
	Calls        []taskManagerToggleDoneCall
	stub         func(cmd *todocli.DoneCmd) (*todocli.Task, error)
	stubLocation string
	expects      []*taskManagerToggleDoneExpect
	verified     bool
}

func (m *taskManagerToggleDone) methodName() string {
	return "ToggleDone"
}

func (m *taskManagerToggleDone) interfaceName() string {
	return "TaskManager"
}

func (m *taskManagerToggleDone) fatal(index int, msg string) {
	m.verified = true
	m.expects[index].tb.Helper()
	m.expects[index].tb.Fatal(msg)
}

func (m *taskManagerToggleDone) panic(msg string) {
	m.verified = true
	panic(msg)
}

func (m *taskManagerToggleDone) buildCallHistory(sb *strings.Builder, header string) {
	if header != "" && len(m.Calls) != 0 {
		sb.WriteString(fmt.Sprintf("%s:\n", header))
	}

	for i, v := range m.Calls {
		a := []any{"cmd", v.Argument.cmd}
		mockgenMessageCallHistory(sb, i, m.expects[i].location, v.Location, a)
	}
}

func (m *taskManagerToggleDone) invokeStub(cmd *todocli.DoneCmd) (*todocli.Task, error) {
	v0, v1 := m.stub(cmd)
	return m.capture(taskManagerToggleDoneArgument{cmd: cmd}, taskManagerToggleDoneReturn{first: v0, second: v1})
}

func (m *taskManagerToggleDone) invokeExpect(cmd *todocli.DoneCmd) (*todocli.Task, error) {
	v0 := []any{"cmd", cmd}

	v1 := len(m.Calls)
	if v1 >= len(m.expects) {
		m.panic(mockgenMessageTooManyCalls(m, len(m.expects), v1+1, v0))
	}

	v2 := m.expects[v1]
	if v2.match != nil && !v2.match(cmd) {
		v2.tb.Helper()
		m.fatal(v1, mockgenMessageMatchFail(m, v2.matchLocation, v1, v0))
	}

	v2.tb.Helper()
	mockgenMatchArgument(m, v1, "cmd", cmd, v2.matcher.cmd, v2.matcherWants, v2.matcherMethods, v2.matcherHints, v2.tb, v2.matcherLocations["cmd"])

	return m.capture(taskManagerToggleDoneArgument{cmd: cmd}, v2.returns)
}

func (m *taskManagerToggleDone) capture(args taskManagerToggleDoneArgument, returns taskManagerToggleDoneReturn) (*todocli.Task, error) {
	m.Calls = append(m.Calls, taskManagerToggleDoneCall{Location: mockgenCallerLocation(4), Argument: args, Return: returns})
	return returns.first, returns.second
}

func (m *taskManagerToggleDone) verify(index int) {
	if !m.verified && index >= len(m.Calls) {
		m.expects[index].tb.Helper()
		m.expects[index].tb.Fatal(mockgenMessageExpectButNotCalled(m, len(m.expects), len(m.Calls), index))
	}
}

type taskManagerToggleDoneCall struct {
	Location string
	Argument taskManagerToggleDoneArgument
	Return   taskManagerToggleDoneReturn
}

type taskManagerToggleDoneArgument struct {
	cmd *todocli.DoneCmd
}

type taskManagerToggleDoneArgumentMatcher struct {
	cmd func(cmd *todocli.DoneCmd) bool
}

type taskManagerToggleDoneReturn struct {
	first  *todocli.Task
	second error
}

type taskManagerToggleDoneExpect struct {
	match            func(cmd *todocli.DoneCmd) bool
	matchLocation    string
	matcher          *taskManagerToggleDoneArgumentMatcher
	matcherWants     map[string]any
	matcherMethods   map[string]string
	matcherHints     map[string]string
	matcherLocations map[string]string
	returns          taskManagerToggleDoneReturn
	location         string
	index            int
	tb               testing.TB
}

type taskManagerToggleDoneExpecter struct {
	expect *taskManagerToggleDoneExpect
	target *taskManagerToggleDone
}

func (e *taskManagerToggleDoneExpecter) Return(first *todocli.Task, second error) {
	e.expect.returns = taskManagerToggleDoneReturn{first: first, second: second}
}

func (e *taskManagerToggleDoneExpecter) Match(matcher func(cmd *todocli.DoneCmd) bool) *taskManagerToggleDoneExpecterWithMatch {
	if matcher == nil {
		e.expect.tb.Helper()
		e.target.fatal(e.expect.index, mockgenMessageMatchByNil(e.target))
	}

	e.expect.match = matcher
	e.expect.matchLocation = mockgenCallerLocation(2)
	return &taskManagerToggleDoneExpecterWithMatch{expect: e.expect}
}

func (e *taskManagerToggleDoneExpecter) MatchCmd(matcher func(cmd *todocli.DoneCmd) bool) *taskManagerToggleDoneExpecterWithMatchArg {
	if matcher == nil {
		e.expect.tb.Helper()
		e.target.fatal(e.expect.index, mockgenMessageMatchArgByNil(e.target, "MatchCmd"))
	}

	e.expect.matcher.cmd = matcher
	e.expect.matcherLocations["cmd"] = mockgenCallerLocation(2)
	e.expect.matcherHints["cmd"] = mockgenMessageMatchArgHint()
	return &taskManagerToggleDoneExpecterWithMatchArg{expect: e.expect, target: e.target}
}

func (e *taskManagerToggleDoneExpecter) With(cmd *todocli.DoneCmd) *taskManagerToggleDoneExpecterWithValue {
	e.WithCmd(cmd)
	e.expect.matcherLocations["cmd"] = mockgenCallerLocation(2)

	return &taskManagerToggleDoneExpecterWithValue{expect: e.expect}
}

func (e *taskManagerToggleDoneExpecter) WithCmd(cmd *todocli.DoneCmd) *taskManagerToggleDoneExpecterWithValueArg {
	e.expect.matcher.cmd = mockgenBasicComparisonMatcher(cmd)
	e.expect.matcherWants["cmd"] = cmd
	e.expect.matcherMethods["cmd"] = "=="
	e.expect.matcherLocations["cmd"] = mockgenCallerLocation(2)

	return &taskManagerToggleDoneExpecterWithValueArg{expect: e.expect, target: e.target}
}

type taskManagerToggleDoneExpecterWithMatch struct {
	expect *taskManagerToggleDoneExpect
}

func (e *taskManagerToggleDoneExpecterWithMatch) Return(first *todocli.Task, second error) {
	e.expect.returns = taskManagerToggleDoneReturn{first: first, second: second}
}

type taskManagerToggleDoneExpecterWithMatchArg struct {
	expect *taskManagerToggleDoneExpect
	target *taskManagerToggleDone
}

func (e *taskManagerToggleDoneExpecterWithMatchArg) Return(first *todocli.Task, second error) {
	e.expect.returns = taskManagerToggleDoneReturn{first: first, second: second}
}

func (e *taskManagerToggleDoneExpecterWithMatchArg) MatchCmd(matcher func(cmd *todocli.DoneCmd) bool) *taskManagerToggleDoneExpecterWithMatchArg {
	if matcher == nil {
		e.expect.tb.Helper()
		e.target.fatal(e.expect.index, mockgenMessageMatchArgByNil(e.target, "MatchCmd"))
	}

	if e.expect.matcher.cmd != nil {
		e.expect.tb.Helper()
		e.target.fatal(e.expect.index, mockgenMessageDuplicateMatchArg(e.target, "MatchCmd", e.expect.matcherLocations["cmd"]))
	}

	e.expect.matcher.cmd = matcher
	e.expect.matcherLocations["cmd"] = mockgenCallerLocation(2)
	e.expect.matcherHints["cmd"] = mockgenMessageMatchArgHint()
	return e
}

type taskManagerToggleDoneExpecterWithValue struct {
	expect *taskManagerToggleDoneExpect
}

func (e *taskManagerToggleDoneExpecterWithValue) Return(first *todocli.Task, second error) {
	e.expect.returns = taskManagerToggleDoneReturn{first: first, second: second}
}

type taskManagerToggleDoneExpecterWithValueArg struct {
	expect *taskManagerToggleDoneExpect
	target *taskManagerToggleDone
}

func (e *taskManagerToggleDoneExpecterWithValueArg) Return(first *todocli.Task, second error) {
	e.expect.returns = taskManagerToggleDoneReturn{first: first, second: second}
}

func (e *taskManagerToggleDoneExpecterWithValueArg) WithCmd(cmd *todocli.DoneCmd) *taskManagerToggleDoneExpecterWithValueArg {
	if e.expect.matcher.cmd != nil {
		e.expect.tb.Helper()
		e.target.fatal(e.expect.index, mockgenMessageDuplicateMatchArg(e.target, "WithCmd", e.expect.matcherLocations["cmd"]))
	}

	e.expect.matcher.cmd = mockgenBasicComparisonMatcher(cmd)
	e.expect.matcherWants["cmd"] = cmd
	e.expect.matcherMethods["cmd"] = "=="
	e.expect.matcherLocations["cmd"] = mockgenCallerLocation(2)

	return e
}

type taskManagerUpdateTasks struct {
	Calls        []taskManagerUpdateTasksCall
	stub         func(cmd *todocli.UpdateCmd) (*todocli.Task, error)
	stubLocation string
	expects      []*taskManagerUpdateTasksExpect
	verified     bool
}

func (m *taskManagerUpdateTasks) methodName() string {
	return "UpdateTasks"
}

func (m *taskManagerUpdateTasks) interfaceName() string {
	return "TaskManager"
}

func (m *taskManagerUpdateTasks) fatal(index int, msg string) {
	m.verified = true
	m.expects[index].tb.Helper()
	m.expects[index].tb.Fatal(msg)
}

func (m *taskManagerUpdateTasks) panic(msg string) {
	m.verified = true
	panic(msg)
}

func (m *taskManagerUpdateTasks) buildCallHistory(sb *strings.Builder, header string) {
	if header != "" && len(m.Calls) != 0 {
		sb.WriteString(fmt.Sprintf("%s:\n", header))
	}

	for i, v := range m.Calls {
		a := []any{"cmd", v.Argument.cmd}
		mockgenMessageCallHistory(sb, i, m.expects[i].location, v.Location, a)
	}
}

func (m *taskManagerUpdateTasks) invokeStub(cmd *todocli.UpdateCmd) (*todocli.Task, error) {
	v0, v1 := m.stub(cmd)
	return m.capture(taskManagerUpdateTasksArgument{cmd: cmd}, taskManagerUpdateTasksReturn{first: v0, second: v1})
}

func (m *taskManagerUpdateTasks) invokeExpect(cmd *todocli.UpdateCmd) (*todocli.Task, error) {
	v0 := []any{"cmd", cmd}

	v1 := len(m.Calls)
	if v1 >= len(m.expects) {
		m.panic(mockgenMessageTooManyCalls(m, len(m.expects), v1+1, v0))
	}

	v2 := m.expects[v1]
	if v2.match != nil && !v2.match(cmd) {
		v2.tb.Helper()
		m.fatal(v1, mockgenMessageMatchFail(m, v2.matchLocation, v1, v0))
	}

	v2.tb.Helper()
	mockgenMatchArgument(m, v1, "cmd", cmd, v2.matcher.cmd, v2.matcherWants, v2.matcherMethods, v2.matcherHints, v2.tb, v2.matcherLocations["cmd"])

	return m.capture(taskManagerUpdateTasksArgument{cmd: cmd}, v2.returns)
}

func (m *taskManagerUpdateTasks) capture(args taskManagerUpdateTasksArgument, returns taskManagerUpdateTasksReturn) (*todocli.Task, error) {
	m.Calls = append(m.Calls, taskManagerUpdateTasksCall{Location: mockgenCallerLocation(4), Argument: args, Return: returns})
	return returns.first, returns.second
}

func (m *taskManagerUpdateTasks) verify(index int) {
	if !m.verified && index >= len(m.Calls) {
		m.expects[index].tb.Helper()
		m.expects[index].tb.Fatal(mockgenMessageExpectButNotCalled(m, len(m.expects), len(m.Calls), index))
	}
}

type taskManagerUpdateTasksCall struct {
	Location string
	Argument taskManagerUpdateTasksArgument
	Return   taskManagerUpdateTasksReturn
}

type taskManagerUpdateTasksArgument struct {
	cmd *todocli.UpdateCmd
}

type taskManagerUpdateTasksArgumentMatcher struct {
	cmd func(cmd *todocli.UpdateCmd) bool
}

type taskManagerUpdateTasksReturn struct {
	first  *todocli.Task
	second error
}

type taskManagerUpdateTasksExpect struct {
	match            func(cmd *todocli.UpdateCmd) bool
	matchLocation    string
	matcher          *taskManagerUpdateTasksArgumentMatcher
	matcherWants     map[string]any
	matcherMethods   map[string]string
	matcherHints     map[string]string
	matcherLocations map[string]string
	returns          taskManagerUpdateTasksReturn
	location         string
	index            int
	tb               testing.TB
}

type taskManagerUpdateTasksExpecter struct {
	expect *taskManagerUpdateTasksExpect
	target *taskManagerUpdateTasks
}

func (e *taskManagerUpdateTasksExpecter) Return(first *todocli.Task, second error) {
	e.expect.returns = taskManagerUpdateTasksReturn{first: first, second: second}
}

func (e *taskManagerUpdateTasksExpecter) Match(matcher func(cmd *todocli.UpdateCmd) bool) *taskManagerUpdateTasksExpecterWithMatch {
	if matcher == nil {
		e.expect.tb.Helper()
		e.target.fatal(e.expect.index, mockgenMessageMatchByNil(e.target))
	}

	e.expect.match = matcher
	e.expect.matchLocation = mockgenCallerLocation(2)
	return &taskManagerUpdateTasksExpecterWithMatch{expect: e.expect}
}

func (e *taskManagerUpdateTasksExpecter) MatchCmd(matcher func(cmd *todocli.UpdateCmd) bool) *taskManagerUpdateTasksExpecterWithMatchArg {
	if matcher == nil {
		e.expect.tb.Helper()
		e.target.fatal(e.expect.index, mockgenMessageMatchArgByNil(e.target, "MatchCmd"))
	}

	e.expect.matcher.cmd = matcher
	e.expect.matcherLocations["cmd"] = mockgenCallerLocation(2)
	e.expect.matcherHints["cmd"] = mockgenMessageMatchArgHint()
	return &taskManagerUpdateTasksExpecterWithMatchArg{expect: e.expect, target: e.target}
}

func (e *taskManagerUpdateTasksExpecter) With(cmd *todocli.UpdateCmd) *taskManagerUpdateTasksExpecterWithValue {
	e.WithCmd(cmd)
	e.expect.matcherLocations["cmd"] = mockgenCallerLocation(2)

	return &taskManagerUpdateTasksExpecterWithValue{expect: e.expect}
}

func (e *taskManagerUpdateTasksExpecter) WithCmd(cmd *todocli.UpdateCmd) *taskManagerUpdateTasksExpecterWithValueArg {
	e.expect.matcher.cmd = mockgenBasicComparisonMatcher(cmd)
	e.expect.matcherWants["cmd"] = cmd
	e.expect.matcherMethods["cmd"] = "=="
	e.expect.matcherLocations["cmd"] = mockgenCallerLocation(2)

	return &taskManagerUpdateTasksExpecterWithValueArg{expect: e.expect, target: e.target}
}

type taskManagerUpdateTasksExpecterWithMatch struct {
	expect *taskManagerUpdateTasksExpect
}

func (e *taskManagerUpdateTasksExpecterWithMatch) Return(first *todocli.Task, second error) {
	e.expect.returns = taskManagerUpdateTasksReturn{first: first, second: second}
}

type taskManagerUpdateTasksExpecterWithMatchArg struct {
	expect *taskManagerUpdateTasksExpect
	target *taskManagerUpdateTasks
}

func (e *taskManagerUpdateTasksExpecterWithMatchArg) Return(first *todocli.Task, second error) {
	e.expect.returns = taskManagerUpdateTasksReturn{first: first, second: second}
}

func (e *taskManagerUpdateTasksExpecterWithMatchArg) MatchCmd(matcher func(cmd *todocli.UpdateCmd) bool) *taskManagerUpdateTasksExpecterWithMatchArg {
	if matcher == nil {
		e.expect.tb.Helper()
		e.target.fatal(e.expect.index, mockgenMessageMatchArgByNil(e.target, "MatchCmd"))
	}

	if e.expect.matcher.cmd != nil {
		e.expect.tb.Helper()
		e.target.fatal(e.expect.index, mockgenMessageDuplicateMatchArg(e.target, "MatchCmd", e.expect.matcherLocations["cmd"]))
	}

	e.expect.matcher.cmd = matcher
	e.expect.matcherLocations["cmd"] = mockgenCallerLocation(2)
	e.expect.matcherHints["cmd"] = mockgenMessageMatchArgHint()
	return e
}

type taskManagerUpdateTasksExpecterWithValue struct {
	expect *taskManagerUpdateTasksExpect
}

func (e *taskManagerUpdateTasksExpecterWithValue) Return(first *todocli.Task, second error) {
	e.expect.returns = taskManagerUpdateTasksReturn{first: first, second: second}
}

type taskManagerUpdateTasksExpecterWithValueArg struct {
	expect *taskManagerUpdateTasksExpect
	target *taskManagerUpdateTasks
}

func (e *taskManagerUpdateTasksExpecterWithValueArg) Return(first *todocli.Task, second error) {
	e.expect.returns = taskManagerUpdateTasksReturn{first: first, second: second}
}

func (e *taskManagerUpdateTasksExpecterWithValueArg) WithCmd(cmd *todocli.UpdateCmd) *taskManagerUpdateTasksExpecterWithValueArg {
	if e.expect.matcher.cmd != nil {
		e.expect.tb.Helper()
		e.target.fatal(e.expect.index, mockgenMessageDuplicateMatchArg(e.target, "WithCmd", e.expect.matcherLocations["cmd"]))
	}

	e.expect.matcher.cmd = mockgenBasicComparisonMatcher(cmd)
	e.expect.matcherWants["cmd"] = cmd
	e.expect.matcherMethods["cmd"] = "=="
	e.expect.matcherLocations["cmd"] = mockgenCallerLocation(2)

	return e
}
