// Code generated by nhatp.com/go/mock-gen/cmd/go-mock-gen - v1.0.0. DO NOT EDIT.

package todo

import (
	"fmt"
	"path/filepath"
	"reflect"
	"runtime"
	"strconv"
	"strings"
	"testing"
)

func mockgenCallerLocation(skip int) string {
	_, file, line, _ := runtime.Caller(skip)
	return fmt.Sprintf("%s:%d", filepath.Base(file), line)
}

type mockgenMockMethod interface {
	methodName() string
	interfaceName() string
	buildCallHistory(sb *strings.Builder, header string)
	fatal(index int, msg string)
	panic(msg string)
}

func mockgenMessageWriteArguments(sb *strings.Builder, template string, args []any) {
	maxLen := 0
	for i := 0; i < len(args); i += 2 {
		str, ok := args[i].(string)
		if !ok {
			str = fmt.Sprintf("%v", args[i])
		}
		maxLen = max(maxLen, len(str))
	}

	format := strings.ReplaceAll(template, "[MAX-KEY-LEN]", strconv.Itoa(maxLen))
	for i := 0; i < len(args); i += 2 {
		key, ok := args[i].(string)
		if !ok {
			key = fmt.Sprintf("%v", args[i])
		}

		var val any
		if i+1 < len(args) {
			val = args[i+1]
		}
		sb.WriteString(fmt.Sprintf(format, key, val))
	}
}

func mockgenMessageMatchFail(m mockgenMockMethod, matchedAt string, index int, args []any) string {
	sb := &strings.Builder{}
	sb.WriteString(fmt.Sprintf("%s.%s call #%d did not match\n", m.interfaceName(), m.methodName(), index+1))
	sb.WriteString(fmt.Sprintf("arguments:\n"))
	mockgenMessageWriteArguments(sb, "\t%[MAX-KEY-LEN]s = %#v\n", args)
	sb.WriteString("\n")
	m.buildCallHistory(sb, "call history")
	sb.WriteString(fmt.Sprintf("hint: check the callback passed to Match at %s", matchedAt))
	return sb.String()
}

func mockgenMessageNotImplemented(interfaceName string, methodName string, signature string, createdLocation string, args []any) string {
	sb := &strings.Builder{}
	sb.WriteString(fmt.Sprintf("unexpected call to %s.%s\n", interfaceName, methodName))
	sb.WriteString(fmt.Sprintf("signature: %s.%s%s\n", interfaceName, methodName, signature))
	sb.WriteString(fmt.Sprintf("called at: %s\n", mockgenCallerLocation(3)))
	sb.WriteString("arguments:\n")
	mockgenMessageWriteArguments(sb, "\t%[MAX-KEY-LEN]s = %#v\n", args)

	location := ""
	if createdLocation != "" {
		location = " after " + createdLocation
	}
	sb.WriteString(fmt.Sprintf("\nhint:%s use one of:\n\t[var].EXPECT().%s(t)\n\t[var].STUB().%s(func(...) ...)\n\n", location, methodName, methodName))
	return sb.String()
}

func mockgenMessageCallHistory(sb *strings.Builder, index int, expectedAt string, calledAt string, args []any) string {
	sb.WriteString(fmt.Sprintf("\t#%d expect at: %s\n", index+1, expectedAt))
	sb.WriteString(fmt.Sprintf("\t   called at: %s\n", calledAt))
	sb.WriteString(fmt.Sprintf("\t   arguments:\n"))
	mockgenMessageWriteArguments(sb, "\t\t%[MAX-KEY-LEN]s = %#v\n", args)
	sb.WriteString("\n")
	return sb.String()
}

func mockgenMessageTooManyCalls(m mockgenMockMethod, want int, got int, args []any) string {
	sb := &strings.Builder{}
	sb.WriteString(fmt.Sprintf("too many calls to %s.%s\n", m.interfaceName(), m.methodName()))
	sb.WriteString(fmt.Sprintf("\twant: %d, got: %d\n\n", want, got))
	m.buildCallHistory(sb, "")
	sb.WriteString(fmt.Sprintf("\t#%d expect at: %s\n", got, "missing"))
	sb.WriteString(fmt.Sprintf("\t   called at: %s\n", mockgenCallerLocation(4)))
	sb.WriteString(fmt.Sprintf("\t   arguments:\n"))
	mockgenMessageWriteArguments(sb, "\t\t%[MAX-KEY-LEN]s = %#v\n", args)
	sb.WriteString("\n")
	sb.WriteString(fmt.Sprintf("\thint: remove unexpected call or add 1 more EXPECT:\n\t\t[var].EXPECT().%s(t)\n", m.methodName()))
	return sb.String()
}

func mockgenMessageMatchByNil(m mockgenMockMethod) string {
	sb := &strings.Builder{}
	sb.WriteString(fmt.Sprintf("%s.%s Match received a nil function\n", m.interfaceName(), m.methodName()))
	sb.WriteString("\thint: provide a valid function")
	return sb.String()
}

func mockgenMessageExpectByNil(m mockgenMockMethod) string {
	sb := &strings.Builder{}
	sb.WriteString(fmt.Sprintf("unexpected nil testing.TB in %s.%s\n", m.interfaceName(), m.methodName()))
	sb.WriteString(fmt.Sprintf("\tcalled at: %s\n\n", mockgenCallerLocation(3)))
	sb.WriteString("\thint: EXPECT requires a valid testing.TB, use STUB instead:\n")
	sb.WriteString(fmt.Sprintf("\t\tspy := [var].STUB().%s(func(...) ...)\n", m.methodName()))
	return sb.String()
}

func mockgenMessageExpectAfterStub(m mockgenMockMethod, stubAt string) string {
	sb := &strings.Builder{}
	sb.WriteString(fmt.Sprintf("conflicting usage for %s.%s\n", m.interfaceName(), m.methodName()))
	sb.WriteString(fmt.Sprintf("\t%14s: %s\n", "STUB used at", stubAt))
	sb.WriteString(fmt.Sprintf("\t%14s: %s\n\n", "EXPECT used at", mockgenCallerLocation(3)))
	sb.WriteString("\thint: use either EXPECT or STUB for the same method, not both\n\n")
	return sb.String()
}

func mockgenMessageStubByNil(m mockgenMockMethod, calledAt string) string {
	sb := &strings.Builder{}
	sb.WriteString(fmt.Sprintf("%s.%s STUB received a nil function\n", m.interfaceName(), m.methodName()))
	sb.WriteString(fmt.Sprintf("called at: %s\n\n", calledAt))
	sb.WriteString("hint: provide a valid function\n")
	return sb.String()
}

func mockgenMessageStubAfterExpect(m mockgenMockMethod, expectAt string) string {
	sb := &strings.Builder{}
	sb.WriteString(fmt.Sprintf("conflicting usage for %s.%s\n", m.interfaceName(), m.methodName()))
	sb.WriteString(fmt.Sprintf("\t%14s: %s\n", "EXPECT used at", expectAt))
	sb.WriteString(fmt.Sprintf("\t%14s: %s\n\n", "STUB used at", mockgenCallerLocation(3)))
	sb.WriteString("\thint: use either EXPECT or STUB for the same method, not both\n\n")
	return sb.String()
}

func mockgenMessageDuplicateStub(m mockgenMockMethod, firstUsedAt string) string {
	sb := &strings.Builder{}
	sb.WriteString(fmt.Sprintf("duplicate STUB for %s.%s\n", m.interfaceName(), m.methodName()))
	sb.WriteString(fmt.Sprintf("\t%14s: %s\n", "first used at", firstUsedAt))
	sb.WriteString(fmt.Sprintf("\t%14s: %s\n\n", "second used at", mockgenCallerLocation(3)))
	sb.WriteString(fmt.Sprintf("\thint: %s.%s is already stubbed, remove one of the above\n\n", m.interfaceName(), m.methodName()))
	return sb.String()
}

func mockgenMessageExpectButNotCalled(m mockgenMockMethod, want int, got int, index int) string {
	sb := &strings.Builder{}
	sb.WriteString(fmt.Sprintf("%s.%s was not called as expected\n", m.interfaceName(), m.methodName()))
	sb.WriteString(fmt.Sprintf("\twant: %d, got: %d\n\n", want, got))
	m.buildCallHistory(sb, "")
	sb.WriteString(fmt.Sprintf("\t#%d never called\n\n", index+1))
	sb.WriteString("\thint: add the missing call or remove the EXPECT above")
	return sb.String()
}

func mockgenMessageMatchArgByNil(m mockgenMockMethod, method string) string {
	sb := &strings.Builder{}
	sb.WriteString(fmt.Sprintf("%s.%s %s received a nil function\n", m.interfaceName(), m.methodName(), method))
	sb.WriteString("\thint: provide a valid function")
	return sb.String()
}

func mockgenMessageDuplicateMatchArg(m mockgenMockMethod, method string, firstUsedAt string) string {
	sb := &strings.Builder{}
	sb.WriteString(fmt.Sprintf("duplicate %s for %s.%s\n", method, m.interfaceName(), m.methodName()))
	sb.WriteString(fmt.Sprintf("\t%14s: %s\n\n", "first used at", firstUsedAt))
	sb.WriteString("\thint: each argument can only be matched once, remove one of the above")
	return sb.String()
}

func mockgenMessageMatchArgHint() string {
	return fmt.Sprintf("\thint: check argument matching at %s\n\t\tor use STUB for fine-grained control", mockgenCallerLocation(3))
}

func mockgenMatchArgument[T any](m mockgenMockMethod, index int, name string, got T, match func(T) bool, wants map[string]any, methods map[string]string, hints map[string]string, tb testing.TB, expectAt string) {
	if match == nil || match(got) {
		return
	}
	tb.Helper()

	method := "func(got) bool"
	if v, ok := methods[name]; ok {
		method = v
	}

	hint := fmt.Sprintf("hint: for custom matching use .Match[arg](func(...) bool) at %s\n\tor use STUB for fine-grained control", expectAt)
	if v, ok := hints[name]; ok {
		hint = v
	}

	sb := &strings.Builder{}
	sb.WriteString(fmt.Sprintf("%s.%s call #%d argument \"%s\" did not match\n", m.interfaceName(), m.methodName(), index+1, name))
	if want, ok := wants[name]; ok {
		sb.WriteString(fmt.Sprintf("  want: %#v\n", want))
	}
	sb.WriteString(fmt.Sprintf("   got: %#v\n", got))
	sb.WriteString(fmt.Sprintf("method: %s\n", method))
	sb.WriteString("\n")
	m.buildCallHistory(sb, "call history")
	sb.WriteString(hint)

	tb.Helper()
	m.fatal(index, sb.String())
}

func mockgenReflectEqualMatcher[T any](want T) func(T) bool {
	return func(got T) bool {
		return reflect.DeepEqual(want, got)
	}
}

func mockgenBasicComparisonMatcher[T comparable](want T) func(T) bool {
	return func(got T) bool {
		return want == got
	}
}

func testStorer() *storer {
	return &storer{td: &storerTestDouble{location: mockgenCallerLocation(2)}}
}

type storerTestDouble struct {
	location   string
	Create     *storerCreate
	Delete     *storerDelete
	GetByID    *storerGetByID
	List       *storerList
	ToggleDone *storerToggleDone
	Update     *storerUpdate
}

type storer struct {
	td *storerTestDouble
}

func (m *storer) STUB() *storerStubber {
	return &storerStubber{target: m}
}

func (m *storer) EXPECT() *storerExpecter {
	return &storerExpecter{target: m}
}

func (m *storer) Create(task Task) (Task, error) {
	v0, v1, v2 := "Storer", "Create", "(task Task) (Task, error)"
	v3 := []any{"task", task}

	if m.td == nil {
		panic(mockgenMessageNotImplemented(v0, v1, v2, "", v3))
	}

	if v4 := m.td.Create; v4 != nil {
		switch {
		case v4.stub != nil:
			return v4.invokeStub(task)
		case len(v4.expects) > 0:
			v5 := len(v4.Calls)
			if v5 < len(v4.expects) {
				v4.expects[v5].tb.Helper()
			}
			return v4.invokeExpect(task)
		}
	}
	panic(mockgenMessageNotImplemented(v0, v1, v2, m.td.location, v3))
}

func (m *storer) Delete(id int) error {
	v0, v1, v2 := "Storer", "Delete", "(id int) error"
	v3 := []any{"id", id}

	if m.td == nil {
		panic(mockgenMessageNotImplemented(v0, v1, v2, "", v3))
	}

	if v4 := m.td.Delete; v4 != nil {
		switch {
		case v4.stub != nil:
			return v4.invokeStub(id)
		case len(v4.expects) > 0:
			v5 := len(v4.Calls)
			if v5 < len(v4.expects) {
				v4.expects[v5].tb.Helper()
			}
			return v4.invokeExpect(id)
		}
	}
	panic(mockgenMessageNotImplemented(v0, v1, v2, m.td.location, v3))
}

func (m *storer) GetByID(id int) (Task, error) {
	v0, v1, v2 := "Storer", "GetByID", "(id int) (Task, error)"
	v3 := []any{"id", id}

	if m.td == nil {
		panic(mockgenMessageNotImplemented(v0, v1, v2, "", v3))
	}

	if v4 := m.td.GetByID; v4 != nil {
		switch {
		case v4.stub != nil:
			return v4.invokeStub(id)
		case len(v4.expects) > 0:
			v5 := len(v4.Calls)
			if v5 < len(v4.expects) {
				v4.expects[v5].tb.Helper()
			}
			return v4.invokeExpect(id)
		}
	}
	panic(mockgenMessageNotImplemented(v0, v1, v2, m.td.location, v3))
}

func (m *storer) List(filter string) ([]Task, error) {
	v0, v1, v2 := "Storer", "List", "(filter string) ([]Task, error)"
	v3 := []any{"filter", filter}

	if m.td == nil {
		panic(mockgenMessageNotImplemented(v0, v1, v2, "", v3))
	}

	if v4 := m.td.List; v4 != nil {
		switch {
		case v4.stub != nil:
			return v4.invokeStub(filter)
		case len(v4.expects) > 0:
			v5 := len(v4.Calls)
			if v5 < len(v4.expects) {
				v4.expects[v5].tb.Helper()
			}
			return v4.invokeExpect(filter)
		}
	}
	panic(mockgenMessageNotImplemented(v0, v1, v2, m.td.location, v3))
}

func (m *storer) ToggleDone(id int) (Task, error) {
	v0, v1, v2 := "Storer", "ToggleDone", "(id int) (Task, error)"
	v3 := []any{"id", id}

	if m.td == nil {
		panic(mockgenMessageNotImplemented(v0, v1, v2, "", v3))
	}

	if v4 := m.td.ToggleDone; v4 != nil {
		switch {
		case v4.stub != nil:
			return v4.invokeStub(id)
		case len(v4.expects) > 0:
			v5 := len(v4.Calls)
			if v5 < len(v4.expects) {
				v4.expects[v5].tb.Helper()
			}
			return v4.invokeExpect(id)
		}
	}
	panic(mockgenMessageNotImplemented(v0, v1, v2, m.td.location, v3))
}

func (m *storer) Update(task Task) (Task, error) {
	v0, v1, v2 := "Storer", "Update", "(task Task) (Task, error)"
	v3 := []any{"task", task}

	if m.td == nil {
		panic(mockgenMessageNotImplemented(v0, v1, v2, "", v3))
	}

	if v4 := m.td.Update; v4 != nil {
		switch {
		case v4.stub != nil:
			return v4.invokeStub(task)
		case len(v4.expects) > 0:
			v5 := len(v4.Calls)
			if v5 < len(v4.expects) {
				v4.expects[v5].tb.Helper()
			}
			return v4.invokeExpect(task)
		}
	}
	panic(mockgenMessageNotImplemented(v0, v1, v2, m.td.location, v3))
}

type storerStubber struct {
	target *storer
}

func (s *storerStubber) Create(stub func(task Task) (Task, error)) *storerCreate {
	if s.target.td == nil {
		s.target.td = &storerTestDouble{}
	}

	m := s.target.td.Create
	if m == nil {
		m = &storerCreate{stubLocation: mockgenCallerLocation(2)}
		s.target.td.Create = m
	}

	if stub == nil {
		m.panic(mockgenMessageStubByNil(m, mockgenCallerLocation(2)))
	}

	if m.stub != nil {
		m.panic(mockgenMessageDuplicateStub(m, m.stubLocation))
	}

	if len(m.expects) > 0 {
		m.panic(mockgenMessageStubAfterExpect(m, m.expects[0].location))
	}

	m.stub = stub
	return m
}

func (s *storerStubber) Delete(stub func(id int) error) *storerDelete {
	if s.target.td == nil {
		s.target.td = &storerTestDouble{}
	}

	m := s.target.td.Delete
	if m == nil {
		m = &storerDelete{stubLocation: mockgenCallerLocation(2)}
		s.target.td.Delete = m
	}

	if stub == nil {
		m.panic(mockgenMessageStubByNil(m, mockgenCallerLocation(2)))
	}

	if m.stub != nil {
		m.panic(mockgenMessageDuplicateStub(m, m.stubLocation))
	}

	if len(m.expects) > 0 {
		m.panic(mockgenMessageStubAfterExpect(m, m.expects[0].location))
	}

	m.stub = stub
	return m
}

func (s *storerStubber) GetByID(stub func(id int) (Task, error)) *storerGetByID {
	if s.target.td == nil {
		s.target.td = &storerTestDouble{}
	}

	m := s.target.td.GetByID
	if m == nil {
		m = &storerGetByID{stubLocation: mockgenCallerLocation(2)}
		s.target.td.GetByID = m
	}

	if stub == nil {
		m.panic(mockgenMessageStubByNil(m, mockgenCallerLocation(2)))
	}

	if m.stub != nil {
		m.panic(mockgenMessageDuplicateStub(m, m.stubLocation))
	}

	if len(m.expects) > 0 {
		m.panic(mockgenMessageStubAfterExpect(m, m.expects[0].location))
	}

	m.stub = stub
	return m
}

func (s *storerStubber) List(stub func(filter string) ([]Task, error)) *storerList {
	if s.target.td == nil {
		s.target.td = &storerTestDouble{}
	}

	m := s.target.td.List
	if m == nil {
		m = &storerList{stubLocation: mockgenCallerLocation(2)}
		s.target.td.List = m
	}

	if stub == nil {
		m.panic(mockgenMessageStubByNil(m, mockgenCallerLocation(2)))
	}

	if m.stub != nil {
		m.panic(mockgenMessageDuplicateStub(m, m.stubLocation))
	}

	if len(m.expects) > 0 {
		m.panic(mockgenMessageStubAfterExpect(m, m.expects[0].location))
	}

	m.stub = stub
	return m
}

func (s *storerStubber) ToggleDone(stub func(id int) (Task, error)) *storerToggleDone {
	if s.target.td == nil {
		s.target.td = &storerTestDouble{}
	}

	m := s.target.td.ToggleDone
	if m == nil {
		m = &storerToggleDone{stubLocation: mockgenCallerLocation(2)}
		s.target.td.ToggleDone = m
	}

	if stub == nil {
		m.panic(mockgenMessageStubByNil(m, mockgenCallerLocation(2)))
	}

	if m.stub != nil {
		m.panic(mockgenMessageDuplicateStub(m, m.stubLocation))
	}

	if len(m.expects) > 0 {
		m.panic(mockgenMessageStubAfterExpect(m, m.expects[0].location))
	}

	m.stub = stub
	return m
}

func (s *storerStubber) Update(stub func(task Task) (Task, error)) *storerUpdate {
	if s.target.td == nil {
		s.target.td = &storerTestDouble{}
	}

	m := s.target.td.Update
	if m == nil {
		m = &storerUpdate{stubLocation: mockgenCallerLocation(2)}
		s.target.td.Update = m
	}

	if stub == nil {
		m.panic(mockgenMessageStubByNil(m, mockgenCallerLocation(2)))
	}

	if m.stub != nil {
		m.panic(mockgenMessageDuplicateStub(m, m.stubLocation))
	}

	if len(m.expects) > 0 {
		m.panic(mockgenMessageStubAfterExpect(m, m.expects[0].location))
	}

	m.stub = stub
	return m
}

type storerExpecter struct {
	target *storer
}

func (e *storerExpecter) Create(tb testing.TB) *storerCreateExpecter {
	if e.target.td == nil {
		e.target.td = &storerTestDouble{}
	}

	var m = e.target.td.Create
	if m == nil {
		m = &storerCreate{}
		e.target.td.Create = m
	}

	if m.stub != nil {
		m.panic(mockgenMessageExpectAfterStub(m, m.stubLocation))
	}

	if tb == nil {
		m.panic(mockgenMessageExpectByNil(m))
	}

	idx := len(m.expects)
	m.expects = append(m.expects, &storerCreateExpect{
		location:         mockgenCallerLocation(2),
		matcher:          &storerCreateArgumentMatcher{},
		matcherWants:     make(map[string]any),
		matcherMethods:   make(map[string]string),
		matcherHints:     make(map[string]string),
		matcherLocations: make(map[string]string),
		index:            idx,
		tb:               tb,
	})

	tb.Helper()
	tb.Cleanup(func() {
		tb.Helper()
		m.verify(idx)
	})

	return &storerCreateExpecter{target: m, expect: m.expects[idx]}
}

func (e *storerExpecter) Delete(tb testing.TB) *storerDeleteExpecter {
	if e.target.td == nil {
		e.target.td = &storerTestDouble{}
	}

	var m = e.target.td.Delete
	if m == nil {
		m = &storerDelete{}
		e.target.td.Delete = m
	}

	if m.stub != nil {
		m.panic(mockgenMessageExpectAfterStub(m, m.stubLocation))
	}

	if tb == nil {
		m.panic(mockgenMessageExpectByNil(m))
	}

	idx := len(m.expects)
	m.expects = append(m.expects, &storerDeleteExpect{
		location:         mockgenCallerLocation(2),
		matcher:          &storerDeleteArgumentMatcher{},
		matcherWants:     make(map[string]any),
		matcherMethods:   make(map[string]string),
		matcherHints:     make(map[string]string),
		matcherLocations: make(map[string]string),
		index:            idx,
		tb:               tb,
	})

	tb.Helper()
	tb.Cleanup(func() {
		tb.Helper()
		m.verify(idx)
	})

	return &storerDeleteExpecter{target: m, expect: m.expects[idx]}
}

func (e *storerExpecter) GetByID(tb testing.TB) *storerGetByIDExpecter {
	if e.target.td == nil {
		e.target.td = &storerTestDouble{}
	}

	var m = e.target.td.GetByID
	if m == nil {
		m = &storerGetByID{}
		e.target.td.GetByID = m
	}

	if m.stub != nil {
		m.panic(mockgenMessageExpectAfterStub(m, m.stubLocation))
	}

	if tb == nil {
		m.panic(mockgenMessageExpectByNil(m))
	}

	idx := len(m.expects)
	m.expects = append(m.expects, &storerGetByIDExpect{
		location:         mockgenCallerLocation(2),
		matcher:          &storerGetByIDArgumentMatcher{},
		matcherWants:     make(map[string]any),
		matcherMethods:   make(map[string]string),
		matcherHints:     make(map[string]string),
		matcherLocations: make(map[string]string),
		index:            idx,
		tb:               tb,
	})

	tb.Helper()
	tb.Cleanup(func() {
		tb.Helper()
		m.verify(idx)
	})

	return &storerGetByIDExpecter{target: m, expect: m.expects[idx]}
}

func (e *storerExpecter) List(tb testing.TB) *storerListExpecter {
	if e.target.td == nil {
		e.target.td = &storerTestDouble{}
	}

	var m = e.target.td.List
	if m == nil {
		m = &storerList{}
		e.target.td.List = m
	}

	if m.stub != nil {
		m.panic(mockgenMessageExpectAfterStub(m, m.stubLocation))
	}

	if tb == nil {
		m.panic(mockgenMessageExpectByNil(m))
	}

	idx := len(m.expects)
	m.expects = append(m.expects, &storerListExpect{
		location:         mockgenCallerLocation(2),
		matcher:          &storerListArgumentMatcher{},
		matcherWants:     make(map[string]any),
		matcherMethods:   make(map[string]string),
		matcherHints:     make(map[string]string),
		matcherLocations: make(map[string]string),
		index:            idx,
		tb:               tb,
	})

	tb.Helper()
	tb.Cleanup(func() {
		tb.Helper()
		m.verify(idx)
	})

	return &storerListExpecter{target: m, expect: m.expects[idx]}
}

func (e *storerExpecter) ToggleDone(tb testing.TB) *storerToggleDoneExpecter {
	if e.target.td == nil {
		e.target.td = &storerTestDouble{}
	}

	var m = e.target.td.ToggleDone
	if m == nil {
		m = &storerToggleDone{}
		e.target.td.ToggleDone = m
	}

	if m.stub != nil {
		m.panic(mockgenMessageExpectAfterStub(m, m.stubLocation))
	}

	if tb == nil {
		m.panic(mockgenMessageExpectByNil(m))
	}

	idx := len(m.expects)
	m.expects = append(m.expects, &storerToggleDoneExpect{
		location:         mockgenCallerLocation(2),
		matcher:          &storerToggleDoneArgumentMatcher{},
		matcherWants:     make(map[string]any),
		matcherMethods:   make(map[string]string),
		matcherHints:     make(map[string]string),
		matcherLocations: make(map[string]string),
		index:            idx,
		tb:               tb,
	})

	tb.Helper()
	tb.Cleanup(func() {
		tb.Helper()
		m.verify(idx)
	})

	return &storerToggleDoneExpecter{target: m, expect: m.expects[idx]}
}

func (e *storerExpecter) Update(tb testing.TB) *storerUpdateExpecter {
	if e.target.td == nil {
		e.target.td = &storerTestDouble{}
	}

	var m = e.target.td.Update
	if m == nil {
		m = &storerUpdate{}
		e.target.td.Update = m
	}

	if m.stub != nil {
		m.panic(mockgenMessageExpectAfterStub(m, m.stubLocation))
	}

	if tb == nil {
		m.panic(mockgenMessageExpectByNil(m))
	}

	idx := len(m.expects)
	m.expects = append(m.expects, &storerUpdateExpect{
		location:         mockgenCallerLocation(2),
		matcher:          &storerUpdateArgumentMatcher{},
		matcherWants:     make(map[string]any),
		matcherMethods:   make(map[string]string),
		matcherHints:     make(map[string]string),
		matcherLocations: make(map[string]string),
		index:            idx,
		tb:               tb,
	})

	tb.Helper()
	tb.Cleanup(func() {
		tb.Helper()
		m.verify(idx)
	})

	return &storerUpdateExpecter{target: m, expect: m.expects[idx]}
}

type storerCreate struct {
	Calls        []storerCreateCall
	stub         func(task Task) (Task, error)
	stubLocation string
	expects      []*storerCreateExpect
	verified     bool
}

func (m *storerCreate) methodName() string {
	return "Create"
}

func (m *storerCreate) interfaceName() string {
	return "Storer"
}

func (m *storerCreate) fatal(index int, msg string) {
	m.verified = true
	m.expects[index].tb.Helper()
	m.expects[index].tb.Fatal(msg)
}

func (m *storerCreate) panic(msg string) {
	m.verified = true
	panic(msg)
}

func (m *storerCreate) buildCallHistory(sb *strings.Builder, header string) {
	if header != "" && len(m.Calls) != 0 {
		sb.WriteString(fmt.Sprintf("%s:\n", header))
	}

	for i, v := range m.Calls {
		a := []any{"task", v.Argument.task}
		mockgenMessageCallHistory(sb, i, m.expects[i].location, v.Location, a)
	}
}

func (m *storerCreate) invokeStub(task Task) (Task, error) {
	v0, v1 := m.stub(task)
	return m.capture(storerCreateArgument{task: task}, storerCreateReturn{first: v0, second: v1})
}

func (m *storerCreate) invokeExpect(task Task) (Task, error) {
	v0 := []any{"task", task}

	v1 := len(m.Calls)
	if v1 >= len(m.expects) {
		m.panic(mockgenMessageTooManyCalls(m, len(m.expects), v1+1, v0))
	}

	v2 := m.expects[v1]
	if v2.match != nil && !v2.match(task) {
		v2.tb.Helper()
		m.fatal(v1, mockgenMessageMatchFail(m, v2.matchLocation, v1, v0))
	}

	v2.tb.Helper()
	mockgenMatchArgument(m, v1, "task", task, v2.matcher.task, v2.matcherWants, v2.matcherMethods, v2.matcherHints, v2.tb, v2.matcherLocations["task"])

	return m.capture(storerCreateArgument{task: task}, v2.returns)
}

func (m *storerCreate) capture(args storerCreateArgument, returns storerCreateReturn) (Task, error) {
	m.Calls = append(m.Calls, storerCreateCall{Location: mockgenCallerLocation(4), Argument: args, Return: returns})
	return returns.first, returns.second
}

func (m *storerCreate) verify(index int) {
	if !m.verified && index >= len(m.Calls) {
		m.expects[index].tb.Helper()
		m.expects[index].tb.Fatal(mockgenMessageExpectButNotCalled(m, len(m.expects), len(m.Calls), index))
	}
}

type storerCreateCall struct {
	Location string
	Argument storerCreateArgument
	Return   storerCreateReturn
}

type storerCreateArgument struct {
	task Task
}

type storerCreateArgumentMatcher struct {
	task func(task Task) bool
}

type storerCreateReturn struct {
	first  Task
	second error
}

type storerCreateExpect struct {
	match            func(task Task) bool
	matchLocation    string
	matcher          *storerCreateArgumentMatcher
	matcherWants     map[string]any
	matcherMethods   map[string]string
	matcherHints     map[string]string
	matcherLocations map[string]string
	returns          storerCreateReturn
	location         string
	index            int
	tb               testing.TB
}

type storerCreateExpecter struct {
	expect *storerCreateExpect
	target *storerCreate
}

func (e *storerCreateExpecter) Return(first Task, second error) {
	e.expect.returns = storerCreateReturn{first: first, second: second}
}

func (e *storerCreateExpecter) Match(matcher func(task Task) bool) *storerCreateExpecterWithMatch {
	if matcher == nil {
		e.expect.tb.Helper()
		e.target.fatal(e.expect.index, mockgenMessageMatchByNil(e.target))
	}

	e.expect.match = matcher
	e.expect.matchLocation = mockgenCallerLocation(2)
	return &storerCreateExpecterWithMatch{expect: e.expect}
}

func (e *storerCreateExpecter) MatchTask(matcher func(task Task) bool) *storerCreateExpecterWithMatchArg {
	if matcher == nil {
		e.expect.tb.Helper()
		e.target.fatal(e.expect.index, mockgenMessageMatchArgByNil(e.target, "MatchTask"))
	}

	e.expect.matcher.task = matcher
	e.expect.matcherLocations["task"] = mockgenCallerLocation(2)
	e.expect.matcherHints["task"] = mockgenMessageMatchArgHint()
	return &storerCreateExpecterWithMatchArg{expect: e.expect, target: e.target}
}

func (e *storerCreateExpecter) With(task Task) *storerCreateExpecterWithValue {
	e.WithTask(task)
	e.expect.matcherLocations["task"] = mockgenCallerLocation(2)

	return &storerCreateExpecterWithValue{expect: e.expect}
}

func (e *storerCreateExpecter) WithTask(task Task) *storerCreateExpecterWithValueArg {
	e.expect.matcher.task = mockgenBasicComparisonMatcher(task)
	e.expect.matcherWants["task"] = task
	e.expect.matcherMethods["task"] = "=="
	e.expect.matcherLocations["task"] = mockgenCallerLocation(2)

	return &storerCreateExpecterWithValueArg{expect: e.expect, target: e.target}
}

type storerCreateExpecterWithMatch struct {
	expect *storerCreateExpect
}

func (e *storerCreateExpecterWithMatch) Return(first Task, second error) {
	e.expect.returns = storerCreateReturn{first: first, second: second}
}

type storerCreateExpecterWithMatchArg struct {
	expect *storerCreateExpect
	target *storerCreate
}

func (e *storerCreateExpecterWithMatchArg) Return(first Task, second error) {
	e.expect.returns = storerCreateReturn{first: first, second: second}
}

func (e *storerCreateExpecterWithMatchArg) MatchTask(matcher func(task Task) bool) *storerCreateExpecterWithMatchArg {
	if matcher == nil {
		e.expect.tb.Helper()
		e.target.fatal(e.expect.index, mockgenMessageMatchArgByNil(e.target, "MatchTask"))
	}

	if e.expect.matcher.task != nil {
		e.expect.tb.Helper()
		e.target.fatal(e.expect.index, mockgenMessageDuplicateMatchArg(e.target, "MatchTask", e.expect.matcherLocations["task"]))
	}

	e.expect.matcher.task = matcher
	e.expect.matcherLocations["task"] = mockgenCallerLocation(2)
	e.expect.matcherHints["task"] = mockgenMessageMatchArgHint()
	return e
}

type storerCreateExpecterWithValue struct {
	expect *storerCreateExpect
}

func (e *storerCreateExpecterWithValue) Return(first Task, second error) {
	e.expect.returns = storerCreateReturn{first: first, second: second}
}

type storerCreateExpecterWithValueArg struct {
	expect *storerCreateExpect
	target *storerCreate
}

func (e *storerCreateExpecterWithValueArg) Return(first Task, second error) {
	e.expect.returns = storerCreateReturn{first: first, second: second}
}

func (e *storerCreateExpecterWithValueArg) WithTask(task Task) *storerCreateExpecterWithValueArg {
	if e.expect.matcher.task != nil {
		e.expect.tb.Helper()
		e.target.fatal(e.expect.index, mockgenMessageDuplicateMatchArg(e.target, "WithTask", e.expect.matcherLocations["task"]))
	}

	e.expect.matcher.task = mockgenBasicComparisonMatcher(task)
	e.expect.matcherWants["task"] = task
	e.expect.matcherMethods["task"] = "=="
	e.expect.matcherLocations["task"] = mockgenCallerLocation(2)

	return e
}

type storerDelete struct {
	Calls        []storerDeleteCall
	stub         func(id int) error
	stubLocation string
	expects      []*storerDeleteExpect
	verified     bool
}

func (m *storerDelete) methodName() string {
	return "Delete"
}

func (m *storerDelete) interfaceName() string {
	return "Storer"
}

func (m *storerDelete) fatal(index int, msg string) {
	m.verified = true
	m.expects[index].tb.Helper()
	m.expects[index].tb.Fatal(msg)
}

func (m *storerDelete) panic(msg string) {
	m.verified = true
	panic(msg)
}

func (m *storerDelete) buildCallHistory(sb *strings.Builder, header string) {
	if header != "" && len(m.Calls) != 0 {
		sb.WriteString(fmt.Sprintf("%s:\n", header))
	}

	for i, v := range m.Calls {
		a := []any{"id", v.Argument.id}
		mockgenMessageCallHistory(sb, i, m.expects[i].location, v.Location, a)
	}
}

func (m *storerDelete) invokeStub(id int) error {
	v0 := m.stub(id)
	return m.capture(storerDeleteArgument{id: id}, storerDeleteReturn{first: v0})
}

func (m *storerDelete) invokeExpect(id int) error {
	v0 := []any{"id", id}

	v1 := len(m.Calls)
	if v1 >= len(m.expects) {
		m.panic(mockgenMessageTooManyCalls(m, len(m.expects), v1+1, v0))
	}

	v2 := m.expects[v1]
	if v2.match != nil && !v2.match(id) {
		v2.tb.Helper()
		m.fatal(v1, mockgenMessageMatchFail(m, v2.matchLocation, v1, v0))
	}

	v2.tb.Helper()
	mockgenMatchArgument(m, v1, "id", id, v2.matcher.id, v2.matcherWants, v2.matcherMethods, v2.matcherHints, v2.tb, v2.matcherLocations["id"])

	return m.capture(storerDeleteArgument{id: id}, v2.returns)
}

func (m *storerDelete) capture(args storerDeleteArgument, returns storerDeleteReturn) error {
	m.Calls = append(m.Calls, storerDeleteCall{Location: mockgenCallerLocation(4), Argument: args, Return: returns})
	return returns.first
}

func (m *storerDelete) verify(index int) {
	if !m.verified && index >= len(m.Calls) {
		m.expects[index].tb.Helper()
		m.expects[index].tb.Fatal(mockgenMessageExpectButNotCalled(m, len(m.expects), len(m.Calls), index))
	}
}

type storerDeleteCall struct {
	Location string
	Argument storerDeleteArgument
	Return   storerDeleteReturn
}

type storerDeleteArgument struct {
	id int
}

type storerDeleteArgumentMatcher struct {
	id func(id int) bool
}

type storerDeleteReturn struct {
	first error
}

type storerDeleteExpect struct {
	match            func(id int) bool
	matchLocation    string
	matcher          *storerDeleteArgumentMatcher
	matcherWants     map[string]any
	matcherMethods   map[string]string
	matcherHints     map[string]string
	matcherLocations map[string]string
	returns          storerDeleteReturn
	location         string
	index            int
	tb               testing.TB
}

type storerDeleteExpecter struct {
	expect *storerDeleteExpect
	target *storerDelete
}

func (e *storerDeleteExpecter) Return(first error) {
	e.expect.returns = storerDeleteReturn{first: first}
}

func (e *storerDeleteExpecter) Match(matcher func(id int) bool) *storerDeleteExpecterWithMatch {
	if matcher == nil {
		e.expect.tb.Helper()
		e.target.fatal(e.expect.index, mockgenMessageMatchByNil(e.target))
	}

	e.expect.match = matcher
	e.expect.matchLocation = mockgenCallerLocation(2)
	return &storerDeleteExpecterWithMatch{expect: e.expect}
}

func (e *storerDeleteExpecter) MatchID(matcher func(id int) bool) *storerDeleteExpecterWithMatchArg {
	if matcher == nil {
		e.expect.tb.Helper()
		e.target.fatal(e.expect.index, mockgenMessageMatchArgByNil(e.target, "MatchID"))
	}

	e.expect.matcher.id = matcher
	e.expect.matcherLocations["id"] = mockgenCallerLocation(2)
	e.expect.matcherHints["id"] = mockgenMessageMatchArgHint()
	return &storerDeleteExpecterWithMatchArg{expect: e.expect, target: e.target}
}

func (e *storerDeleteExpecter) With(id int) *storerDeleteExpecterWithValue {
	e.WithID(id)
	e.expect.matcherLocations["id"] = mockgenCallerLocation(2)

	return &storerDeleteExpecterWithValue{expect: e.expect}
}

func (e *storerDeleteExpecter) WithID(id int) *storerDeleteExpecterWithValueArg {
	e.expect.matcher.id = mockgenBasicComparisonMatcher(id)
	e.expect.matcherWants["id"] = id
	e.expect.matcherMethods["id"] = "=="
	e.expect.matcherLocations["id"] = mockgenCallerLocation(2)

	return &storerDeleteExpecterWithValueArg{expect: e.expect, target: e.target}
}

type storerDeleteExpecterWithMatch struct {
	expect *storerDeleteExpect
}

func (e *storerDeleteExpecterWithMatch) Return(first error) {
	e.expect.returns = storerDeleteReturn{first: first}
}

type storerDeleteExpecterWithMatchArg struct {
	expect *storerDeleteExpect
	target *storerDelete
}

func (e *storerDeleteExpecterWithMatchArg) Return(first error) {
	e.expect.returns = storerDeleteReturn{first: first}
}

func (e *storerDeleteExpecterWithMatchArg) MatchID(matcher func(id int) bool) *storerDeleteExpecterWithMatchArg {
	if matcher == nil {
		e.expect.tb.Helper()
		e.target.fatal(e.expect.index, mockgenMessageMatchArgByNil(e.target, "MatchID"))
	}

	if e.expect.matcher.id != nil {
		e.expect.tb.Helper()
		e.target.fatal(e.expect.index, mockgenMessageDuplicateMatchArg(e.target, "MatchID", e.expect.matcherLocations["id"]))
	}

	e.expect.matcher.id = matcher
	e.expect.matcherLocations["id"] = mockgenCallerLocation(2)
	e.expect.matcherHints["id"] = mockgenMessageMatchArgHint()
	return e
}

type storerDeleteExpecterWithValue struct {
	expect *storerDeleteExpect
}

func (e *storerDeleteExpecterWithValue) Return(first error) {
	e.expect.returns = storerDeleteReturn{first: first}
}

type storerDeleteExpecterWithValueArg struct {
	expect *storerDeleteExpect
	target *storerDelete
}

func (e *storerDeleteExpecterWithValueArg) Return(first error) {
	e.expect.returns = storerDeleteReturn{first: first}
}

func (e *storerDeleteExpecterWithValueArg) WithID(id int) *storerDeleteExpecterWithValueArg {
	if e.expect.matcher.id != nil {
		e.expect.tb.Helper()
		e.target.fatal(e.expect.index, mockgenMessageDuplicateMatchArg(e.target, "WithID", e.expect.matcherLocations["id"]))
	}

	e.expect.matcher.id = mockgenBasicComparisonMatcher(id)
	e.expect.matcherWants["id"] = id
	e.expect.matcherMethods["id"] = "=="
	e.expect.matcherLocations["id"] = mockgenCallerLocation(2)

	return e
}

type storerGetByID struct {
	Calls        []storerGetByIDCall
	stub         func(id int) (Task, error)
	stubLocation string
	expects      []*storerGetByIDExpect
	verified     bool
}

func (m *storerGetByID) methodName() string {
	return "GetByID"
}

func (m *storerGetByID) interfaceName() string {
	return "Storer"
}

func (m *storerGetByID) fatal(index int, msg string) {
	m.verified = true
	m.expects[index].tb.Helper()
	m.expects[index].tb.Fatal(msg)
}

func (m *storerGetByID) panic(msg string) {
	m.verified = true
	panic(msg)
}

func (m *storerGetByID) buildCallHistory(sb *strings.Builder, header string) {
	if header != "" && len(m.Calls) != 0 {
		sb.WriteString(fmt.Sprintf("%s:\n", header))
	}

	for i, v := range m.Calls {
		a := []any{"id", v.Argument.id}
		mockgenMessageCallHistory(sb, i, m.expects[i].location, v.Location, a)
	}
}

func (m *storerGetByID) invokeStub(id int) (Task, error) {
	v0, v1 := m.stub(id)
	return m.capture(storerGetByIDArgument{id: id}, storerGetByIDReturn{first: v0, second: v1})
}

func (m *storerGetByID) invokeExpect(id int) (Task, error) {
	v0 := []any{"id", id}

	v1 := len(m.Calls)
	if v1 >= len(m.expects) {
		m.panic(mockgenMessageTooManyCalls(m, len(m.expects), v1+1, v0))
	}

	v2 := m.expects[v1]
	if v2.match != nil && !v2.match(id) {
		v2.tb.Helper()
		m.fatal(v1, mockgenMessageMatchFail(m, v2.matchLocation, v1, v0))
	}

	v2.tb.Helper()
	mockgenMatchArgument(m, v1, "id", id, v2.matcher.id, v2.matcherWants, v2.matcherMethods, v2.matcherHints, v2.tb, v2.matcherLocations["id"])

	return m.capture(storerGetByIDArgument{id: id}, v2.returns)
}

func (m *storerGetByID) capture(args storerGetByIDArgument, returns storerGetByIDReturn) (Task, error) {
	m.Calls = append(m.Calls, storerGetByIDCall{Location: mockgenCallerLocation(4), Argument: args, Return: returns})
	return returns.first, returns.second
}

func (m *storerGetByID) verify(index int) {
	if !m.verified && index >= len(m.Calls) {
		m.expects[index].tb.Helper()
		m.expects[index].tb.Fatal(mockgenMessageExpectButNotCalled(m, len(m.expects), len(m.Calls), index))
	}
}

type storerGetByIDCall struct {
	Location string
	Argument storerGetByIDArgument
	Return   storerGetByIDReturn
}

type storerGetByIDArgument struct {
	id int
}

type storerGetByIDArgumentMatcher struct {
	id func(id int) bool
}

type storerGetByIDReturn struct {
	first  Task
	second error
}

type storerGetByIDExpect struct {
	match            func(id int) bool
	matchLocation    string
	matcher          *storerGetByIDArgumentMatcher
	matcherWants     map[string]any
	matcherMethods   map[string]string
	matcherHints     map[string]string
	matcherLocations map[string]string
	returns          storerGetByIDReturn
	location         string
	index            int
	tb               testing.TB
}

type storerGetByIDExpecter struct {
	expect *storerGetByIDExpect
	target *storerGetByID
}

func (e *storerGetByIDExpecter) Return(first Task, second error) {
	e.expect.returns = storerGetByIDReturn{first: first, second: second}
}

func (e *storerGetByIDExpecter) Match(matcher func(id int) bool) *storerGetByIDExpecterWithMatch {
	if matcher == nil {
		e.expect.tb.Helper()
		e.target.fatal(e.expect.index, mockgenMessageMatchByNil(e.target))
	}

	e.expect.match = matcher
	e.expect.matchLocation = mockgenCallerLocation(2)
	return &storerGetByIDExpecterWithMatch{expect: e.expect}
}

func (e *storerGetByIDExpecter) MatchID(matcher func(id int) bool) *storerGetByIDExpecterWithMatchArg {
	if matcher == nil {
		e.expect.tb.Helper()
		e.target.fatal(e.expect.index, mockgenMessageMatchArgByNil(e.target, "MatchID"))
	}

	e.expect.matcher.id = matcher
	e.expect.matcherLocations["id"] = mockgenCallerLocation(2)
	e.expect.matcherHints["id"] = mockgenMessageMatchArgHint()
	return &storerGetByIDExpecterWithMatchArg{expect: e.expect, target: e.target}
}

func (e *storerGetByIDExpecter) With(id int) *storerGetByIDExpecterWithValue {
	e.WithID(id)
	e.expect.matcherLocations["id"] = mockgenCallerLocation(2)

	return &storerGetByIDExpecterWithValue{expect: e.expect}
}

func (e *storerGetByIDExpecter) WithID(id int) *storerGetByIDExpecterWithValueArg {
	e.expect.matcher.id = mockgenBasicComparisonMatcher(id)
	e.expect.matcherWants["id"] = id
	e.expect.matcherMethods["id"] = "=="
	e.expect.matcherLocations["id"] = mockgenCallerLocation(2)

	return &storerGetByIDExpecterWithValueArg{expect: e.expect, target: e.target}
}

type storerGetByIDExpecterWithMatch struct {
	expect *storerGetByIDExpect
}

func (e *storerGetByIDExpecterWithMatch) Return(first Task, second error) {
	e.expect.returns = storerGetByIDReturn{first: first, second: second}
}

type storerGetByIDExpecterWithMatchArg struct {
	expect *storerGetByIDExpect
	target *storerGetByID
}

func (e *storerGetByIDExpecterWithMatchArg) Return(first Task, second error) {
	e.expect.returns = storerGetByIDReturn{first: first, second: second}
}

func (e *storerGetByIDExpecterWithMatchArg) MatchID(matcher func(id int) bool) *storerGetByIDExpecterWithMatchArg {
	if matcher == nil {
		e.expect.tb.Helper()
		e.target.fatal(e.expect.index, mockgenMessageMatchArgByNil(e.target, "MatchID"))
	}

	if e.expect.matcher.id != nil {
		e.expect.tb.Helper()
		e.target.fatal(e.expect.index, mockgenMessageDuplicateMatchArg(e.target, "MatchID", e.expect.matcherLocations["id"]))
	}

	e.expect.matcher.id = matcher
	e.expect.matcherLocations["id"] = mockgenCallerLocation(2)
	e.expect.matcherHints["id"] = mockgenMessageMatchArgHint()
	return e
}

type storerGetByIDExpecterWithValue struct {
	expect *storerGetByIDExpect
}

func (e *storerGetByIDExpecterWithValue) Return(first Task, second error) {
	e.expect.returns = storerGetByIDReturn{first: first, second: second}
}

type storerGetByIDExpecterWithValueArg struct {
	expect *storerGetByIDExpect
	target *storerGetByID
}

func (e *storerGetByIDExpecterWithValueArg) Return(first Task, second error) {
	e.expect.returns = storerGetByIDReturn{first: first, second: second}
}

func (e *storerGetByIDExpecterWithValueArg) WithID(id int) *storerGetByIDExpecterWithValueArg {
	if e.expect.matcher.id != nil {
		e.expect.tb.Helper()
		e.target.fatal(e.expect.index, mockgenMessageDuplicateMatchArg(e.target, "WithID", e.expect.matcherLocations["id"]))
	}

	e.expect.matcher.id = mockgenBasicComparisonMatcher(id)
	e.expect.matcherWants["id"] = id
	e.expect.matcherMethods["id"] = "=="
	e.expect.matcherLocations["id"] = mockgenCallerLocation(2)

	return e
}

type storerList struct {
	Calls        []storerListCall
	stub         func(filter string) ([]Task, error)
	stubLocation string
	expects      []*storerListExpect
	verified     bool
}

func (m *storerList) methodName() string {
	return "List"
}

func (m *storerList) interfaceName() string {
	return "Storer"
}

func (m *storerList) fatal(index int, msg string) {
	m.verified = true
	m.expects[index].tb.Helper()
	m.expects[index].tb.Fatal(msg)
}

func (m *storerList) panic(msg string) {
	m.verified = true
	panic(msg)
}

func (m *storerList) buildCallHistory(sb *strings.Builder, header string) {
	if header != "" && len(m.Calls) != 0 {
		sb.WriteString(fmt.Sprintf("%s:\n", header))
	}

	for i, v := range m.Calls {
		a := []any{"filter", v.Argument.filter}
		mockgenMessageCallHistory(sb, i, m.expects[i].location, v.Location, a)
	}
}

func (m *storerList) invokeStub(filter string) ([]Task, error) {
	v0, v1 := m.stub(filter)
	return m.capture(storerListArgument{filter: filter}, storerListReturn{first: v0, second: v1})
}

func (m *storerList) invokeExpect(filter string) ([]Task, error) {
	v0 := []any{"filter", filter}

	v1 := len(m.Calls)
	if v1 >= len(m.expects) {
		m.panic(mockgenMessageTooManyCalls(m, len(m.expects), v1+1, v0))
	}

	v2 := m.expects[v1]
	if v2.match != nil && !v2.match(filter) {
		v2.tb.Helper()
		m.fatal(v1, mockgenMessageMatchFail(m, v2.matchLocation, v1, v0))
	}

	v2.tb.Helper()
	mockgenMatchArgument(m, v1, "filter", filter, v2.matcher.filter, v2.matcherWants, v2.matcherMethods, v2.matcherHints, v2.tb, v2.matcherLocations["filter"])

	return m.capture(storerListArgument{filter: filter}, v2.returns)
}

func (m *storerList) capture(args storerListArgument, returns storerListReturn) ([]Task, error) {
	m.Calls = append(m.Calls, storerListCall{Location: mockgenCallerLocation(4), Argument: args, Return: returns})
	return returns.first, returns.second
}

func (m *storerList) verify(index int) {
	if !m.verified && index >= len(m.Calls) {
		m.expects[index].tb.Helper()
		m.expects[index].tb.Fatal(mockgenMessageExpectButNotCalled(m, len(m.expects), len(m.Calls), index))
	}
}

type storerListCall struct {
	Location string
	Argument storerListArgument
	Return   storerListReturn
}

type storerListArgument struct {
	filter string
}

type storerListArgumentMatcher struct {
	filter func(filter string) bool
}

type storerListReturn struct {
	first  []Task
	second error
}

type storerListExpect struct {
	match            func(filter string) bool
	matchLocation    string
	matcher          *storerListArgumentMatcher
	matcherWants     map[string]any
	matcherMethods   map[string]string
	matcherHints     map[string]string
	matcherLocations map[string]string
	returns          storerListReturn
	location         string
	index            int
	tb               testing.TB
}

type storerListExpecter struct {
	expect *storerListExpect
	target *storerList
}

func (e *storerListExpecter) Return(first []Task, second error) {
	e.expect.returns = storerListReturn{first: first, second: second}
}

func (e *storerListExpecter) Match(matcher func(filter string) bool) *storerListExpecterWithMatch {
	if matcher == nil {
		e.expect.tb.Helper()
		e.target.fatal(e.expect.index, mockgenMessageMatchByNil(e.target))
	}

	e.expect.match = matcher
	e.expect.matchLocation = mockgenCallerLocation(2)
	return &storerListExpecterWithMatch{expect: e.expect}
}

func (e *storerListExpecter) MatchFilter(matcher func(filter string) bool) *storerListExpecterWithMatchArg {
	if matcher == nil {
		e.expect.tb.Helper()
		e.target.fatal(e.expect.index, mockgenMessageMatchArgByNil(e.target, "MatchFilter"))
	}

	e.expect.matcher.filter = matcher
	e.expect.matcherLocations["filter"] = mockgenCallerLocation(2)
	e.expect.matcherHints["filter"] = mockgenMessageMatchArgHint()
	return &storerListExpecterWithMatchArg{expect: e.expect, target: e.target}
}

func (e *storerListExpecter) With(filter string) *storerListExpecterWithValue {
	e.WithFilter(filter)
	e.expect.matcherLocations["filter"] = mockgenCallerLocation(2)

	return &storerListExpecterWithValue{expect: e.expect}
}

func (e *storerListExpecter) WithFilter(filter string) *storerListExpecterWithValueArg {
	e.expect.matcher.filter = mockgenBasicComparisonMatcher(filter)
	e.expect.matcherWants["filter"] = filter
	e.expect.matcherMethods["filter"] = "=="
	e.expect.matcherLocations["filter"] = mockgenCallerLocation(2)

	return &storerListExpecterWithValueArg{expect: e.expect, target: e.target}
}

type storerListExpecterWithMatch struct {
	expect *storerListExpect
}

func (e *storerListExpecterWithMatch) Return(first []Task, second error) {
	e.expect.returns = storerListReturn{first: first, second: second}
}

type storerListExpecterWithMatchArg struct {
	expect *storerListExpect
	target *storerList
}

func (e *storerListExpecterWithMatchArg) Return(first []Task, second error) {
	e.expect.returns = storerListReturn{first: first, second: second}
}

func (e *storerListExpecterWithMatchArg) MatchFilter(matcher func(filter string) bool) *storerListExpecterWithMatchArg {
	if matcher == nil {
		e.expect.tb.Helper()
		e.target.fatal(e.expect.index, mockgenMessageMatchArgByNil(e.target, "MatchFilter"))
	}

	if e.expect.matcher.filter != nil {
		e.expect.tb.Helper()
		e.target.fatal(e.expect.index, mockgenMessageDuplicateMatchArg(e.target, "MatchFilter", e.expect.matcherLocations["filter"]))
	}

	e.expect.matcher.filter = matcher
	e.expect.matcherLocations["filter"] = mockgenCallerLocation(2)
	e.expect.matcherHints["filter"] = mockgenMessageMatchArgHint()
	return e
}

type storerListExpecterWithValue struct {
	expect *storerListExpect
}

func (e *storerListExpecterWithValue) Return(first []Task, second error) {
	e.expect.returns = storerListReturn{first: first, second: second}
}

type storerListExpecterWithValueArg struct {
	expect *storerListExpect
	target *storerList
}

func (e *storerListExpecterWithValueArg) Return(first []Task, second error) {
	e.expect.returns = storerListReturn{first: first, second: second}
}

func (e *storerListExpecterWithValueArg) WithFilter(filter string) *storerListExpecterWithValueArg {
	if e.expect.matcher.filter != nil {
		e.expect.tb.Helper()
		e.target.fatal(e.expect.index, mockgenMessageDuplicateMatchArg(e.target, "WithFilter", e.expect.matcherLocations["filter"]))
	}

	e.expect.matcher.filter = mockgenBasicComparisonMatcher(filter)
	e.expect.matcherWants["filter"] = filter
	e.expect.matcherMethods["filter"] = "=="
	e.expect.matcherLocations["filter"] = mockgenCallerLocation(2)

	return e
}

type storerToggleDone struct {
	Calls        []storerToggleDoneCall
	stub         func(id int) (Task, error)
	stubLocation string
	expects      []*storerToggleDoneExpect
	verified     bool
}

func (m *storerToggleDone) methodName() string {
	return "ToggleDone"
}

func (m *storerToggleDone) interfaceName() string {
	return "Storer"
}

func (m *storerToggleDone) fatal(index int, msg string) {
	m.verified = true
	m.expects[index].tb.Helper()
	m.expects[index].tb.Fatal(msg)
}

func (m *storerToggleDone) panic(msg string) {
	m.verified = true
	panic(msg)
}

func (m *storerToggleDone) buildCallHistory(sb *strings.Builder, header string) {
	if header != "" && len(m.Calls) != 0 {
		sb.WriteString(fmt.Sprintf("%s:\n", header))
	}

	for i, v := range m.Calls {
		a := []any{"id", v.Argument.id}
		mockgenMessageCallHistory(sb, i, m.expects[i].location, v.Location, a)
	}
}

func (m *storerToggleDone) invokeStub(id int) (Task, error) {
	v0, v1 := m.stub(id)
	return m.capture(storerToggleDoneArgument{id: id}, storerToggleDoneReturn{first: v0, second: v1})
}

func (m *storerToggleDone) invokeExpect(id int) (Task, error) {
	v0 := []any{"id", id}

	v1 := len(m.Calls)
	if v1 >= len(m.expects) {
		m.panic(mockgenMessageTooManyCalls(m, len(m.expects), v1+1, v0))
	}

	v2 := m.expects[v1]
	if v2.match != nil && !v2.match(id) {
		v2.tb.Helper()
		m.fatal(v1, mockgenMessageMatchFail(m, v2.matchLocation, v1, v0))
	}

	v2.tb.Helper()
	mockgenMatchArgument(m, v1, "id", id, v2.matcher.id, v2.matcherWants, v2.matcherMethods, v2.matcherHints, v2.tb, v2.matcherLocations["id"])

	return m.capture(storerToggleDoneArgument{id: id}, v2.returns)
}

func (m *storerToggleDone) capture(args storerToggleDoneArgument, returns storerToggleDoneReturn) (Task, error) {
	m.Calls = append(m.Calls, storerToggleDoneCall{Location: mockgenCallerLocation(4), Argument: args, Return: returns})
	return returns.first, returns.second
}

func (m *storerToggleDone) verify(index int) {
	if !m.verified && index >= len(m.Calls) {
		m.expects[index].tb.Helper()
		m.expects[index].tb.Fatal(mockgenMessageExpectButNotCalled(m, len(m.expects), len(m.Calls), index))
	}
}

type storerToggleDoneCall struct {
	Location string
	Argument storerToggleDoneArgument
	Return   storerToggleDoneReturn
}

type storerToggleDoneArgument struct {
	id int
}

type storerToggleDoneArgumentMatcher struct {
	id func(id int) bool
}

type storerToggleDoneReturn struct {
	first  Task
	second error
}

type storerToggleDoneExpect struct {
	match            func(id int) bool
	matchLocation    string
	matcher          *storerToggleDoneArgumentMatcher
	matcherWants     map[string]any
	matcherMethods   map[string]string
	matcherHints     map[string]string
	matcherLocations map[string]string
	returns          storerToggleDoneReturn
	location         string
	index            int
	tb               testing.TB
}

type storerToggleDoneExpecter struct {
	expect *storerToggleDoneExpect
	target *storerToggleDone
}

func (e *storerToggleDoneExpecter) Return(first Task, second error) {
	e.expect.returns = storerToggleDoneReturn{first: first, second: second}
}

func (e *storerToggleDoneExpecter) Match(matcher func(id int) bool) *storerToggleDoneExpecterWithMatch {
	if matcher == nil {
		e.expect.tb.Helper()
		e.target.fatal(e.expect.index, mockgenMessageMatchByNil(e.target))
	}

	e.expect.match = matcher
	e.expect.matchLocation = mockgenCallerLocation(2)
	return &storerToggleDoneExpecterWithMatch{expect: e.expect}
}

func (e *storerToggleDoneExpecter) MatchID(matcher func(id int) bool) *storerToggleDoneExpecterWithMatchArg {
	if matcher == nil {
		e.expect.tb.Helper()
		e.target.fatal(e.expect.index, mockgenMessageMatchArgByNil(e.target, "MatchID"))
	}

	e.expect.matcher.id = matcher
	e.expect.matcherLocations["id"] = mockgenCallerLocation(2)
	e.expect.matcherHints["id"] = mockgenMessageMatchArgHint()
	return &storerToggleDoneExpecterWithMatchArg{expect: e.expect, target: e.target}
}

func (e *storerToggleDoneExpecter) With(id int) *storerToggleDoneExpecterWithValue {
	e.WithID(id)
	e.expect.matcherLocations["id"] = mockgenCallerLocation(2)

	return &storerToggleDoneExpecterWithValue{expect: e.expect}
}

func (e *storerToggleDoneExpecter) WithID(id int) *storerToggleDoneExpecterWithValueArg {
	e.expect.matcher.id = mockgenBasicComparisonMatcher(id)
	e.expect.matcherWants["id"] = id
	e.expect.matcherMethods["id"] = "=="
	e.expect.matcherLocations["id"] = mockgenCallerLocation(2)

	return &storerToggleDoneExpecterWithValueArg{expect: e.expect, target: e.target}
}

type storerToggleDoneExpecterWithMatch struct {
	expect *storerToggleDoneExpect
}

func (e *storerToggleDoneExpecterWithMatch) Return(first Task, second error) {
	e.expect.returns = storerToggleDoneReturn{first: first, second: second}
}

type storerToggleDoneExpecterWithMatchArg struct {
	expect *storerToggleDoneExpect
	target *storerToggleDone
}

func (e *storerToggleDoneExpecterWithMatchArg) Return(first Task, second error) {
	e.expect.returns = storerToggleDoneReturn{first: first, second: second}
}

func (e *storerToggleDoneExpecterWithMatchArg) MatchID(matcher func(id int) bool) *storerToggleDoneExpecterWithMatchArg {
	if matcher == nil {
		e.expect.tb.Helper()
		e.target.fatal(e.expect.index, mockgenMessageMatchArgByNil(e.target, "MatchID"))
	}

	if e.expect.matcher.id != nil {
		e.expect.tb.Helper()
		e.target.fatal(e.expect.index, mockgenMessageDuplicateMatchArg(e.target, "MatchID", e.expect.matcherLocations["id"]))
	}

	e.expect.matcher.id = matcher
	e.expect.matcherLocations["id"] = mockgenCallerLocation(2)
	e.expect.matcherHints["id"] = mockgenMessageMatchArgHint()
	return e
}

type storerToggleDoneExpecterWithValue struct {
	expect *storerToggleDoneExpect
}

func (e *storerToggleDoneExpecterWithValue) Return(first Task, second error) {
	e.expect.returns = storerToggleDoneReturn{first: first, second: second}
}

type storerToggleDoneExpecterWithValueArg struct {
	expect *storerToggleDoneExpect
	target *storerToggleDone
}

func (e *storerToggleDoneExpecterWithValueArg) Return(first Task, second error) {
	e.expect.returns = storerToggleDoneReturn{first: first, second: second}
}

func (e *storerToggleDoneExpecterWithValueArg) WithID(id int) *storerToggleDoneExpecterWithValueArg {
	if e.expect.matcher.id != nil {
		e.expect.tb.Helper()
		e.target.fatal(e.expect.index, mockgenMessageDuplicateMatchArg(e.target, "WithID", e.expect.matcherLocations["id"]))
	}

	e.expect.matcher.id = mockgenBasicComparisonMatcher(id)
	e.expect.matcherWants["id"] = id
	e.expect.matcherMethods["id"] = "=="
	e.expect.matcherLocations["id"] = mockgenCallerLocation(2)

	return e
}

type storerUpdate struct {
	Calls        []storerUpdateCall
	stub         func(task Task) (Task, error)
	stubLocation string
	expects      []*storerUpdateExpect
	verified     bool
}

func (m *storerUpdate) methodName() string {
	return "Update"
}

func (m *storerUpdate) interfaceName() string {
	return "Storer"
}

func (m *storerUpdate) fatal(index int, msg string) {
	m.verified = true
	m.expects[index].tb.Helper()
	m.expects[index].tb.Fatal(msg)
}

func (m *storerUpdate) panic(msg string) {
	m.verified = true
	panic(msg)
}

func (m *storerUpdate) buildCallHistory(sb *strings.Builder, header string) {
	if header != "" && len(m.Calls) != 0 {
		sb.WriteString(fmt.Sprintf("%s:\n", header))
	}

	for i, v := range m.Calls {
		a := []any{"task", v.Argument.task}
		mockgenMessageCallHistory(sb, i, m.expects[i].location, v.Location, a)
	}
}

func (m *storerUpdate) invokeStub(task Task) (Task, error) {
	v0, v1 := m.stub(task)
	return m.capture(storerUpdateArgument{task: task}, storerUpdateReturn{first: v0, second: v1})
}

func (m *storerUpdate) invokeExpect(task Task) (Task, error) {
	v0 := []any{"task", task}

	v1 := len(m.Calls)
	if v1 >= len(m.expects) {
		m.panic(mockgenMessageTooManyCalls(m, len(m.expects), v1+1, v0))
	}

	v2 := m.expects[v1]
	if v2.match != nil && !v2.match(task) {
		v2.tb.Helper()
		m.fatal(v1, mockgenMessageMatchFail(m, v2.matchLocation, v1, v0))
	}

	v2.tb.Helper()
	mockgenMatchArgument(m, v1, "task", task, v2.matcher.task, v2.matcherWants, v2.matcherMethods, v2.matcherHints, v2.tb, v2.matcherLocations["task"])

	return m.capture(storerUpdateArgument{task: task}, v2.returns)
}

func (m *storerUpdate) capture(args storerUpdateArgument, returns storerUpdateReturn) (Task, error) {
	m.Calls = append(m.Calls, storerUpdateCall{Location: mockgenCallerLocation(4), Argument: args, Return: returns})
	return returns.first, returns.second
}

func (m *storerUpdate) verify(index int) {
	if !m.verified && index >= len(m.Calls) {
		m.expects[index].tb.Helper()
		m.expects[index].tb.Fatal(mockgenMessageExpectButNotCalled(m, len(m.expects), len(m.Calls), index))
	}
}

type storerUpdateCall struct {
	Location string
	Argument storerUpdateArgument
	Return   storerUpdateReturn
}

type storerUpdateArgument struct {
	task Task
}

type storerUpdateArgumentMatcher struct {
	task func(task Task) bool
}

type storerUpdateReturn struct {
	first  Task
	second error
}

type storerUpdateExpect struct {
	match            func(task Task) bool
	matchLocation    string
	matcher          *storerUpdateArgumentMatcher
	matcherWants     map[string]any
	matcherMethods   map[string]string
	matcherHints     map[string]string
	matcherLocations map[string]string
	returns          storerUpdateReturn
	location         string
	index            int
	tb               testing.TB
}

type storerUpdateExpecter struct {
	expect *storerUpdateExpect
	target *storerUpdate
}

func (e *storerUpdateExpecter) Return(first Task, second error) {
	e.expect.returns = storerUpdateReturn{first: first, second: second}
}

func (e *storerUpdateExpecter) Match(matcher func(task Task) bool) *storerUpdateExpecterWithMatch {
	if matcher == nil {
		e.expect.tb.Helper()
		e.target.fatal(e.expect.index, mockgenMessageMatchByNil(e.target))
	}

	e.expect.match = matcher
	e.expect.matchLocation = mockgenCallerLocation(2)
	return &storerUpdateExpecterWithMatch{expect: e.expect}
}

func (e *storerUpdateExpecter) MatchTask(matcher func(task Task) bool) *storerUpdateExpecterWithMatchArg {
	if matcher == nil {
		e.expect.tb.Helper()
		e.target.fatal(e.expect.index, mockgenMessageMatchArgByNil(e.target, "MatchTask"))
	}

	e.expect.matcher.task = matcher
	e.expect.matcherLocations["task"] = mockgenCallerLocation(2)
	e.expect.matcherHints["task"] = mockgenMessageMatchArgHint()
	return &storerUpdateExpecterWithMatchArg{expect: e.expect, target: e.target}
}

func (e *storerUpdateExpecter) With(task Task) *storerUpdateExpecterWithValue {
	e.WithTask(task)
	e.expect.matcherLocations["task"] = mockgenCallerLocation(2)

	return &storerUpdateExpecterWithValue{expect: e.expect}
}

func (e *storerUpdateExpecter) WithTask(task Task) *storerUpdateExpecterWithValueArg {
	e.expect.matcher.task = mockgenBasicComparisonMatcher(task)
	e.expect.matcherWants["task"] = task
	e.expect.matcherMethods["task"] = "=="
	e.expect.matcherLocations["task"] = mockgenCallerLocation(2)

	return &storerUpdateExpecterWithValueArg{expect: e.expect, target: e.target}
}

type storerUpdateExpecterWithMatch struct {
	expect *storerUpdateExpect
}

func (e *storerUpdateExpecterWithMatch) Return(first Task, second error) {
	e.expect.returns = storerUpdateReturn{first: first, second: second}
}

type storerUpdateExpecterWithMatchArg struct {
	expect *storerUpdateExpect
	target *storerUpdate
}

func (e *storerUpdateExpecterWithMatchArg) Return(first Task, second error) {
	e.expect.returns = storerUpdateReturn{first: first, second: second}
}

func (e *storerUpdateExpecterWithMatchArg) MatchTask(matcher func(task Task) bool) *storerUpdateExpecterWithMatchArg {
	if matcher == nil {
		e.expect.tb.Helper()
		e.target.fatal(e.expect.index, mockgenMessageMatchArgByNil(e.target, "MatchTask"))
	}

	if e.expect.matcher.task != nil {
		e.expect.tb.Helper()
		e.target.fatal(e.expect.index, mockgenMessageDuplicateMatchArg(e.target, "MatchTask", e.expect.matcherLocations["task"]))
	}

	e.expect.matcher.task = matcher
	e.expect.matcherLocations["task"] = mockgenCallerLocation(2)
	e.expect.matcherHints["task"] = mockgenMessageMatchArgHint()
	return e
}

type storerUpdateExpecterWithValue struct {
	expect *storerUpdateExpect
}

func (e *storerUpdateExpecterWithValue) Return(first Task, second error) {
	e.expect.returns = storerUpdateReturn{first: first, second: second}
}

type storerUpdateExpecterWithValueArg struct {
	expect *storerUpdateExpect
	target *storerUpdate
}

func (e *storerUpdateExpecterWithValueArg) Return(first Task, second error) {
	e.expect.returns = storerUpdateReturn{first: first, second: second}
}

func (e *storerUpdateExpecterWithValueArg) WithTask(task Task) *storerUpdateExpecterWithValueArg {
	if e.expect.matcher.task != nil {
		e.expect.tb.Helper()
		e.target.fatal(e.expect.index, mockgenMessageDuplicateMatchArg(e.target, "WithTask", e.expect.matcherLocations["task"]))
	}

	e.expect.matcher.task = mockgenBasicComparisonMatcher(task)
	e.expect.matcherWants["task"] = task
	e.expect.matcherMethods["task"] = "=="
	e.expect.matcherLocations["task"] = mockgenCallerLocation(2)

	return e
}
