// Code generated by nhatp.com/go/mock-gen/cmd/go-mock-gen - v1.0.0. DO NOT EDIT.

package todo

import (
	"fmt"
	"path/filepath"
	"reflect"
	"runtime"
	"strconv"
	"strings"
	"testing"
)

func mockgenCallerLocation(skip int) string {
	_, file, line, _ := runtime.Caller(skip)
	return fmt.Sprintf("%s:%d", filepath.Base(file), line)
}

type mockgenMockMethod interface {
	methodName() string
	interfaceName() string
	buildCallHistory(sb *strings.Builder, header string)
	fatal(index int, msg string)
	panic(msg string)
}

func mockgenMessageWriteArguments(sb *strings.Builder, template string, args []any) {
	maxLen := 0
	for i := 0; i < len(args); i += 2 {
		str, ok := args[i].(string)
		if !ok {
			str = fmt.Sprintf("%v", args[i])
		}
		maxLen = max(maxLen, len(str))
	}

	format := strings.ReplaceAll(template, "[MAX-KEY-LEN]", strconv.Itoa(maxLen))
	for i := 0; i < len(args); i += 2 {
		key, ok := args[i].(string)
		if !ok {
			key = fmt.Sprintf("%v", args[i])
		}

		var val any
		if i+1 < len(args) {
			val = args[i+1]
		}
		sb.WriteString(fmt.Sprintf(format, key, val))
	}
}

func mockgenMessageMatchFail(m mockgenMockMethod, matchedAt string, index int, args []any) string {
	sb := &strings.Builder{}
	sb.WriteString(fmt.Sprintf("%s.%s call #%d did not match\n", m.interfaceName(), m.methodName(), index+1))
	sb.WriteString(fmt.Sprintf("arguments:\n"))
	mockgenMessageWriteArguments(sb, "\t%[MAX-KEY-LEN]s = %#v\n", args)
	sb.WriteString("\n")
	m.buildCallHistory(sb, "call history")
	sb.WriteString(fmt.Sprintf("hint: check the callback passed to Match at %s", matchedAt))
	return sb.String()
}

func mockgenMessageNotImplemented(interfaceName string, methodName string, signature string, createdLocation string, args []any) string {
	sb := &strings.Builder{}
	sb.WriteString(fmt.Sprintf("unexpected call to %s.%s\n", interfaceName, methodName))
	sb.WriteString(fmt.Sprintf("signature: %s.%s%s\n", interfaceName, methodName, signature))
	sb.WriteString(fmt.Sprintf("called at: %s\n", mockgenCallerLocation(3)))
	sb.WriteString("arguments:\n")
	mockgenMessageWriteArguments(sb, "\t%[MAX-KEY-LEN]s = %#v\n", args)

	location := ""
	if createdLocation != "" {
		location = " after " + createdLocation
	}
	sb.WriteString(fmt.Sprintf("\nhint:%s use one of:\n\t[var].EXPECT().%s(t)\n\t[var].STUB().%s(func(...) ...)\n\n", location, methodName, methodName))
	return sb.String()
}

func mockgenMessageCallHistory(sb *strings.Builder, index int, expectedAt string, calledAt string, args []any) string {
	sb.WriteString(fmt.Sprintf("\t#%d expect at: %s\n", index+1, expectedAt))
	sb.WriteString(fmt.Sprintf("\t   called at: %s\n", calledAt))
	sb.WriteString(fmt.Sprintf("\t   arguments:\n"))
	mockgenMessageWriteArguments(sb, "\t\t%[MAX-KEY-LEN]s = %#v\n", args)
	sb.WriteString("\n")
	return sb.String()
}

func mockgenMessageTooManyCalls(m mockgenMockMethod, want int, got int, args []any) string {
	sb := &strings.Builder{}
	sb.WriteString(fmt.Sprintf("too many calls to %s.%s\n", m.interfaceName(), m.methodName()))
	sb.WriteString(fmt.Sprintf("\twant: %d, got: %d\n\n", want, got))
	m.buildCallHistory(sb, "")
	sb.WriteString(fmt.Sprintf("\t#%d expect at: %s\n", got, "missing"))
	sb.WriteString(fmt.Sprintf("\t   called at: %s\n", mockgenCallerLocation(4)))
	sb.WriteString(fmt.Sprintf("\t   arguments:\n"))
	mockgenMessageWriteArguments(sb, "\t\t%[MAX-KEY-LEN]s = %#v\n", args)
	sb.WriteString("\n")
	sb.WriteString(fmt.Sprintf("\thint: remove unexpected call or add 1 more EXPECT:\n\t\t[var].EXPECT().%s(t)\n", m.methodName()))
	return sb.String()
}

func mockgenMessageMatchByNil(m mockgenMockMethod) string {
	sb := &strings.Builder{}
	sb.WriteString(fmt.Sprintf("%s.%s Match received a nil function\n", m.interfaceName(), m.methodName()))
	sb.WriteString("\thint: provide a valid function")
	return sb.String()
}

func mockgenMessageExpectByNil(m mockgenMockMethod) string {
	sb := &strings.Builder{}
	sb.WriteString(fmt.Sprintf("unexpected nil testing.TB in %s.%s\n", m.interfaceName(), m.methodName()))
	sb.WriteString(fmt.Sprintf("\tcalled at: %s\n\n", mockgenCallerLocation(3)))
	sb.WriteString("\thint: EXPECT requires a valid testing.TB, use STUB instead:\n")
	sb.WriteString(fmt.Sprintf("\t\tspy := [var].STUB().%s(func(...) ...)\n", m.methodName()))
	return sb.String()
}

func mockgenMessageExpectAfterStub(m mockgenMockMethod, stubAt string) string {
	sb := &strings.Builder{}
	sb.WriteString(fmt.Sprintf("conflicting usage for %s.%s\n", m.interfaceName(), m.methodName()))
	sb.WriteString(fmt.Sprintf("\t%14s: %s\n", "STUB used at", stubAt))
	sb.WriteString(fmt.Sprintf("\t%14s: %s\n\n", "EXPECT used at", mockgenCallerLocation(3)))
	sb.WriteString("\thint: use either EXPECT or STUB for the same method, not both\n\n")
	return sb.String()
}

func mockgenMessageStubByNil(m mockgenMockMethod, calledAt string) string {
	sb := &strings.Builder{}
	sb.WriteString(fmt.Sprintf("%s.%s STUB received a nil function\n", m.interfaceName(), m.methodName()))
	sb.WriteString(fmt.Sprintf("called at: %s\n\n", calledAt))
	sb.WriteString("hint: provide a valid function\n")
	return sb.String()
}

func mockgenMessageStubAfterExpect(m mockgenMockMethod, expectAt string) string {
	sb := &strings.Builder{}
	sb.WriteString(fmt.Sprintf("conflicting usage for %s.%s\n", m.interfaceName(), m.methodName()))
	sb.WriteString(fmt.Sprintf("\t%14s: %s\n", "EXPECT used at", expectAt))
	sb.WriteString(fmt.Sprintf("\t%14s: %s\n\n", "STUB used at", mockgenCallerLocation(3)))
	sb.WriteString("\thint: use either EXPECT or STUB for the same method, not both\n\n")
	return sb.String()
}

func mockgenMessageDuplicateStub(m mockgenMockMethod, firstUsedAt string) string {
	sb := &strings.Builder{}
	sb.WriteString(fmt.Sprintf("duplicate STUB for %s.%s\n", m.interfaceName(), m.methodName()))
	sb.WriteString(fmt.Sprintf("\t%14s: %s\n", "first used at", firstUsedAt))
	sb.WriteString(fmt.Sprintf("\t%14s: %s\n\n", "second used at", mockgenCallerLocation(3)))
	sb.WriteString(fmt.Sprintf("\thint: %s.%s is already stubbed, remove one of the above\n\n", m.interfaceName(), m.methodName()))
	return sb.String()
}

func mockgenMessageExpectButNotCalled(m mockgenMockMethod, want int, got int, index int) string {
	sb := &strings.Builder{}
	sb.WriteString(fmt.Sprintf("%s.%s was not called as expected\n", m.interfaceName(), m.methodName()))
	sb.WriteString(fmt.Sprintf("\twant: %d, got: %d\n\n", want, got))
	m.buildCallHistory(sb, "")
	sb.WriteString(fmt.Sprintf("\t#%d never called\n\n", index+1))
	sb.WriteString("\thint: add the missing call or remove the EXPECT above")
	return sb.String()
}

func mockgenMessageMatchArgByNil(m mockgenMockMethod, method string) string {
	sb := &strings.Builder{}
	sb.WriteString(fmt.Sprintf("%s.%s %s received a nil function\n", m.interfaceName(), m.methodName(), method))
	sb.WriteString("\thint: provide a valid function")
	return sb.String()
}

func mockgenMessageDuplicateMatchArg(m mockgenMockMethod, method string, firstUsedAt string) string {
	sb := &strings.Builder{}
	sb.WriteString(fmt.Sprintf("duplicate %s for %s.%s\n", method, m.interfaceName(), m.methodName()))
	sb.WriteString(fmt.Sprintf("\t%14s: %s\n\n", "first used at", firstUsedAt))
	sb.WriteString("\thint: each argument can only be matched once, remove one of the above")
	return sb.String()
}

func mockgenMessageMatchArgHint() string {
	return fmt.Sprintf("\thint: check argument matching at %s\n\t\tor use STUB for fine-grained control", mockgenCallerLocation(3))
}

func mockgenMatchArgument[T any](m mockgenMockMethod, index int, name string, got T, match func(T) bool, wants map[string]any, methods map[string]string, hints map[string]string, tb testing.TB, expectAt string) {
	if match == nil || match(got) {
		return
	}
	tb.Helper()

	method := "func(got) bool"
	if v, ok := methods[name]; ok {
		method = v
	}

	hint := fmt.Sprintf("hint: for custom matching use .Match[arg](func(...) bool) at %s\n\tor use STUB for fine-grained control", expectAt)
	if v, ok := hints[name]; ok {
		hint = v
	}

	sb := &strings.Builder{}
	sb.WriteString(fmt.Sprintf("%s.%s call #%d argument \"%s\" did not match\n", m.interfaceName(), m.methodName(), index+1, name))
	if want, ok := wants[name]; ok {
		sb.WriteString(fmt.Sprintf("  want: %#v\n", want))
	}
	sb.WriteString(fmt.Sprintf("   got: %#v\n", got))
	sb.WriteString(fmt.Sprintf("method: %s\n", method))
	sb.WriteString("\n")
	m.buildCallHistory(sb, "call history")
	sb.WriteString(hint)

	tb.Helper()
	m.fatal(index, sb.String())
}

func mockgenReflectEqualMatcher[T any](want T) func(T) bool {
	return func(got T) bool {
		return reflect.DeepEqual(want, got)
	}
}

func mockgenBasicComparisonMatcher[T comparable](want T) func(T) bool {
	return func(got T) bool {
		return want == got
	}
}

func teststorer() *storer0 {
	return &storer0{td: &storerTestDouble{location: mockgenCallerLocation(2)}}
}

type storerTestDouble struct {
	location string
	Load     *storerLoad
	Save     *storerSave
}

type storer0 struct {
	td *storerTestDouble
}

func (m *storer0) STUB() *storerStubber {
	return &storerStubber{target: m}
}

func (m *storer0) EXPECT() *storerExpecter {
	return &storerExpecter{target: m}
}

func (m *storer0) Load() ([]Task, error) {
	v0, v1, v2 := "storer", "Load", "() ([]Task, error)"
	v3 := []any{}

	if m.td == nil {
		panic(mockgenMessageNotImplemented(v0, v1, v2, "", v3))
	}

	if v4 := m.td.Load; v4 != nil {
		switch {
		case v4.stub != nil:
			return v4.invokeStub()
		case len(v4.expects) > 0:
			v5 := len(v4.Calls)
			if v5 < len(v4.expects) {
				v4.expects[v5].tb.Helper()
			}
			return v4.invokeExpect()
		}
	}
	panic(mockgenMessageNotImplemented(v0, v1, v2, m.td.location, v3))
}

func (m *storer0) Save(tasks []Task) error {
	v0, v1, v2 := "storer", "Save", "(tasks []Task) error"
	v3 := []any{"tasks", tasks}

	if m.td == nil {
		panic(mockgenMessageNotImplemented(v0, v1, v2, "", v3))
	}

	if v4 := m.td.Save; v4 != nil {
		switch {
		case v4.stub != nil:
			return v4.invokeStub(tasks)
		case len(v4.expects) > 0:
			v5 := len(v4.Calls)
			if v5 < len(v4.expects) {
				v4.expects[v5].tb.Helper()
			}
			return v4.invokeExpect(tasks)
		}
	}
	panic(mockgenMessageNotImplemented(v0, v1, v2, m.td.location, v3))
}

type storerStubber struct {
	target *storer0
}

func (s *storerStubber) Load(stub func() ([]Task, error)) *storerLoad {
	if s.target.td == nil {
		s.target.td = &storerTestDouble{}
	}

	m := s.target.td.Load
	if m == nil {
		m = &storerLoad{stubLocation: mockgenCallerLocation(2)}
		s.target.td.Load = m
	}

	if stub == nil {
		m.panic(mockgenMessageStubByNil(m, mockgenCallerLocation(2)))
	}

	if m.stub != nil {
		m.panic(mockgenMessageDuplicateStub(m, m.stubLocation))
	}

	if len(m.expects) > 0 {
		m.panic(mockgenMessageStubAfterExpect(m, m.expects[0].location))
	}

	m.stub = stub
	return m
}

func (s *storerStubber) Save(stub func(tasks []Task) error) *storerSave {
	if s.target.td == nil {
		s.target.td = &storerTestDouble{}
	}

	m := s.target.td.Save
	if m == nil {
		m = &storerSave{stubLocation: mockgenCallerLocation(2)}
		s.target.td.Save = m
	}

	if stub == nil {
		m.panic(mockgenMessageStubByNil(m, mockgenCallerLocation(2)))
	}

	if m.stub != nil {
		m.panic(mockgenMessageDuplicateStub(m, m.stubLocation))
	}

	if len(m.expects) > 0 {
		m.panic(mockgenMessageStubAfterExpect(m, m.expects[0].location))
	}

	m.stub = stub
	return m
}

type storerExpecter struct {
	target *storer0
}

func (e *storerExpecter) Load(tb testing.TB) *storerLoadExpecter {
	if e.target.td == nil {
		e.target.td = &storerTestDouble{}
	}

	var m = e.target.td.Load
	if m == nil {
		m = &storerLoad{}
		e.target.td.Load = m
	}

	if m.stub != nil {
		m.panic(mockgenMessageExpectAfterStub(m, m.stubLocation))
	}

	if tb == nil {
		m.panic(mockgenMessageExpectByNil(m))
	}

	idx := len(m.expects)
	m.expects = append(m.expects, &storerLoadExpect{
		location: mockgenCallerLocation(2),
		index:    idx,
		tb:       tb,
	})

	tb.Helper()
	tb.Cleanup(func() {
		tb.Helper()
		m.verify(idx)
	})

	return &storerLoadExpecter{expect: m.expects[idx]}
}

func (e *storerExpecter) Save(tb testing.TB) *storerSaveExpecter {
	if e.target.td == nil {
		e.target.td = &storerTestDouble{}
	}

	var m = e.target.td.Save
	if m == nil {
		m = &storerSave{}
		e.target.td.Save = m
	}

	if m.stub != nil {
		m.panic(mockgenMessageExpectAfterStub(m, m.stubLocation))
	}

	if tb == nil {
		m.panic(mockgenMessageExpectByNil(m))
	}

	idx := len(m.expects)
	m.expects = append(m.expects, &storerSaveExpect{
		location:         mockgenCallerLocation(2),
		matcher:          &storerSaveArgumentMatcher{},
		matcherWants:     make(map[string]any),
		matcherMethods:   make(map[string]string),
		matcherHints:     make(map[string]string),
		matcherLocations: make(map[string]string),
		index:            idx,
		tb:               tb,
	})

	tb.Helper()
	tb.Cleanup(func() {
		tb.Helper()
		m.verify(idx)
	})

	return &storerSaveExpecter{target: m, expect: m.expects[idx]}
}

type storerLoad struct {
	Calls        []storerLoadCall
	stub         func() ([]Task, error)
	stubLocation string
	expects      []*storerLoadExpect
	verified     bool
}

func (m *storerLoad) methodName() string {
	return "Load"
}

func (m *storerLoad) interfaceName() string {
	return "storer"
}

func (m *storerLoad) fatal(index int, msg string) {
	m.verified = true
	m.expects[index].tb.Helper()
	m.expects[index].tb.Fatal(msg)
}

func (m *storerLoad) panic(msg string) {
	m.verified = true
	panic(msg)
}

func (m *storerLoad) buildCallHistory(sb *strings.Builder, header string) {
	if header != "" && len(m.Calls) != 0 {
		sb.WriteString(fmt.Sprintf("%s:\n", header))
	}

	for i, v := range m.Calls {
		a := []any{}
		mockgenMessageCallHistory(sb, i, m.expects[i].location, v.Location, a)
	}
}

func (m *storerLoad) invokeStub() ([]Task, error) {
	v0, v1 := m.stub()
	return m.capture(storerLoadReturn{first: v0, second: v1})
}

func (m *storerLoad) invokeExpect() ([]Task, error) {
	v0 := []any{}

	v1 := len(m.Calls)
	if v1 >= len(m.expects) {
		m.panic(mockgenMessageTooManyCalls(m, len(m.expects), v1+1, v0))
	}

	v2 := m.expects[v1]
	return m.capture(v2.returns)
}

func (m *storerLoad) capture(returns storerLoadReturn) ([]Task, error) {
	m.Calls = append(m.Calls, storerLoadCall{Location: mockgenCallerLocation(4), Return: returns})
	return returns.first, returns.second
}

func (m *storerLoad) verify(index int) {
	if !m.verified && index >= len(m.Calls) {
		m.expects[index].tb.Helper()
		m.expects[index].tb.Fatal(mockgenMessageExpectButNotCalled(m, len(m.expects), len(m.Calls), index))
	}
}

type storerLoadCall struct {
	Location string
	Return   storerLoadReturn
}

type storerLoadReturn struct {
	first  []Task
	second error
}

type storerLoadExpect struct {
	returns  storerLoadReturn
	location string
	index    int
	tb       testing.TB
}

type storerLoadExpecter struct {
	expect *storerLoadExpect
}

func (e *storerLoadExpecter) Return(first []Task, second error) {
	e.expect.returns = storerLoadReturn{first: first, second: second}
}

type storerSave struct {
	Calls        []storerSaveCall
	stub         func(tasks []Task) error
	stubLocation string
	expects      []*storerSaveExpect
	verified     bool
}

func (m *storerSave) methodName() string {
	return "Save"
}

func (m *storerSave) interfaceName() string {
	return "storer"
}

func (m *storerSave) fatal(index int, msg string) {
	m.verified = true
	m.expects[index].tb.Helper()
	m.expects[index].tb.Fatal(msg)
}

func (m *storerSave) panic(msg string) {
	m.verified = true
	panic(msg)
}

func (m *storerSave) buildCallHistory(sb *strings.Builder, header string) {
	if header != "" && len(m.Calls) != 0 {
		sb.WriteString(fmt.Sprintf("%s:\n", header))
	}

	for i, v := range m.Calls {
		a := []any{"tasks", v.Argument.tasks}
		mockgenMessageCallHistory(sb, i, m.expects[i].location, v.Location, a)
	}
}

func (m *storerSave) invokeStub(tasks []Task) error {
	v0 := m.stub(tasks)
	return m.capture(storerSaveArgument{tasks: tasks}, storerSaveReturn{first: v0})
}

func (m *storerSave) invokeExpect(tasks []Task) error {
	v0 := []any{"tasks", tasks}

	v1 := len(m.Calls)
	if v1 >= len(m.expects) {
		m.panic(mockgenMessageTooManyCalls(m, len(m.expects), v1+1, v0))
	}

	v2 := m.expects[v1]
	if v2.match != nil && !v2.match(tasks) {
		v2.tb.Helper()
		m.fatal(v1, mockgenMessageMatchFail(m, v2.matchLocation, v1, v0))
	}

	v2.tb.Helper()
	mockgenMatchArgument(m, v1, "tasks", tasks, v2.matcher.tasks, v2.matcherWants, v2.matcherMethods, v2.matcherHints, v2.tb, v2.matcherLocations["tasks"])

	return m.capture(storerSaveArgument{tasks: tasks}, v2.returns)
}

func (m *storerSave) capture(args storerSaveArgument, returns storerSaveReturn) error {
	m.Calls = append(m.Calls, storerSaveCall{Location: mockgenCallerLocation(4), Argument: args, Return: returns})
	return returns.first
}

func (m *storerSave) verify(index int) {
	if !m.verified && index >= len(m.Calls) {
		m.expects[index].tb.Helper()
		m.expects[index].tb.Fatal(mockgenMessageExpectButNotCalled(m, len(m.expects), len(m.Calls), index))
	}
}

type storerSaveCall struct {
	Location string
	Argument storerSaveArgument
	Return   storerSaveReturn
}

type storerSaveArgument struct {
	tasks []Task
}

type storerSaveArgumentMatcher struct {
	tasks func(tasks []Task) bool
}

type storerSaveReturn struct {
	first error
}

type storerSaveExpect struct {
	match            func(tasks []Task) bool
	matchLocation    string
	matcher          *storerSaveArgumentMatcher
	matcherWants     map[string]any
	matcherMethods   map[string]string
	matcherHints     map[string]string
	matcherLocations map[string]string
	returns          storerSaveReturn
	location         string
	index            int
	tb               testing.TB
}

type storerSaveExpecter struct {
	expect *storerSaveExpect
	target *storerSave
}

func (e *storerSaveExpecter) Return(first error) {
	e.expect.returns = storerSaveReturn{first: first}
}

func (e *storerSaveExpecter) Match(matcher func(tasks []Task) bool) *storerSaveExpecterWithMatch {
	if matcher == nil {
		e.expect.tb.Helper()
		e.target.fatal(e.expect.index, mockgenMessageMatchByNil(e.target))
	}

	e.expect.match = matcher
	e.expect.matchLocation = mockgenCallerLocation(2)
	return &storerSaveExpecterWithMatch{expect: e.expect}
}

func (e *storerSaveExpecter) MatchTasks(matcher func(tasks []Task) bool) *storerSaveExpecterWithMatchArg {
	if matcher == nil {
		e.expect.tb.Helper()
		e.target.fatal(e.expect.index, mockgenMessageMatchArgByNil(e.target, "MatchTasks"))
	}

	e.expect.matcher.tasks = matcher
	e.expect.matcherLocations["tasks"] = mockgenCallerLocation(2)
	e.expect.matcherHints["tasks"] = mockgenMessageMatchArgHint()
	return &storerSaveExpecterWithMatchArg{expect: e.expect, target: e.target}
}

func (e *storerSaveExpecter) With(tasks []Task) *storerSaveExpecterWithValue {
	e.WithTasks(tasks)
	e.expect.matcherLocations["tasks"] = mockgenCallerLocation(2)

	return &storerSaveExpecterWithValue{expect: e.expect}
}

func (e *storerSaveExpecter) WithTasks(tasks []Task) *storerSaveExpecterWithValueArg {
	e.expect.matcher.tasks = mockgenReflectEqualMatcher(tasks)
	e.expect.matcherWants["tasks"] = tasks
	e.expect.matcherMethods["tasks"] = "reflect.DeepEqual"
	e.expect.matcherLocations["tasks"] = mockgenCallerLocation(2)

	return &storerSaveExpecterWithValueArg{expect: e.expect, target: e.target}
}

type storerSaveExpecterWithMatch struct {
	expect *storerSaveExpect
}

func (e *storerSaveExpecterWithMatch) Return(first error) {
	e.expect.returns = storerSaveReturn{first: first}
}

type storerSaveExpecterWithMatchArg struct {
	expect *storerSaveExpect
	target *storerSave
}

func (e *storerSaveExpecterWithMatchArg) Return(first error) {
	e.expect.returns = storerSaveReturn{first: first}
}

func (e *storerSaveExpecterWithMatchArg) MatchTasks(matcher func(tasks []Task) bool) *storerSaveExpecterWithMatchArg {
	if matcher == nil {
		e.expect.tb.Helper()
		e.target.fatal(e.expect.index, mockgenMessageMatchArgByNil(e.target, "MatchTasks"))
	}

	if e.expect.matcher.tasks != nil {
		e.expect.tb.Helper()
		e.target.fatal(e.expect.index, mockgenMessageDuplicateMatchArg(e.target, "MatchTasks", e.expect.matcherLocations["tasks"]))
	}

	e.expect.matcher.tasks = matcher
	e.expect.matcherLocations["tasks"] = mockgenCallerLocation(2)
	e.expect.matcherHints["tasks"] = mockgenMessageMatchArgHint()
	return e
}

type storerSaveExpecterWithValue struct {
	expect *storerSaveExpect
}

func (e *storerSaveExpecterWithValue) Return(first error) {
	e.expect.returns = storerSaveReturn{first: first}
}

type storerSaveExpecterWithValueArg struct {
	expect *storerSaveExpect
	target *storerSave
}

func (e *storerSaveExpecterWithValueArg) Return(first error) {
	e.expect.returns = storerSaveReturn{first: first}
}

func (e *storerSaveExpecterWithValueArg) WithTasks(tasks []Task) *storerSaveExpecterWithValueArg {
	if e.expect.matcher.tasks != nil {
		e.expect.tb.Helper()
		e.target.fatal(e.expect.index, mockgenMessageDuplicateMatchArg(e.target, "WithTasks", e.expect.matcherLocations["tasks"]))
	}

	e.expect.matcher.tasks = mockgenReflectEqualMatcher(tasks)
	e.expect.matcherWants["tasks"] = tasks
	e.expect.matcherMethods["tasks"] = "reflect.DeepEqual"
	e.expect.matcherLocations["tasks"] = mockgenCallerLocation(2)

	return e
}
